### ISSUE TITLE
Town commands only work on first run

### ISSUE THREAD

**Issue by aravol** [MyEssentials/MyTown2#100]
Attempting to use the town commands from a single-player opened-to-LAN world.

When running this way, town commands work fine on the first run, but after closing the world (NOT the application) and reopening any other world (tried making new ones, opening existing ones, opening the same one) the "/t" command is no longer registered with Minecraft and reports an error

Using Minecraft Forge 10.13.2.1230
Using MyTown 1.7.10-0.26a

**Comment by dezil** [comment]
this mod is not designed to be used on a client, it is server only

**Comment by AfterWind** [comment]
MyTown really falls apart when used both on client and server. I suggest making a dedicated server instead of using LAN.
