### ISSUE TITLE
Deleted plot prevents a new plot

### ISSUE THREAD

**Issue by aravol** [MyEssentials/MyTown2#102]
Tried to make and then delete a plot, but when making a new plot I get an error saying it overlapped the old one ("NoName"). Old plot does not show up when using "Show Plots" command.

**Comment by AfterWind** [comment]
Try and make the plot using the same command but putting the name at the end of it: /t plot make namehere

**Comment by AfterWind** [comment]
Tested and had no issues creating deleting and then creating a new plot on the same spot. Guess it's fixed...
