### ISSUE TITLE
Console Spam from Mining Laser

### ISSUE THREAD

**Issue by groveham** [MyEssentials/MyTown2#113]
Testing this on my server, and one thing I have noticed is that when a player uses the Mining Laser from IC2, there is console spam, quite a lot of it and from what I can tell, there is one line of spam per block broken. 
The player isn't in a town/protection, they are braking blocks in the wild.

"22.02 15:23:29 [Server] INFO [15:23:29] [Server thread/INFO] [MyTown2]: Detected laser break."

Is there anything you could add to turn this off? Like an option in the config to disable warnings about certain tools/blocks used, or even an option to turn it off if the tool is being used outside of a town?

**Comment by AfterWind** [comment]
Yes, this will be fixed in the next version.

**Comment by AfterWind** [comment]
Technically fixed because we're not using the old protection system anymore.
