### ISSUE TITLE
MyTown2 and Thaumcraft Golems

### ISSUE THREAD

**Issue by groveham** [MyEssentials/MyTown2#115]
http://pastebin.com/iQgdxkj6

My Server crashed as a Golem attempted to place a sapling with the protection of a town. Please see the error message above.

**Comment by AfterWind** [comment]
Update MyEssentials Core. If that doesn't work, remove MT2 from the client in case you have it there.

**Comment by groveham** [comment]
MyEssentials core it up to date. And the server is crashing, it's not a client side issue. It only happens when a golem attempts to plant a sapling inside a town. If you remove the town from the chunk then everything's fine.

**Comment by AfterWind** [comment]
The issue occurs because it can't find MyEssentials-Core.
