### ISSUE TITLE
Planned 1.8 update?

### ISSUE THREAD

**Issue by SirWilli** [MyEssentials/MyTown2#116]
hey,
when is it planned to update to 1.8?

**Comment by AfterWind** [comment]
These kinds of questions should be asked here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2212817-mytown-2-0-26a-offers-protection-for-your-vanilla

Porting MyTown2 to 1.8 should not be a difficult task as we don't depend much on Forge/Minecraft code. This is the reason why we will not be porting it until it's stable or the community moves to 1.8 before that.

**Comment by SirWilli** [comment]
Okay, just thought about a 1.8 test server as there already some mods ported but unfortunately no protection yet.

**Comment by AfterWind** [comment]
I just can't afford porting and supporting 2 different versions of MyTown as I barely have enough time to work on the 1.7.10 version. Sorry :/
