### ISSUE TITLE
Plot claims to be deleted, but still shows up in plot info

### ISSUE THREAD

**Issue by Jadziyah** [MyEssentials/MyTown2#118]
I created a plot within the borders of my town, 16x16x1. After realizing it was only 1 high I went to delete the plot and make a new one in its place. After doing /t plot delete I get the 'Plot has been deleted!' confirmation message. Doing /t plot show sees no plot borders. However, when I do /t plot info in the same location, it tells me the original plot is still there. And when I try to remake a new plot which overlaps those blocks, it also tells me the original plot is still there.  I cannot simply delete the chunk from my town because of another error, the 'can't delete chunk that town spawn is in' one which isn't fixed yet but slated for a future release it seems. Any ideas would be appreciated

**Comment by AfterWind** [comment]
Both bugs were fixed but the latest version with the fix is not released yet.
