### ISSUE TITLE
"/ta add" command

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#120]
tried to add a player to a townadmin created town and got this: http://pastebin.com/hB4Ppmhr

**Comment by AfterWind** [comment]
Try deleting your DefaultRanks.json file. Maybe you have an old version of that.

**Comment by FiveEYZ** [comment]
might be a error cause its a "admintown" and when i did "/ta add Gromskar Gromskars mayor" i got: 
"The rank mayor does not exist in Gromskars!". a town created with "/ta new" wont have ranks and thats why it gives error.

**Comment by AfterWind** [comment]
AdminTowns are not supposed to have Residents.
I am aware that some of the features such as plots cannot be used in admin towns at the moment. I will work on fixing that shortly.
