### ISSUE TITLE
Wild permissions should include all flags

### ISSUE THREAD

**Issue by krwminer** [MyEssentials/MyTown2#121]
Server owners might want to disable use of certain items in the wild. Is there any reason to limit wild to be a sub-set of permission checking?

**Comment by AfterWind** [comment]
I don't fully understand the request please elaborate.

**Comment by krwminer** [comment]
wilderness.json is set to only a few possible settings.itemUse was not one of them. I do not see any reason to limit the wilderness to not not include itemUse and other possible permission flags.

Also I could not find any way to list the permission for the wild in game.

**Comment by AfterWind** [comment]
Fixed.

**Comment by AfterWind** [comment]
Reopened for adding /t perm wild list command
