### ISSUE TITLE
"/t new" issue for new players

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#129]
So a player wanted to make a town and this is what happend.

A player joins the server and want to make a town, when he does "/t new ThinkersTown" everything goes well. 
Untill the player start to claim the chunk beside it it will say "you need to be closer to your town to claim" or something, when i tell him to do "/t spawn" then he will get teleported to our server spawn located at x:0 z:0

when i tried to make a town in the same chunk it said i was to close even if his "/t spawn" was at x:0 z:0

so i told him to delete his town and then i did "/t res THinkaZ"

 [CHAT] &7 --------  Resident: &aTHinkaZ &7--------
 [CHAT]  &7Towns: &fnull
 [CHAT]  &7Joined: &fSaturday, March 14, 2015 10:46:14

for me it works 100% and there is no errors in the logs when they create a new town.

**Comment by AfterWind** [comment]
When you do /t spawn if tries to get the town's spawn, if it doesn't find it it simply teleports the player to the world's spawn. When he deleted he's town is fine if the "Towns" says it's null since he's not in any towns anymore.
Basically the issue has something to do with /t claim and its checks. Got it!

**Comment by FiveEYZ** [comment]
the chunk the player are standing in dosent get updated with entry/leave message

**Comment by FiveEYZ** [comment]
from irc yesterday:
"8:53:01 PM <Flenix> Hey all. Standard players on my server can make a town but don't get any claimed land when they do so. For example, they type /town new TownName, and it confirms the town is made - but if they do /town setspawn without moving they're told they aren't in their town area. They also can't claim as it's not attached. Is this a permissions issue or a bug?"


I also want to say that im now using cauldron and "itemCost" is sponge, new players are able to make new town without problems.

**Comment by FiveEYZ** [comment]
I don't think this is a issue anymore, closing for now
