### ISSUE TITLE
"/t friends list" problem

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#133]
Problem with friends, u can remove them but everyone of them will be restored after a server reboot.

"/t friends remove <name>" gives: "Player has been removed from the friends list!"
with no error in console, "/t friends list" will get updated with the name removed. 

All names are restored after a server restart.

**Comment by AfterWind** [comment]
This is the only feature I wasn't able to test on my own xD

**Comment by dariusc93** [comment]
Possibly that is it not saving like it should? Also @AfterWind how i test things when i know its a multiplayer feature is launching two small clients and connect to a local server and test that way ;)

**Comment by AfterWind** [comment]
Yeah, I just found out I can make 2 instances of same modpack on MultiMC for testing. Now I can actually test it properly.

**Comment by FiveEYZ** [comment]
issue have been resolved
