### ISSUE TITLE
mobs

### ISSUE THREAD

**Issue by krwminer** [MyEssentials/MyTown2#136]
I think the mobs setting is unclear and it current only works for "hostiles".

I think the flag should be "allowedMobs" and it should have the settings "all", "passive" or "none".

Currently it only checks for "hostiles" and ignores the "all" or "none" settings.

**Comment by AfterWind** [comment]
I will change most flag names to something that will always mean true=active false=inactive since that's how the stuff in code is. As for the "mobs" flag its name will be changed to "allowedMobs" or something similar.

**Comment by krwminer** [comment]
More than just an enhancement. Currently setting "all" or "none" do the same thing, that does not make sense.

**Comment by krwminer** [comment]
This really should be put on the list to be fixed before the next release.
