### ISSUE TITLE
Thaumcraft Golems Placing blocks

### ISSUE THREAD

**Issue by groveham** [MyEssentials/MyTown2#137]
It seems that Thaumcraft Golem's can't place blocks (such as sapplings) for tree farms in town protected chunks. Works fine if your outside town, but not when they're in a town. 

I advised a player to try adding [FakeThaumcraftGolem] as I believe that's the fake player name for the golems but now MyTown2 is waiting for the fake player to accept the invite (which it cant do) and I can't see anything in the console about accepting it either incase it was forwarded there.

**Comment by AfterWind** [comment]
You can add any player yourself, if you're an op with the command: /ta add (player) (town) [rank]
What version are you using?

Protection related issues should go here from now on: https://github.com/MyEssentials/MyTown2-Protections/issues/

**Comment by groveham** [comment]
Running:
MyEssentials-Core-1.7.10-1.4-universal.jar
MyTown2-1.7.10-0.26a.jar

Sorry I'll post protection issues there from now on, I've saved the link
