### ISSUE TITLE
trample crops

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#139]
need to disable the ability for outsiders (or maybe everyone) to trample crops in a town

**Comment by FiveEYZ** [comment]
One of the biggest reason i have Kcauldron is that im able to use Worldguard just so i can disable the ability for players/mobs to trample crops.

https://github.com/jascotty2/worldguard/blob/master/src/main/java/com/sk89q/worldguard/bukkit/WorldGuardPlayerListener.java#L764

https://github.com/jascotty2/worldguard/blob/master/src/main/java/com/sk89q/worldguard/bukkit/WorldGuardEntityListener.java#L140

these links might be useless as its a bukkit plugin, i just wanted to throw them in here :)

**Comment by joserobjr** [comment]
There's no forge event for this. The method that process the crop trampling is `BlockFarmland.onFallenUpon()`

If we need to patch we would insert code after the first `FRAME SAME`

**Comment by krwminer** [comment]
If you would be willing, please submit a PR for this. I had looked into this briefly and figured out that we need a patch for Forge in order to do this also.

**Comment by 0zlw** [comment]
Not sure if it's just us but we tested this functionality out with the following versions and it didn't seem to block an outsider from trampling Vanilla or AgriCraft crops.

Versions:
MEC: 99
MyPermissions: 47
MT2: 311
