### ISSUE TITLE
Can't access Mystcraft book - only if I move it far enough away from a specific place

### ISSUE THREAD

**Issue by retrozool** [MyEssentials/MyTown2#143]
I have MYTown2 MyTown2-1.7.10-115-dev installed.
I have one town called Portal which is directly next to a chunk (in the wild) which contains a Mystcraft book (reason being is that I did not manage to make people access it in the town if they are not residents)
It was always able to access that book.
This changed (I think) after I created a new town far away.
I did the following:
My active (selected) town is Portal.

/t new xxx
and then tried to claim chunks with /ta claim xxx
This did not work as my active town was Portal and I can do a "far claim"
so I did
/t select xxx
an then claimed chunks around town xxx with /ta claim xxx

Since then it seems that the book is no longer accessible. Maybe my town "thinks" that the chunks around town "portal" now belog to it and have the same permissions.
What I did then was deleting Portal completely - did not help
recreate portal, changing all permissions to "true" - did not help
If I move the book about 2 chunks away then it works again
/t map did not show the town after I deleted it.

Hope that explains my situation somehow - and I can also suggest to show it "live" if necessary

**Comment by retrozool** [comment]
one more information - seems that the distance it needs now for the book to be accessible again is 8 blocks (not chunks) from the town Portal. on the 9th block it's accessible again.

**Comment by AfterWind** [comment]
This was a weird consequence of another very strange bug. Should be fixed now. Jeez, what Mojang code can do o.O
