### ISSUE TITLE
no permission for /t borders show 

### ISSUE THREAD

**Issue by kalelreturns** [MyEssentials/MyTown2#144]
I'm using dev build #115. I'm a resident in a town and don't have permission to use this command: /t borders show.  I added "mytown.cmd.everyone.borders.show", to the resident rank and does nothing. I make sure I was inside the town and had the correct town selected. I even restarted the server and it still doesn't work.

**Comment by AfterWind** [comment]
Could be because you need an updated RanksConfig file. Try deleting the old one and launch it that way.

**Comment by kalelreturns** [comment]
That worked. Thanks.
