### ISSUE TITLE
Using plot commands Fail to identify plot.

### ISSUE THREAD

**Issue by Travistbh** [MyEssentials/MyTown2#146]
/t plot info
/t plot perm set .....

As the town creator these commands fail to acknowledge the plot that i stand on.

"your are not standing in a plot!"

**Comment by AfterWind** [comment]
What version are you using. I have tested with latest build and it works for me. Keep in mind that plots are a 3D shape not only a plane, if you have it as a plane it might be tricky to be inside of it.

**Comment by AfterWind** [comment]
The bug is related to the position of the player not being rounded 100% correctly.

**Comment by Travistbh** [comment]
using /t claim   

not manualy creating plots.   

any command i attempt to use with plots whether im above below or in the middle of it results in  same error.   build #122
