### ISSUE TITLE
issue with enter=false

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#149]
some towns have made a nether portal and have the flag "enter" on false, when a outsider use the portal to get to the overworld they will be stuck inside the town.

Because they are stock inside the portal they cant open chat to enter a command to tp away from there.

1 way to solve it would be to tp the outsider to nearest town border.

**Comment by cjm721** [comment]
Which is then over a pit of lava. Better solution might be to check where the portal comes out at and prevent the dimensional teleport.

**Comment by AfterWind** [comment]
Fixed, but I can only send the player back to its spawn.

**Comment by krwminer** [comment]
Sending the player back to spawn is the best thing to do anyway. I did not check, but make sure you send them a chat message letting them know what happened though.
