### ISSUE TITLE
ConfigProcessor doesn't support float types.

### ISSUE THREAD

**Issue by AfterWind** [MyEssentials/MyTown2#150]
Having this value in the Config class does not appear in the config itself.

**Comment by legobear154** [comment]
The main reason why is because forge Configuration class doesn't directly support floats. It does, however support doubles. I can see about doing an extra check and cast to get it working for floats.

**Comment by AfterWind** [comment]
Oh, ok, I'll use doubles for now but leaving this here for now, but not high priority.

**Comment by krwminer** [comment]
Has this been fixed? If not, is it really an Enhancement?

**Comment by AfterWind** [comment]
oops. New config supports it.
