### ISSUE TITLE
Shops - Creation , use, and methods (Current findings)

### ISSUE THREAD

**Issue by Travistbh** [MyEssentials/MyTown2#156]
Creation - 
very simple to use, no issues with creating signs.

Using shops-  
- [x] trying to use a shop throws an internal error.   
- [x] Items used to throw the error,  signs, brick stairs,

The result is the same for both buy and sell.

Methods -  
- [ ] sellBuy needs 4 arguments instead of 3.  <sellBuy> <amount> <sellPrice> <buyPrice>

No Reports generated as result of internal server error.

**Comment by AfterWind** [comment]
Reports can be found in the server's log.

**Comment by Travistbh** [comment]
<script src="http://pastebin.com/embed_js.php?i=80iPg3m7"></script>

**Comment by Travistbh** [comment]
./t claim now returns an unexpected error.  however /ta claim <town> works properly

**Comment by AfterWind** [comment]
I think this is an issue with the new economy system implemented by @legobear154 
Gonna try and fix it.

**Comment by AfterWind** [comment]
Should be mostly fixed now.

**Comment by Travistbh** [comment]
I have confirmed that by changing the cost item from $ to $ForgeEssentials  fixes server restarts and successfully created shops and they work now.  Build #130  and MEC 5

**Comment by Travistbh** [comment]
oh yeah needs 4 args

**Comment by AfterWind** [comment]
Moved to https://github.com/MyEssentials/MyShops/issues/2. Closing.
