### ISSUE TITLE
Error. CRASH

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#162]
Can tou take a look on my crashreport.

http://pastebin.com/2hAKR9d2

have you any idea of what it could be?

THe location mentioned is actually the SPAWN

(0.00, 64.10, 0.00)

**Comment by AfterWind** [comment]
I am suspecting Forge for being the issue here, try another version and see if it fixes the issue.

**Comment by evernife** [comment]
I hadn had another error like this. If happens again i will change the forge.
