### ISSUE TITLE
Whitelist Message

### ISSUE THREAD

**Issue by greeneLeader** [MyEssentials/MyTown2#165]
Please add a message saying that you have been given a selector tool to add a whitelisted item to your town perms because it is hard to know anything happened when it goes into your inventory and you don't see anything telling you that something happened.

**Comment by AfterWind** [comment]
The whitelister is not 100% implemented, I will get around to that when I finish implementing it.

**Comment by greeneLeader** [comment]
Ok and thanks for a great mod
