### ISSUE TITLE
New Towns bug  (0.0.2b)

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#167]
My players make new towns but theis towns are Admin Towns.

They use the command /t new Name
and make admin towns randomly

They dont have the permission to make /ta new
this is really boring.... :c

**Comment by AfterWind** [comment]
Are you sure? I have tested it and nothing of sorts happens for me.
How do you know they are admin towns?

**Comment by evernife** [comment]
Yes, when i type, /t list
this is what i get http://prntscr.com/6uo1cx

The only permission that they have is "cmd.mytown".

**Comment by AfterWind** [comment]
Having "SERVER ADMINS" as mayor simply means there is no mayor for that town. I am not sure why that might be, but I can't reproduce your problem sadly. Any errors that appear in the server console or log file once somebody creates a town?

**Comment by evernife** [comment]
So, i was looking the console, this are the ''suspect'' things that i saw.

First: Permissions :/ 

[MyTown2/MyTown2]: Permission node mytown.cmd.assistant.rename is missing from the configs in rank Mayor
[MyTown2/MyTown2]: Permission node mytown.cmd.assistant.rename is missing from the configs in rank Assistant

Second: Console error: http://pastebin.com/3nn5mDxh ; http://pastebin.com/PjCxqeyQ ;
\-->Really suspect ^^
NOTE: This error occuer a lot of times, it seems the right error to me :/

**Comment by AfterWind** [comment]
Ok, I see the issue now, thanks.

**Comment by evernife** [comment]
You know, you are the best modmaker gye that i know, you do a really amazing job man, i dont know what will be of me without your work ^^

Ty For everything.

**Comment by AfterWind** [comment]
I still am having trouble replicating the issue. Can you please give me the data.db file? It's found in config/MyTown.

**Comment by evernife** [comment]
sure. Here it is http://www.mediafire.com/download/mqkfwz8wfa5692j/data.db

**Comment by evernife** [comment]
Not appeared again in the last days. Closing for now.
