### ISSUE TITLE
Couldn't process command: 't perm set nearbytowns true'

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#168]
When me and my users try to use the flag: "nerabytowns" we got this error.
http://pastebin.com/EpCVaFCw

And the localization for the error when try to create a town too near another one is an missing, actually,  we got this when try to create some town ner to another: http://prntscr.com/6ux41y
I think its only the localization, but, there is no cost to say ^^

**Comment by AfterWind** [comment]
/t perm set nearbyTowns true
is the command you should be using.

**Comment by FiveEYZ** [comment]
yep its case sensitive

**Comment by evernife** [comment]
yes, i used it, and i get this error.
I used this comand: /t perm set nearbyTowns true
Sorry, i wrote this wrongly upthere...

But, i am getting this error, take a look at the bins please :D

**Comment by AfterWind** [comment]
Which error? You didn't send me anything.

**Comment by evernife** [comment]
Now it works, sorry for the wrong bug :c

But the text still is buged :D 
http://prntscr.com/6ux41y

**Comment by AfterWind** [comment]
That's not such a big issue, I will add it next version.

**Comment by evernife** [comment]
:V
