### ISSUE TITLE
[Request] New way to claim admin Towns

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#170]
I way to claim large amount of claims at the same time, just for admins.

Look, i have  a spawn that have more than 60 chunks, i need to claim one by one, it took me a lot of time, i think i will be nice to have a way to claim then more rapdly.

**Comment by AfterWind** [comment]
This already exists
simply do: /t claim <range> or /ta claim <town> <range>
And it will claim a SQUARE around the player with the length of 2*range + 1.

**Comment by evernife** [comment]
ty
