### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#171]
I found my server with lag and i saw the log, and this ''things'' was in there.
I dont understant them, but it will be useful to me to know if it is a bug from the mytown, or forge, or even other mod.

http://pastebin.com/Cw5StuF5

**Comment by AfterWind** [comment]
Pretty sure it's Forge... again. I am verifying if an entity is null before sending the message.

**Comment by evernife** [comment]
That is the version that you commend me?
