### ISSUE TITLE
Unknown Error when changing Town Permissions

### ISSUE THREAD

**Issue by PlanetBeast** [MyEssentials/MyTown2#173]
When using MyTown 2 on a Cauldron server using the PermissionsEx plugin for permission nodes, when a town is trying to change the state of a town perm (flag) an unknown error occurs. [Here](http://pastebin.com/jA0L35FM) is the error that pops in console when trying to change the mob flag. A similar log is posted with the other flags as well.

**Comment by AfterWind** [comment]
What are you trying to do...
To change a town's flags you need to do:
/t perm set <flag> <value>
or, for admins, in which you have to specify the town's name (which seems to me that that's what you want):
/ta perm town set <town> <flag> <value>

This error keeps on popping up, I need to send the message back to sender, which I forgot, that could be considered an issue. I will leave this open just for this issue.

**Comment by PlanetBeast** [comment]
Odd. Now it seems to be working fine. I don't know what was wrong before. Thanks for the response though :)
