### ISSUE TITLE
Damage from entities that are controlled by players bypasses pvp flag.

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#174]
I metioned that in the Forum, but, it is really necessary.
As you said to me, add a flag in the Admin Towns and, maybe, wild.

Even when the PvP block in the Town, DOGS can still kill players, i think it will be more usefult the invencibility than block the dog, or, maybe, both :D

(add the block dog damange to the flag "PvP")

I jut make it here just for you dont forget :D

**Comment by AfterWind** [comment]
I have added this to my TODO list, which can be found here: #141 
But it's alright to keep it here as well. I have my TODO list just so I don't flood the issue list. :)

**Comment by evernife** [comment]
:D

**Comment by AfterWind** [comment]
I made the flag that protected entites protect players as well. Although having a `god` flag would be overpowered so we'll find a way to get the player that is controlling dogs.

**Comment by krwminer** [comment]
Tamed Wolves, (DOGS), will not harm a player now if PVP is false.
