### ISSUE TITLE
Forge Version

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#175]
What is the most compatible version of forge to MyTown2 ?

**Comment by FiveEYZ** [comment]
forge 1307 was to low for me using 1343 atm and its working pretty well

**Comment by evernife** [comment]
i am using the Recommended build and having a few inssues [10.13.2.1291]
So, the best thing is ask :D

**Comment by evernife** [comment]
AfterWind, what version should i use?

**Comment by AfterWind** [comment]
Try 1343, if that's what @FiveEYZ  uses and works for him.

**Comment by evernife** [comment]
ty

**Comment by FiveEYZ** [comment]
still getting this error on cauldron (forge 1343) http://pastebin.com/57tqRxAJ
cant use any newer version or the recommended build of FTB Infinity (1.3.4) wont work.

**Comment by evernife** [comment]
FiveEYZ
I dropped the cauldron, its better use only forge sistem, really less lag...
