### ISSUE TITLE
Crash when sending messages to players.

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#178]
http://pastebin.com/gtZ1xUtM

**Comment by AfterWind** [comment]
You've already reported this.

**Comment by AfterWind** [comment]
Duplicate of #171

**Comment by evernife** [comment]
strange, its another inssue, in previous time you said it was forge, but, now, i changed for version...

Do you think is still forge?

**Comment by AfterWind** [comment]
Now I don't but I can't find the issue in MT2 either :/

**Comment by evernife** [comment]
Ok, ty

**Comment by evernife** [comment]
Sir, really, can you take a look one last time.
http://pastebin.com/eaQAxA6g

I can't see other mod who can make this.

I will try to change the forge version one more time...

**Comment by AfterWind** [comment]
When does it happen, maybe I can do a workaround for this. I am still very convinced Forge or Minecraft is doing something derpy.

**Comment by evernife** [comment]
This is happen a lot of times. Sometime, when the server restart, in less the 5 min it occurs.
I didn't found what is the cause of it. I will try to. :/

**Comment by evernife** [comment]
Just to say, the frequency that this happens is like: (10 or 15 times per day)

**Comment by AfterWind** [comment]
Is this still happening?
