### ISSUE TITLE
Industrial Craft not protecting

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#179]
Blocks of the indutrial craft can be accessed by players outside of the Town. The protection of grief is perfectly working, but they can access the blocks...

**Comment by krwminer** [comment]
In general, problems with Protections should be reported here:
https://github.com/MyEssentials/MyTown2-Protections/issues

Are you saying someone standing outside of town on the border can access blocks in the Town? But when they enter the Town they can not access them?

**Comment by evernife** [comment]
Open an issue there.

No, i am saying they can open the block inside and outside the town :/

**Comment by FiveEYZ** [comment]
did u get the updated ic2 file i pushed 2 days ago? cause i cant access ic2 machines in another town without being OP

**Comment by evernife** [comment]
ok, i will downlaod again, i will keep this open till i test the inssue :D

**Comment by evernife** [comment]
Solved.
