### ISSUE TITLE
infinit cost item

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#180]
Some of my players can take infinite of the cost item.}
He was in a town, but he disbanded his town to make in some other place.
But, by mistake, he spelled the command: "/t leave delete" two times, and received the item again, and now, everytime he spell the command "/t leave delete" het get the cost item.

**Comment by evernife** [comment]
PLUS: 
-No console error.
-Print: http://prntscr.com/6w35x2

**Comment by evernife** [comment]
Any progress?

Sorry for asking, but this is a really boring bug :c

**Comment by AfterWind** [comment]
Sorry, I am very busy this week and can't do much progress on it :/

**Comment by evernife** [comment]
Its ok

**Comment by AfterWind** [comment]
I can't reproduce this bug. Please give me the details on how it happened.

**Comment by evernife** [comment]
Didn't happen again, maybe we will need to wait some other user have this one :/
