### ISSUE TITLE
Spawn command not working properly and disabling of commands.

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#182]
First, there is a bug that if you try to use /t spawn in other dimmesion you dont get back to your spawn, you go to a spawn at the same location (cords) in the dimmension you are.

For exemple: MY house is un cords 100 90 100 ant DIM 0
When i use in the nether, i go to the cords 100 90 100 but in the NETHER,

Second point, a way to disable the /t spawn (and /t setspawn)
Because it is better use the ForgeEssetials ''home'' (because /t spawn is not compatible with the entire teleport system of ForgeEssentials, and /back not works)

**Comment by AfterWind** [comment]
/t spawn works for me, although it is quite slow :/. Are you using cauldron?
You can disable any command by modifying the DefaultRanks.json config file. Simply put a "-" behind mytown.cmd.everyone.spawn to disable /t spawn command.

**Comment by evernife** [comment]
I am using Forge.
I am using the 0.0.2b

I will try to get a few exemples, this happens only a few times. (random)

**Comment by groveham** [comment]
I can confirm this happens as well, running forge and 0.0.2b. Players on my server state it happens but has never happened to myself
