### ISSUE TITLE
Cannot use items in here!

### ISSUE THREAD

**Issue by zacekjakub** [MyEssentials/MyTown2#185]
Hi, I am not sure this is bug of mytown, I have nothing in log, but because it's permission problem, I thought it could be MyTown thing. It started happening on our server (can't exactly say when) and it's happening to our users one by one. One day working, next day this fail appears for the same user and we really can't find the reason.

Does it seem to you like MyTown fail? Thank you. :)

**Comment by evernife** [comment]
Hmm, its a flag.
FIRST: Use the latest version.

This is flag prevent players from using any item in a town, for exemple, players cant use a ender pearl, or a bucket.

When/where this menssage appears?
Is when a player who is not resident tries to use an item in others towns?
Is When inside an AdminTown ?
Is in the wild ? 

I use the mod in my server too, never seen a "bug" like this...

**Comment by zacekjakub** [comment]
Hello,

it's version 0.0.2b and we really can't use experimental version on the server, I tried once and it was a bad idea.
When/Where: anytime, anywhere, to the already affected players. I don't know when it happens, users can do anything until some time, but I still don't have any idea what is the problem when this problem starts. It doesn't affect only the town, but they can use water nowhere.
U asked three more questions, but I think the first answer told it all. :)

I can give you an access to the server itself as well as to the logs or send you our synch app for minecraft... It installs all the necessary mods and so on and you can connect with affected name.

Thank you guys.

Jakub

**Comment by AfterWind** [comment]
Use the command "/ta perm wild set useItems true"
That should fix it, if you say it's happening everywhere.

**Comment by zacekjakub** [comment]
Ok, going to try in about two hours. I 'll let u know, thanks. :)
Dne 30. 4. 2015 12:56 PM napsal uživatel "Sergiu Muresan" <
notifications@github.com>:

**Comment by zacekjakub** [comment]
Thank you guys, the command helped us.. I just can't get why it started doing to users after some time and not exactly from start.

**Comment by evernife** [comment]
zacekjakub, when you said "send you our synch app for minecraft..!"

Can you give to me, i am a server owner and i want a nice modpack launcher for players, i will be really nice to test yours.

**Comment by zacekjakub** [comment]
Hi, no problem.. Only problem for you is that it's in Czech language and hardcoded for our server. But in fact, change language and server details should take a few minutes...

Legend:
1st button download mc
2nd just actualize mc, never necessary to use
3rd run mc- it starts cracked mc launcher (preconfigured) and u have to click run mc there again..

But that's all. I think it's really simple...

here download the app:
http://37.205.10.29/stahnout/install.exe

In case of any questions:
mail: jakub@zacekj.cz
skype: zacekjakub
gtalk: zacekjakub

Let me know. :)

**Comment by evernife** [comment]
The language took me down, but in any case, no problem, i am using the techinic launcher, for now its ok :D
