### ISSUE TITLE
"/t spawn" - Crashs

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#189]
I have found a way to get this crashs:
#178
#171
#187
#186

I mentioned before that sometimes the "/t spawn" did not work, and is a bit rare and this not happens with all players.. I mentioned it here: #182

I got this crashs, two or three times following this steps:

1--> Going to the nether
2--> Using the command "/t spawn"  (note: For this crashes to happen, the command /t spawn couldn't work, when you use the command you stay at the same LOCATION...)
NOTE: As I said, this happens only a few times...
3--> Now, use the command /spawn (i am using ForgeEssentials)
4--> The server crash...

Latest Crash: http://pastebin.com/Fx7V4aUn

All related to the "/t spawn" or to the "teleportation" in fact. (I think '-' )
Its a bit hard to reproduce... i will try to get more conditions like items, or armors, or lvl, etc...

EDIT:
http://pastebin.com/bw8fNGLs

**Comment by AfterWind** [comment]
The first crash report is actually on the wireless redstone mod's side.

**Comment by evernife** [comment]
Maybe in some of the crashes.
If mytown is removed, there is no more random crashes....

**Comment by krwminer** [comment]
Teleport code has been redone in the current versions of Core and MyTown2 on Jenkins:

https://ci.mineguild.net/job/MyTown2/
https://ci.mineguild.net/job/MyEssentials-Core/

Please let me know if you are still having problems.
