### ISSUE TITLE
/ta kick NICK TOWN

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#190]
Is there a way to remove someone from a specific town ?

There is actually a way to add someone /ta add NICK TOWN
But there is not a way to kick a person from a town....

This seems really basic, but, i think you forgot about this command --'

**Comment by AfterWind** [comment]
I know it's not really intuitive, I might just change it to /ta kick instead.

**Comment by evernife** [comment]
--'
Make sence
