### ISSUE TITLE
Towns in dimensions that are not loaded on startup get deleted

### ISSUE THREAD

**Issue by cnaude** [MyEssentials/MyTown2#192]
When we create towns on mars they get saved to data.db. On startup of the server towns and worlds associated with mars (dim-29) are deleted.

**Comment by spannerman79** [comment]
Forge version?
Server log?

**Comment by AfterWind** [comment]
Pretty sure there shouldn't be any logs for that, the towns found in a different dimension are a little bit difficult to deal with, but I will try to fix this.

**Comment by cnaude** [comment]
My suspicion is that MyTown is loading too fast and needs to wait for Galacticraft to load fully. I noticed in your code that you check if a dimension is valid on startup. If the dimension is not valid the towns and world are deleted.

Forge: 10.13.2.1291
BTP12: https://www.atlauncher.com/pack/bevostechpack/

**Comment by cnaude** [comment]
I wonder if my players can place a chunk loader on mars as a temporary workaround.

**Comment by spannerman79** [comment]
You could also issue a /gckeeploaded without the need for a chunk loader

**Comment by cnaude** [comment]
@spannerman79 That's an excellent suggestion. I see that it supports static dimensions. I'll give that a shot.

**Comment by cnaude** [comment]
Maybe a good solution is to simply not delete towns and worlds on startup. instead print a warning message in the log that a dimension was not found and there may be orphaned towns. Or make it a configurable option. Just my .02c.

**Comment by AfterWind** [comment]
That's a good suggestion, I will have to see about how I will handle the situation. I don't really want towns that don't exist anymore to be lying around in the memore and database so I need a way to delete them but then again that scenario is pretty rare.

**Comment by spannerman79** [comment]
Then perhaps make it a ops/admin command to purge the database @AfterWind  ?

For example;

/townadmin purge <dim>
then needing a second command within 10 seconds
/townadmin purge confirm

**Comment by AfterWind** [comment]
"/ta db purge"
To delete the whole database, but can only be done through the server's console.

**Comment by cnaude** [comment]
We tested using the static dimensions in galacticcraft and that resolved the issue.

**Comment by AfterWind** [comment]
Does this still occur?

**Comment by AfterWind** [comment]
Fixed.
