### ISSUE TITLE
Dynmap integration

### ISSUE THREAD

**Issue by Zerzix** [MyEssentials/MyTown2#193]
It would be nice to see towns displayed in Dynmap for forge.

**Comment by AfterWind** [comment]
Duplicate of #27.
I will get to it once we have a client-side version of the mod :)

**Comment by cjm721** [comment]
Dynmap is a server side map to allow connections from a web browser. Its not something you install on the client.

**Comment by AfterWind** [comment]
I am aware of that, it's just scheduled after I release the client-side simply because it will have lots of the same code.
