### ISSUE TITLE
Friend Remove Crashes Client

### ISSUE THREAD

**Issue by oryfoxer7410** [MyEssentials/MyTown2#195]
When we do /t friends remove it crashes the game client, however, the friend does appear to be removed from the town. 

I'll update with a pastebin shortly.

**Comment by AfterWind** [comment]
Do you have mytown in your client? If so, please remove it, it's not needed AND it is not suggested to have it there, as it will cause crashes like this one.

**Comment by oryfoxer7410** [comment]
No, this is on a server side only.

**Comment by AfterWind** [comment]
Oh, I see what the issue is. Thanks for the report and sorry about my last comment, I've seen a LOT of people trying to install mytown on the client and I jumped to conclusions :(
