### ISSUE TITLE
[Request] Plot management

### ISSUE THREAD

**Issue by yepidoodles** [MyEssentials/MyTown2#197]
The new plot management system is complicated, inefficient and annoying to use... The chunk based system from the original MyTown is much better in my opinion. I have a 60 chunk radius town on my 1.6.4 server with MyTown and that was so much easier to set up than what I am trying to set up currently... The heights are especially frustrating.

**Comment by yepidoodles** [comment]
Also, when someone, anyone, and it only has to be one person, has the plot/ town borders on, no one can break the borders, even if they have them off... This is annoying and frustrating.

**Comment by yepidoodles** [comment]
Another thing is when you walked in and out of plots it would say ~<name> or ~Unassigned - I'd be grateful if you added that back in; everyone liked that

**Comment by evernife** [comment]
Have your mother taught you manners?

Dude, look here, are you paying for this mod? I think not.

If you have bugs or requests to make, nice, but if you don't liked the mod, please, just don't download it...

I am using this mod on my server, it is a really helpful mod, if you prefer the old MyTown, PLEASE, continue using it...

This mod is still in BETA, is still im progress, he is doing what he can to make a good MOD.
So... if you have a request, make this in a pleasant way... 

And one more thing, this is MyTown2 --- "2" ---
This means that can be different from MyTown :D

(NOTE: I am just a user, good day sir )

**Comment by yepidoodles** [comment]
I could say the same to you, I am giving feedback based on my experiences and my community's feedback. I liked the old MyTown and there is no other mod which even comes close, and that is also the opinion of my community. 

Also, I would happily pay any amount of money for this mod, and would happily donate if asked, and have offered to donate in the past, and once AE2 protection is added (Which is currently no fault of the MyTown devs) I will donate that $50 I promised, but until AE2 is protected, I don't think this mod is really much better than the rest, at least currently until it lives up to the original version of MyTown.

' if you prefer the old MyTown, PLEASE, continue using it...'
NOTE: The old MyTown is ONLY 1.6.4. Not 1.7.10, my 1.6.4 server currently runs the original version.

And yes it is still in BETA, and I'm trying to help develop it by pointing out issues and changes which could be used to improve it. The dev's do not have to listen to my input, they can throw it in the trash if you like; But the original MyTown was perfect, and I think following that lead will be what's best for the mod as pretty much the only people using it are those who used the original MyTown. 

And yes, this is MyTown2, but it was also re-wrote pretty much from scratch so there is alot of differences and many of them aren't better than the original; and I feel the original features were often better; especially the chunks based plots. If you have used the previous version of MyTown as much as I did, I'm sure you'd have the same opinion. I have been a server owner/ Admin for nearly 2 years, so don't try to undermine what I say. I have opinions and so do you, keep them off my request thread.

- Alice

(NOTE: I am no sir.)

**Comment by AfterWind** [comment]
I don't think she is rude on anything. Just saying your complaints is all
well and good. She's not paying for the mod but the fact that she's
reporting to me means she's helping.

I do agree with the fact that plots are a pain to use at the moment.
Although I don't want to switch back to the chunk based one simply because
of them being restrictive.

A first step of doing this better would be to stop using so many commands
and just use one and two rightclicks with a wand.

A second step would be to make a graphical interface for admins in the
Mytown2 Client ( which I have barely started) and have it select
coordinates for plots that way en mass.

What do you think of these two first ideas for improvement?

**Comment by evernife** [comment]
These ideas are really good, this remembers me of the protection system "GrifPrevention" (bukkit plugin)... 
(Players are really used to this system, using a GoldShovel to protect the claim... 
{The tool could be configurable})

It was really easy to use, no commands :D

But I really didn't like the idea of clients. You said for admins, so it can be done, but a client for the normal user it would difficult the modpack update. 

In any case, LADY yepidoodles, forgive me for my misunderstanding....

**Comment by yepidoodles** [comment]
I agree that the chunk system can be rather restrictive, I remember when I first switched from Grief prevention to MyTown, there were many concerns over that; But, it is the height which is rather irritating, perhaps adding a command that works the same as '//expand vert' which makes the selection cover the entire height of the plot might work as a good solution.

I don't really understand the client idea, you'll have to explain that a little more, and in terms of modpack update, I have my own modpack off the techniclauncher so it would be very easy for me to add it.

And you are forgiven evernife

**Comment by yepidoodles** [comment]
A quick question, I tried setting /town perm set restrictedtownperms true (As it is currently listed as false) but it doesn't work. What is the value for this?
Another thing which would be handy to add would be an error message for when a flag does not exist, it currently says 'An unknown error occurred while attempting to perform this command' and leaves lots of lines of gibberish in my console.

**Comment by yepidoodles** [comment]
Another thing which is odd, when claiming using '/town claim' it gives this text:
https://gyazo.com/63b7af1f4d64facf286641f29689db7f
And this console error:
https://www.dropbox.com/s/s5gerowprpx3dv4/Mytown%20claim%20error.txt?dl=0

**Comment by evernife** [comment]
I did't het this error, Are you using what version of MyTown?

**Comment by yepidoodles** [comment]
0.0.2b

**Comment by evernife** [comment]
Its normal for me :/ 
http://prntscr.com/75vqem
What forge version are you using?

**Comment by yepidoodles** [comment]
Sometimes It works fine and other times it doesn't, I'm running Cauldron 1.1307.06.218 which I think is forge 1291

I sometimes have an issue when people make a town too
http://gyazo.com/7049a751a265d81c4d7f2680f3b425b4
Someone makes a town and it turns into an admin town even when they are not op'd and use /mytown new <name>
https://www.dropbox.com/s/rcp8lgevy40qeei/Mytown%20town%20error.txt?dl=0

**Comment by evernife** [comment]
Yes, i have had this problems too (#167), in any case it seems to not occuer anymore, i have a new forge version.
But, i think you could test it for us, 

Here, take one of this cauldron versions and test (make a backup before please)

(I am using only forge because i am using fastcraft, so i didnt tested it with cauldron )

**Comment by yepidoodles** [comment]
I don't have any choice but to use Cauldron, as it's the only thing which combines both forge and bukkit - and they haven't updated to the new forge yet; but the new forge has pretty much only changed fluid registry which shouldn't effect this mod at all.

**Comment by FiveEYZ** [comment]
just wanted to add that if u have cauldron 1.1307.06.218 then its forge 1307

**Comment by yepidoodles** [comment]
Thanks lol, not that It makes all that much difference xD

**Comment by evernife** [comment]
LOL, when i said
"Here, take one of this cauldron versions and test (make a backup before please)"

i send this link:

http://tcpr.ca/cauldron

bug-life :dash:

**Comment by evernife** [comment]
yepidoodles, what "essentials" version do you use?

**Comment by yepidoodles** [comment]
2.13.1 I think 

Haven't had time to make a test run yet

**Comment by AfterWind** [comment]
@yepidoodles the issue with /town perm set restrictedtownperms true is that restrictredtownperms needs to be spelt like this: restrictredTownPerms.

**Comment by yepidoodles** [comment]
Thanks, I thought I'd tried the caps, but obviously did something wrong... Or it was having a broken day  ^.^ 

Really need to find a way to make caps not count, they make using the mod really annoying.

**Comment by AfterWind** [comment]
I agree, that's another thing I need to do.

**Comment by AfterWind** [comment]
I think everything that was discussed in this issue was fixed.

Making a plot is now much more simple:
`/t plot new <plotName>`
This gets you the selector tool as normal. Right-clicking the two corners will now automatically create the plot for you, without the need of executing a whole bunch of commands. And shift right-clicking it will change it so that the plot selected will be from top to bottom of the world.

There is now a message of when you enter a plot and when you enter an unassigned plot.

Flags are no longer case sensitive and they are now only one word for easier usage.

The bug with borders should be fixed, but haven't tested it yet since I don't have 2 accounts right now :P

**Comment by yepidoodles** [comment]
That is brilliant, thank you :)
