### ISSUE TITLE
[Suggestions] Plot types, Mod Support & other little things

### ISSUE THREAD

**Issue by Flenix** [MyEssentials/MyTown2#20]
Plot types (Could also be flags)
- PvP-enabled plots for non-PvP towns (Or PvP-free plots for PvP towns)
- Interaction plots for non-interaction towns (So people not in the town can interact with certain things)
- Mob Spawn plots

Mod Support:
MCHeli. Not sure how easy/possible due to it being a Japanese mod, it's also double obfuscated so BON won't show anything useful. It'd be nice to state things like only town people can break a vehicle but anyone can get into a vehicle. A good fallback could be to check any "unknown entity" (IE not Steves carts, Railcraft, Traincraft etc)

Other little things:
- Config:
I'd like to see the ability to set forced perms in a config, before a server even starts, It seems a bit more stable, as in MT1 I've had issues with each player having to disable mob spawning even though I'd set it as a global perm already.

- Towns:
It'd be cool if towns could change certain messages, for example when entering/leaving a town. A town board shown to players on login (like Towny has) would be cool too.

- Economy:
Like I said in IRC I plan to fork in support for FlenixCities econ, but it might be best for you to decide what you'd want from it first. FlenixCities will allow the ability for mods to make a new bank account, so you could make an account for each town called mytown_TownName. Mayors (and maybe assistants) could interact with that using /town deposit and /town withdraw, It'd all be very easily handled with my API.
As for the econ functions, these would work with any econ system (including an item-based one)
- Town cost
- Claim cost
- Far claim cost (for claims not connected to town you could charge more, like Towny's outpost)
- Town spawn cost
- Town spawn other cost (if another town allows it- this could be a flag!)

The mayor could somehow define a chest as well, which is locked to only him and unbreakable. That would open up:
- Player plot-buying (with whatever cost taken from the player and put in that town chest)

And finally, with a proper econ (such as mine or one from Bukkit)
- Player taxes (per plot-type?)
- Town upkeep costs

One last idea; a client add-on mod.
You could use packets to send info to a client, and therefore reduce chat spam. If you wanted to be really clever you could integrate with a minimap mod for the town map, and you could also display info on-screen, such as the town you're currently in and various mayor statistics. I'd be more than happy to help with this or even handle most of the client-end stuff for you if you want, it'd be pretty easy to do based off my HUDWidgets mod.

Sorry for the ramble, I get a bit lost in ideas. I've wanted a Towny remake for Forge since I first moved over to it, and this has potential to be so much better than the original Towny!

**Comment by AfterWind** [comment]
I will close this and add the missing stuff that hasn't been yet implemented to my own TODO list.
Missing stuff being: changing welcome message, buying plots, taxes for players and upkeep and far claims.
We are already using FE's economy system, we will add more in the future.
