### ISSUE TITLE
"/t new" (problems)

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#201]
This is not a current bug, but, i decided to report:

Sometimes when you use the command /t new (TOWN) you get your "CostItem" spend (in my case, an "Ancient Coin") and your town don't appear.

No errors, nothing that can be visible.
(BUT.... i have the thought that the TOWN appears in another place.... i will try to take a better look, but this is a real bug... boring too )

**Comment by AfterWind** [comment]
I think by "boring" you meant to say "annoying" instead :)

**Comment by evernife** [comment]
Sorry, I am Brazilian, both words have similar meanings

**Comment by ThuGie** [comment]
Actually i have had this problem as well!
I made a town using /ta new spawn, and it appeared a few chunks away.
I noticed this because i showed the borders removing the town and adding it again did not solve it.

I moved a few chunks and it worked there. quite odd but not yet fixed btw.

**Comment by oryfoxer7410** [comment]
Same. Player on my server had made a town, but it wasn't claimed were he was. It apparently claimed a section far away. We just deleted and recreated.

**Comment by Biofusionz** [comment]
This is a really persistent bug on my server. Its starting to be a bit of a hassle having to force claim a chunk each time someone decides to make a town

**Comment by evernife** [comment]
So i say :D

**Comment by groveham** [comment]
Just experienced this as well. Other people on the server are OK, one player created a town, the town shows in the list of towns but the protection isn't there. The area is still stated as 'Wild' and when trying to claim a chunk next to the founding chunk he gets a message regarding 'You cannot have any more far chunks!'.
We figured out that the town was founded over 1700 blocks away which is the players last death point if that helps. 
I asked him to delete the town, then re-log and re-create the town. He logged off the server, then back on (didn't restart his client) and then the town was founded in the correct place. 

Hope that helps narrow down the issue!

**Comment by AfterWind** [comment]
@groveham The fact that it created on his last death point is really important information. I will look more into it, but I think I now have a grasp of why this happens, expect this to be fixed tomorrow.

**Comment by FiveEYZ** [comment]
Dont know if duplicate, but im running latest build of both mytown2 and core on cauldron 1420

the player get a error when making a town and the chunk he is standing in turns into a "admin town" with the "town name" he used in the command.
here is the console error: http://pastebin.com/LzGyQja6

**Comment by AfterWind** [comment]
Yeah, I still haven't fixed it yet. Sorry had to finish all the other refactorings I started xD
Next build will have that fix.
