### ISSUE TITLE
Galacticraft Dimension claims bugged

### ISSUE THREAD

**Issue by PlanetBeast** [MyEssentials/MyTown2#205]
There is currently an issue with MyTown in where if you try to claim a chunk on a GC Planet instead of claiming the chunk there in that dimension it claims the chunk where that chunk is in the overworld. I don't know if this is a bug anyone else is experiencing as I hadn't seen an issue report about it closed or open (unless I missed it). The server is a cauldron run server so I don't know if that plays a role in it. If you need anymore information let me know! Thank you!!

**Comment by evernife** [comment]
Already reported, but, as you are saying, seems a bit different.
#192

**Comment by PlanetBeast** [comment]
Yeah, saw that one but didn't think it related to what I was experiencing, but what do I know :P

**Comment by AfterWind** [comment]
I can't seem to reproduce this, unless galacticraft is actually assigning dimension ids in a different way, everything should work properly.

**Comment by PlanetBeast** [comment]
Tried reproducing it again, no luck. I guess its fixed? I don't know what happened that one time :P
