### ISSUE TITLE
MyTown2 addon Grief Prevention

### ISSUE THREAD

**Issue by evernife** [MyEssentials/MyTown2#206]
Is there a way to make the protection of MyTown2 an AddOn of GriefPrevention.
(Just asking, this came to my mind...)

**Comment by AfterWind** [comment]
No. For a few reasons:
1) MyTown2 is based solely on Forge and GriefPrevention is based on Bukkit, while a "link" between them is possible it will hit the performance greatly.
2) Bukkit is no longer supported thus we'll not write software for it unless it's a small change that influences in a positive way the community.
3) MyTown2 is very much different than GriefPrevention.
