### ISSUE TITLE
/t borders show

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#207]
doing this command makes the server to timed out

the last thing in the logs is:

[00:25:01] [Server thread/INFO]: wolfman696 issued server command: /t borders show

happend with cauldron 1388 and 1408

**Comment by AfterWind** [comment]
No logs, no nothing?

**Comment by FiveEYZ** [comment]
that's the weird part! 
Nothing shows in the logs, except that someone used this command and server times out and people can reconnect.

**Comment by AfterWind** [comment]
Have you tried with Forge only? Could also be a problem with Cauldron itself.

**Comment by FiveEYZ** [comment]
i have not tried that and it wont be possible for me to test with "forge only"

**Comment by AfterWind** [comment]
Fixed.
