### ISSUE TITLE
Creeper spawn issue

### ISSUE THREAD

**Issue by yepidoodles** [MyEssentials/MyTown2#208]
Since we added MyTown creepers have not been able to spawn, even with spawn eggs. I didn't report it before because I didn't know which plugin was causing it, turns out that it is the Minecraft protection file; creeper explosion prevention section which was preventing them, we just deleted that part to see if it would work (as we have explosions off via essentials anyway), so not a big deal for us, but It most likely would be for others.

- Alice

**Comment by AfterWind** [comment]
If I am not mistaken the explosions themselves are also handled on our side as well. So removing the creeper from the exposive entities list shouldn't have much of an impact.

**Comment by yepidoodles** [comment]
Yeah, I'm just concerned about others having this issue, if anyone else could test spawning a creeper with a spawn egg without removing the section, I'd be grateful.

**Comment by krwminer** [comment]
Do you have explosions disabled for the wild? If you do, all you should have to do is allow explosions for creepers to spawn.

Removing creeper explosions from Vanilla will work as long as the Forge is 1254 or higher which has the explosion protection event.

**Comment by yepidoodles** [comment]
But it should just stop explosions, not creeper spawning, that's just weird, you shouldn't have to allow explosions just to get creepers

**Comment by AfterWind** [comment]
I agree. It's somewhat of a bug with the protection file and the system. There needs to be put a condition on creeper protection to check if the fuse has been lit but we don't have entity checks yet.

**Comment by krwminer** [comment]
This is fixed in the latest version of development branch protections.

**Comment by yepidoodles** [comment]
Thank you very much :)
