### ISSUE TITLE
"That the selection is not in a plot in town name" when selling plots

### ISSUE THREAD

**Issue by karl2002** [MyEssentials/MyTown2#209]
Having this issue where i am unable to to sell plots or even add people to them as it acts like the plot dosn't exist yet when i do show plot borders i see all the plots i created. Yet i can't do anything with them.

**Comment by AfterWind** [comment]
Please check again if you have created the plot properly.
* /t plot select
* right click the two corners
* /t plot make <name>
And try again.

**Comment by AfterWind** [comment]
No response :/
