### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#211]
getting this startup crash: http://pastebin.com/D0D1iFz6

using:
MyTown2-1.7.10-154-dev
MyEssentials-Core-1.7.10-1.5r17-universal

running on:
Cauldron-1.7.10-1420

modpack:
FTB Infinity 1.6.2

**Comment by AfterWind** [comment]
You're using outdated version of MyEssentials-Core. Try building it from the repo, that should solve this issue.

**Comment by FiveEYZ** [comment]
i assumed it was the latest cause it was built on jenkins at the same time the repo was updated

**Comment by AfterWind** [comment]
MyEssentials-Core{2.0} [MyEssentials-Core] (MyEssentials-Core-1.7.10-1.5r7-universal.jar
You are using r7 not r17, that's why
