### ISSUE TITLE
[MyTown2-1.7.10-0.0.2b] mytown.util.Formatter.formatResidentsToString(Formatter.java:80) CRASH

### ISSUE THREAD

**Issue by brunyman** [MyEssentials/MyTown2#212]
Hi, we use this plugin with FTB Direwolf20 modpack and KCauldron-1.7.10-1408.95.

Lately we started to get a lot this crash:

http://pastebin.com/BQqc1Yxn

**Comment by AfterWind** [comment]
When does this happen?

**Comment by brunyman** [comment]
i think when a player was entering a town with enter flag set to false, but not always

**Comment by AfterWind** [comment]
This should no longer happen.
