### ISSUE TITLE
/t perm set mob hostiles dont work

### ISSUE THREAD

**Issue by blasterdude9** [MyEssentials/MyTown2#214]
/t perm set mobs hostiles dont work saids invalid value

**Comment by FiveEYZ** [comment]
passives instead of hostiles now

**Comment by AfterWind** [comment]
Basically the mobs flag is not inverted. It tells what type of mob to allow to exist in the town:
* none: anything that is a living entity will get deleted in town
* passives: anything that is not passive (zombie, creeper etc.) will get deleted.
* all: doesn't delete anything.
