### ISSUE TITLE
/t plot add member wont keep the member in the list

### ISSUE THREAD

**Issue by blasterdude9** [MyEssentials/MyTown2#217]
/t plot add member wont keep the member in the list u have to delete the plot and readd them

**Comment by blasterdude9** [comment]
found that out today when im trying to add a member to the claim it would keep it till the server restarted then they are not in the list

**Comment by AfterWind** [comment]
Any error that appeared after adding the member to the plot?

**Comment by blasterdude9** [comment]
idk u have to a fiveeyz

**Comment by blasterdude9** [comment]
this issue was fixed

**Comment by Red3Tango** [comment]
I don't know how this issue was fixed. With running 0.1.1b this issue still exists on my server.
After server restarts, they are no longer shown with /t plot info, they do not have access to the plot, though they are in the database as a member.

**Comment by FiveEYZ** [comment]
http://pastebin.com/0NR6Ugdh

i checked the plot before he did the command, the player was not listed in the plot and he wasn't able to access the plot
