### ISSUE TITLE
Problems with /ta config reload

### ISSUE THREAD

**Issue by Flenix** [MyEssentials/MyTown2#218]
When changing the flag settings, existing towns are not forced to that state. For example, if you change the flags so PvP is true, and towns cannot change that, any town with PvP as false will remain false.
No one can then set the PvP flag in that town to true, even using the /ta command.

**Comment by Flenix** [comment]
Update on this; it's actually the /ta config reload command that's broken. A server restart forces the flags to the correct settings.

**Comment by krwminer** [comment]
There is also an issue with /ta config reload with the Wild permissions. It keeps adding to Wild.instance.flagList in the update() method. It does not replace flags or clear flagList before adding the flags.

**Comment by krwminer** [comment]
Flenix,

I need you to be more specific about the problem:

+ What state was everything in to start
+ What did you change, (file, /t perm set, etc.)
+ What did you expect to happen
+ What did happen

Thanks.

**Comment by Flenix** [comment]
To start with, flags were as default (I'd upgraded from a version without flags I believe - console took a few minutes to process flags for all the towns)

I changed a number of flags, all using /ta (never as a specific town), trying to disable and force settings for towns. One example could be changing accessBlocks in towns to true, and disabling the configurability of it (done in the config file itself)

Upon /ta admin reload, flags weren't forced to the new settings. However, towns could no longer change it either; meaning it was effectively forced to false.

**Comment by AfterWind** [comment]
This should be fixed.
