### ISSUE TITLE
/t leave delete

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#221]
"/t leave delete" gives error
here is the error from log: http://pastebin.com/L7xpLiqR

**Comment by FiveEYZ** [comment]
doing this command as the only resident and mayor in town it tells me:
"Before you leave you need to choose between deleting the town or passing mayorship to other resident: /t pass <resident> or /t leave delete"

no error in logs.

**Comment by AfterWind** [comment]
Aaaand the award for the best derp of 2015 goes toooo issue #221.
Should be fixed now.
