### ISSUE TITLE
Errors on loading protection.

### ISSUE THREAD

**Issue by Xen1290** [MyEssentials/MyTown2#222]
Hi @AfterWind @krwminer ,
https://gist.github.com/Xen1290/d238e99d8b3ba27d5916
This with latest version on jenkins (MyTown and MyEssentialsCore)
I used only json files from here
https://github.com/MyEssentials/MyTown2-Protections

**Comment by FiveEYZ** [comment]
yea, the protection files need to be updated for the new flags that got changed in the last couple of builds.
