### ISSUE TITLE
Right click event crash

### ISSUE THREAD

**Issue by ProfX66** [MyEssentials/MyTown2#223]
I have a server with MyTown2 and it seems to work properly, until I add MyTown2 to my client. Once I add it to the client any triggering of a right click event crashes the client completely (crash report: http://pastebin.com/TZWRdCaj). It should be noted that the server does not throw any error at all.

Versions:
* MyTown 2:1.7.10-0.0.2b
* MyTown|API:1.0
* MyEssentials-Core:2.0

I've had this happen both on my custom pack and an Agrarian Skies 2 server/client.

**Comment by bbz404** [comment]
Its not a client side mod. Only server. remove it from your client.

**Comment by ProfX66** [comment]
So originally I had it like that but people were not able to unclaim chunks, there was no errors printed at that time though. Once people added the mod to the client they were able to unclaim chunks but could not right click. Not a huge deal I guess but thanks.

**Comment by bbz404** [comment]
What happens when they attempt to unclaim? Any Message on console when attempted or ingame?

**Comment by ProfX66** [comment]
They would receive the message "This block is not claimed by town mytown.entities.Town@5917d559" but they would get the entrance and exit message in that same chunk.

**Comment by bbz404** [comment]
Ok. I would suggest close this issue and create new one in relation to the unclaiming issue.

**Comment by ProfX66** [comment]
Will do, thanks.
