### ISSUE TITLE
Unable to unclaim blocks

### ISSUE THREAD

**Issue by ProfX66** [MyEssentials/MyTown2#224]
On my server, users are unable to unclaim blocks/chunks they have previously claimed.

When attempting to unclaim they receive the following message:
* This block is not claimed by town mytown.entities.Town@5917d559

I suggested that they try adding the mod to their client and doing so allowed them to remove the block. Since this is a server side mod, this seems like odd behavior.

Also there was no errors in the console for this, just that message.

The blocks do give the entrance and exit message, which is what tells us they had it claimed.

Versions:
* MyTown 2:1.7.10-0.0.2b
* MyTown|API:1.0
* MyEssentials-Core:2.0

**Comment by FiveEYZ** [comment]
using lastest build 161
when someone do "/t unclaim" this happens: http://pastebin.com/wMRfZU7a
same when someone did "/t borders show" http://pastebin.com/7xQcKgCW

seems to be alot of logging messages

**Comment by AfterWind** [comment]
@FiveEYZ that's just debug messages that I am using to fix one of the issues. Actually, you can test that for me, try making a plot inside another plot and see if the redstone markers go away or not.

@ProfX66 I always love it when people put some effort into formatting their text. I will look into the issue.

**Comment by FiveEYZ** [comment]
here u go: http://pastebin.com/6AFVgXag

when i selected the second corner of the plot i said "New plot created" and the selection i made turns in to this http://gyazo.com/d3ebd4a807879718d150594a9a2f7b62
i guess thats the error that shows in the paste

**Comment by AfterWind** [comment]
Oh, nice! Thanks for the report, really helps fix the issue I mentioned.

**Comment by FiveEYZ** [comment]
the selection from the first plot didnt disappear and the same goes for the second plot inside the first one

but will tell u "Selection is inside plot test2"

**Comment by ProfX66** [comment]
When testing build *#163* for this issue, my server would crash on startup. Created issue **#232** for that specific error as it does not seem related to this one.
