### ISSUE TITLE
/t perm set mobs passives dont work now

### ISSUE THREAD

**Issue by blasterdude9** [MyEssentials/MyTown2#225]
/t perm set mobs passives dont work now

**Comment by AfterWind** [comment]
What exactly does not work?

**Comment by blasterdude9** [comment]
when u set it to passive all mobs hostiles spawn as well

**Comment by AfterWind** [comment]
I will look into it.

**Comment by AfterWind** [comment]
This is caused by the protection files. Try and modify the Minecraft.json so that in the denialValue field it says passives instead of hostiles and try spawning a vanilla mob in a town with mobs flag set to passives.

**Comment by krwminer** [comment]
Please use the protection file in the development branch for the latest builds, they are all up to date.
