### ISSUE TITLE
plots dont work at all u cant make them and when u do it dont show them 

### ISSUE THREAD

**Issue by blasterdude9** [MyEssentials/MyTown2#228]
when u make the plot it crashes the server and wont show what u did

**Comment by AfterWind** [comment]
Here's a tip, every time you say "crash" in an issue remind yourself that you need a crash report as well :)

**Comment by FiveEYZ** [comment]
making a plot works, he didnt know it was changed.

but as u can see here when i played around with the plots for a couple of mins http://paste.ubuntu.com/11724761/

it generated alot of lines in the console, after 30 mins server uptime the log file is at 2.2 mb

**Comment by AfterWind** [comment]
The risk of using a dev build :P.
I will remove them as soon as I fixed the issue.

**Comment by blasterdude9** [comment]
im going to put it on my in house network server and see what crashes i get and what works and what dont
