### ISSUE TITLE
Errors on loading protection

### ISSUE THREAD

**Issue by Xen1290** [MyEssentials/MyTown2#229]
Hi @AfterWind @krwminer ,
https://gist.github.com/Xen1290/ae3cfd82553d1bd2a176
This with latest version on jenkins (MyTown(161) and MyEssentialsCore)
I used only json files from here
https://github.com/MyEssentials/MyTown2-Protections
I think json files  or MyTown need an entire check?

**Comment by AfterWind** [comment]
Move this to the MyTown2-Protections repository please.
