### ISSUE TITLE
[Request] cost behavior with "/t spawn"

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#230]
at the moment if u add a cost to use "/t spawn" it will cost to use it to ur own town.
is it possible to make it only cost to use when going to another town?

so if it possible for it to only charge money for "/t spawn (townName)"  but not "/t spawn"

**Comment by AfterWind** [comment]
It already is possible to do this. Look into the config for costAmountSpawn and costAmountOtherSpawn
Although I might wanna polish a little it should work how you want it.
