### ISSUE TITLE
Client update on protection hit

### ISSUE THREAD

**Issue by krwminer** [MyEssentials/MyTown2#231]
The protection system needs some way to define areas on the client that need an update block message sent to for a protection hit so it can sync the client back to the server. 

It might be good if this was optional so the update packets are only sent when needed.

We currently have a temp fix for doors, but this needs to be expanded.

**Comment by AfterWind** [comment]
It wouldn't be too hard to make that an option, but the issue is that even the door needs some extra code: I need to send packets on both of the blocks for it to update on the client side.

**Comment by krwminer** [comment]
I am asking for an optional area defined where it will send update packets back for every block in that area. Then you can properly control when and where to update from the protect itself. That would make your code generic.

**Comment by AfterWind** [comment]
Okay, we need to come up with a way to specify the area in the json files.

**Comment by krwminer** [comment]
Have it be optional like owner. Call it say "update".
Specify a relative Min and Max, X, Y, Z. So say xMin, xMax, yMin, yMax, zMin, zMax.

**Comment by AfterWind** [comment]
But then only cubical shaped are allowed. Like, say, we have a multiblock structure that is in a cross pattern and we need to update that, can't we also have it be able to specify that as well.
Another issue is that then we need a "center" block, that would make checking for it a real hassle.

**Comment by krwminer** [comment]
So far, the only cases that I know of that need this are 3D box shapes that this would cover.
Also the only thing I know of that needs this is an item RIGHT_CLICK_BLOCK or a RIGHT_CLICK on a block.

**Comment by AfterWind** [comment]
Implemented.
