### ISSUE TITLE
NoClassDefFoundError for Lmytown/core/logger/Log with build #163

### ISSUE THREAD

**Issue by ProfX66** [MyEssentials/MyTown2#232]
While testing build *#163* for issue **#224** my server just crashes during startup.

The following crash report shows a *NoClassDefFoundError* for *Lmytown/core/logger/Log*
* http://pastebin.com/04cqzufU

Should also be noted that it seemed to corrupt my data.db, when reverting to build *#145* it would also crash with the following crash report
* http://pastebin.com/pXAwUqLF

I suspect its the database but I renamed my whole MyTown folder and let it recreate, afterwards it loaded up with out any errors.

I did try loading build *#163* with the config folder renamed but it still crashed with the first error.

**Comment by krwminer** [comment]
You need to use a matching pair of MyEssentials-Core and  MyTown2. You used the latest MyTown2 and Beta MyEssentials-Core :

MyEssentials-Core{2.0} [MyEssentials-Core] (MyEssentials-Core-1.7.10-1.6r-universal.jar) 
MyTown2{1.7.10-0000r} [MyTown 2] (MyTown2-1.7.10-163-dev.jar)

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2212817-mytown-2-0-0-2b-finally-in-beta-vault-and?comment=292

**Comment by ProfX66** [comment]
I am using *"MyEssentials-Core-1.7.10-1.6r-universal.jar"* as you linked.

I am not, however, using the latest successful build https://ci.mineguild.net/job/MyEssentials-Core/lastSuccessfulBuild/

Per my log it states a version of *MyEssentials-Core:2.0*

**Comment by krwminer** [comment]
I think the build numbering is a bit messed up for Core. I think Beta was tagged as 1.6r and the latest builds are 1.5r. Please match the latest of both MyTown2 and Core using the links I provided in the forums post.

**Comment by ProfX66** [comment]
Will run that test later today.

**Comment by AfterWind** [comment]
Closing, simply an issue with not using the proper version of MEC. Get it from here: https://ci.mineguild.net/job/MyEssentials-Core/
I know it says 1.5r but it's actually 1.6r but somehow the update didn't get through :/
