### ISSUE TITLE
Error message does not go to the players themselves and it clogs down to the console.

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#233]
someone was trying to run this command and it gave an error: http://pastebin.com/FYdcS8gN

**Comment by krwminer** [comment]
Did he get the following message?

"You are not allowed to teleport to the location of DragonKnights's spawn"

Did he have ENTER permission for DragonKnights's town?

**Comment by FiveEYZ** [comment]
will check

**Comment by FiveEYZ** [comment]
tried to do the command myself and "An unkown error occured..." and the same error thats in the paste.

i did not see: "You are not allowed to teleport to the location of DragonKnights's spawn"

**Comment by AfterWind** [comment]
§cYou are not allowed to teleport to the location of DragonKnights's spawn

**Comment by krwminer** [comment]
This did not get closed because you mentioned it in the MEC change. I assume it is closed now?

**Comment by AfterWind** [comment]
Oh, yes, it should be fixed, I always forget those type of things :P
