### ISSUE TITLE
/t new <name>

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#234]
user getting error trying to make a new town http://pastebin.com/Nmj6SSr3

**Comment by AfterWind** [comment]
It seems like the town with name "Eden" already exists in the database. Try doing /t list and see if that is true.

**Comment by AfterWind** [comment]
Duplicate of #233. Closing.

**Comment by FiveEYZ** [comment]
yes that town name Eden already existed, thanks for awesome support! :D
