### ISSUE TITLE
[Request] a way for admins to check/edit friends

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#235]
One incident that happened on the server:
A resident had a disagreement with his town major and got kicked out of the town, but was still a friend with another resident in the town (he refused to tell who) so he was still able to enter the town and take stuff.

All drama could have been avoided if there was a admin command to check/edit friends of another player.

or make it so friends of a resident cant bypass the townflags.

for example you can add it as a value to a flag like the mobs flag: access[none, friends, all]

**Comment by AfterWind** [comment]
I am thinking of removing the friends list altogether and implement a whitelist for each town that tells which player can bypass protections.

Another way to implement this is to have only the mayor granting protection bypasses when he is in a player's friends list.

Your idea is not bad but it only works if you trust ALL friends of all the residents, which is close to impossible.

Which do you think is better? Should I keep the friends list for later usage? Any other suggestions?

**Comment by Preadd** [comment]
What about only granting friends access to plots?
So if I'm e.g. an assistant then my friends still only have access to my specific plots and they dont get my assistant rights too.
If friends need more right, they need to be invited to the town and get the right from the mayor.

But I agree with FiveEYZ that admins should be able to see peoples friends list.
That way it gets easier to solve matters of griefing etc.

**Comment by AfterWind** [comment]
You can already add anyone as a member to the plot whether or not is a resident of the town. The issue with that right now is that any resident can make a plot in any corner of the town, so I'll have to implement the permission system for that stuff as well.

The admin manipulation of friends list will be implemented as it is a good idea.

**Comment by Preadd** [comment]
Sounds really good.
My main concern though was that a friend get same rights (or close) which is mostly unwanted. My plot limitation was just a try to find something more suitable namely the plot assigned specifically to you and not the whole town where you could be mayor, assistant.
Well I guess you get my point. :)

For me the friends list is not important to keep, if I can just add a friend to my plot.

**Comment by AfterWind** [comment]
Okay, I may even remove the whole friends idea and just work with that. Will also modify the plot's info formatter so that you know which of the members are in the town and which aren't.

**Comment by AfterWind** [comment]
Friends are currently not used in any kind of permission, so admin management of that would be useless. You can even look in the DB if you want to know who's friends with who.
I will close this. Reopen if there's a reason for those admin commands.

**Comment by FiveEYZ** [comment]
Friends did exist when i made the "Request"
All player info in the DB is stored in UUID and are kinda tedious to lookup, while a /ta command would give the actual username.

But since friends have been removed i guess there is no reason for this Request.
