### ISSUE TITLE
Crash with mytown

### ISSUE THREAD

**Issue by Xen1290** [MyEssentials/MyTown2#236]
@AfterWind @krwminer 
When I try to setup nuke near a town, server crash with that:
https://gist.github.com/Xen1290/97b5d593e7d4bb80fa84
 - industrialcraft-2-2.2.736-experimental

And server costantly crashing on startup with same error.

**Comment by AfterWind** [comment]
This is an issue with the protection files themselves, close this and move it to the protections issues tracker here: https://github.com/MyEssentials/MyTown2-Protections/issues

**Comment by Xen1290** [comment]
Moved. Sorry. https://github.com/MyEssentials/MyTown2-Protections/issues/86
