### ISSUE TITLE
[Request] New Rank Permissions: 'mytown.cmd.bypass.xxxxx'

### ISSUE THREAD

**Issue by djrecipe** [MyEssentials/MyTown2#237]
MyTown 2 seems promising, but there is one huge flaw that I am not certain how to get around.

I want to utilize MyTown2's town permission architecture. Currently, I do not care about or want plots. I am simply want an area with restricted permissions unless your username is white-listed.

I currently have 'restrictedTownPerms' set to 'True' but I have no plots defined. As such, it is impossible for anyone except the OWNER of the town (aka the one who founded it) to bypass the town restrictions. I've tried adding two Mayors, etc. The end result is always the same: with 'restrictedTownPerms=false' EVERYONE has FULL access to the area, with 'restrictedTownPerms=true' EVERYONE except the original founder has all of the "outsider" restrictions placed on them - even "Resident"s and "Assistant"s.

If I were able to add permission to the "Assistant" rank, for example, something like "mytown.cmd.bypass.accessBlocks" or "mytown.cmd.bypass.enter", then I could use the ranking system to allow different tiers of privilege for different people, without having to deal with the tedious plot-making process that is counter-intuitive to what I am trying to accomplish.

**Comment by djrecipe** [comment]
After looking through your code a bit, I noticed that the parenthesis orientation was different between these two methods:
```
    public boolean checkPermission(Resident res, FlagType flagType, Object denialValue, int dim, int x, int y, int z) {
        Plot plot = getPlotAtCoords(dim, x, y, z);

        if (plot == null || flagType.isTownOnly()) {
            if(getValue(flagType).equals(denialValue) && !hasResident(res) && (!residentHasFriendInTown(res) || ((Boolean) getValue(FlagType.RESTRICTIONS) && !(getMayor() == res)))) {
                return PlayerUtils.isOp(res.getPlayer());
            }
        } else {
            if (plot.getValue(flagType).equals(denialValue) && !plot.hasResident(res) && !plot.residentHasFriendInPlot(res))
                return PlayerUtils.isOp(res.getPlayer());
        }
        return true;
    }
```

```
    public boolean checkPermission(Resident res, FlagType flagType, Object denialValue) {
        if (getValue(flagType).equals(denialValue) && (!hasResident(res) && !residentHasFriendInTown(res) || ((Boolean)getValue(FlagType.RESTRICTIONS) && !(getMayor() == res)))) {
            return PlayerUtils.isOp(res.getPlayer());
        }
        return true;
    }
```

----------------------------

specifically look at

```
            if(getValue(flagType).equals(denialValue) && !hasResident(res) && (!residentHasFriendInTown(res) || ((Boolean) getValue(FlagType.RESTRICTIONS) && !(getMayor() == res)))) {
                return PlayerUtils.isOp(res.getPlayer());
```
vs.
```
        if (getValue(flagType).equals(denialValue) && (!hasResident(res) && !residentHasFriendInTown(res) || ((Boolean)getValue(FlagType.RESTRICTIONS) && !(getMayor() == res)))) {
            return PlayerUtils.isOp(res.getPlayer());
```

----------------------------

Here is the first method [Town.CheckPermission(Resident,FlagType,Object,int,int,int,int] with the applicable values filled out (a non-op resident is present in a restricted town with no plots):

```
if(TRUE && FALSE && (FALSE || (TRUE && TRUE)))
	return FALSE;
else
        return TRUE;
```

Here is the second method [Town.CheckPermission(Resident,FlagType,Object] with the applicable values filled out (a non-op resident is present in a restricted town with no plots):

```
if (TRUE && (FALSE && TRUE || (TRUE && TRUE)))
	return FALSE;
else
        return TRUE
```

Because of order of operations (&& is resolved before ||), method #2 will ALWAYS deny permission provided that a) town is in restricted mode AND b) player is not the original mayor AND c) player is not an op. So in the end, if Method #2 was made to match Method #1 then a resident of a non-plotted, restricted town would be able to bypass the town restrictions (which is what I desired).

**Comment by AfterWind** [comment]
The restrictedTownPerms flag is supposed to work together with the plots. We are planning on adding a way to specify the flag bypasses directly in the config file on a per-rank basis and eventually make it compatible with other permission system out there like ForgeEssentials.

The issue with those two methods is a mistake of mine and will be fixed.

**Comment by djrecipe** [comment]
Okay thank you for the timely response! I hope you opt for the solution that allows me to use MyTown2 without plots. If this does not currently fit within your design parameters at the moment then I understand.

**Comment by AfterWind** [comment]
Fixed the methods. I'll have to discuss with the rest of the team about the permission strings but it might take quite a while till' we get it implemented.

**Comment by AfterWind** [comment]
Implemented
