### ISSUE TITLE
missing protections (for mods)

### ISSUE THREAD

**Issue by jogi01** [MyEssentials/MyTown2#239]
hey guys!

i have parsed myself through all mods and protections and have these issues which i cant solve myself:

mod: chisel
you can leftclick with a chisel on the floor and change any chiselable blocks.

mod: Gregtech & greg's stargate craft
need normal protection (machines rightclick)

mod: Hardcore Ender Expansion
protection warning comes up but GUI from the machines, too.

mod: wr-cbe logic (from codechicken wireless transmitter&receiver)
need normal protection (rightlick gui)

as i said i have tried myself, on other mods it works fine but these are my last hurdles :) 

who can help here :)
-jogi

**Comment by FiveEYZ** [comment]
u should move the issue here: https://github.com/MyEssentials/MyTown2-Protections/issues

**Comment by AfterWind** [comment]
As FiveEYZ said, everything related to protections goes to that repo. Please close this issue and open it there, I want them separated for better management.
