### ISSUE TITLE
/t plot new

### ISSUE THREAD

**Issue by blasterdude9** [MyEssentials/MyTown2#240]
the /t plot new then the name does now work now it does can not create plot outside of town when the town plot is claimed the selector part of this command is broken.

**Comment by FiveEYZ** [comment]
making new plot works for me, u sure u doing it right?

**Comment by AfterWind** [comment]
Umm... what?
Plots should only be created inside a town.

**Comment by blasterdude9** [comment]
i messed up on it i had it in the wrong town when i was trying to create the plot
