### ISSUE TITLE
[Request/ Suggestion] Gravestones

### ISSUE THREAD

**Issue by yepidoodles** [MyEssentials/MyTown2#241]
In the mod OpenBlocks there are player graves of which the player must break in order to get their stuff back, there are also similar gravestone mods out there which do this. If possible, it would be great to exclude these blocks from the MyTown2 protection so that if a player dies in someone else's town they can still retrieve their items. This isn't really a necessary add, but would be a nice/ useful feature to have. 

Thanks 

- Alice

**Comment by AfterWind** [comment]
We actually got a similar request to this before.
We are surely gonna implement it but not in the next version unfortunately.

**Comment by yepidoodles** [comment]
Yeah, as I said it's not a necessity, but would be good to add eventually ^.^

Thanks

**Comment by damonmensch** [comment]
I have a suggestion, stead of just gravestones, how about a configurable whitelist for both items and block placements to ignore the protections. Then all the server admin has to do is add the aforementioned gravestone's id to the list and voila, it's there. Would make life easier down the road to make future mods compatible.

**Comment by FiveEYZ** [comment]
In my head OpenBlocks graves should be fairly easy to add to some kind of whitelist where only the owner of the block can break it anywhere, as the "player name" is stored inside it.
as can be seen here: https://gyazo.com/0b5da375e3936874ed0ac76b3a8ddf18
