### ISSUE TITLE
[0.1.0b] NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by brunyman** [MyEssentials/MyTown2#242]
We get this a lot, don't know what triggers. We run FTB Direwolf20 withn cauldron 1.7.10

http://pastebin.com/EJpAfQ3J

**Comment by FiveEYZ** [comment]
what version of forge do u have in that cauldron?

**Comment by brunyman** [comment]
KCauldron-1.7.10-1408.95-server

Forge Mod Loader version 7.10.114.1388 for Minecraft 1.7.10

**Comment by FiveEYZ** [comment]
try update to KCauldron-1.7.10-1420.120 or newer, i dont have this issue with FTB Infinity+KCauldron

**Comment by brunyman** [comment]
ok, thanks, i'l test that

**Comment by brunyman** [comment]
Ok, I updated to KCauldron-1.7.10-1420.120 , but i still get this crash a lot.

Looks like it triggers when a player joins. Here: http://pastebin.com/tmn0cYVD

Crash report: http://pastebin.com/dpkP3DVH

I'l check the player coordinates for coruption

**Comment by legobear154** [comment]
What appears to happen is the player that joins times out just before a chat message is sent, and because the player is no longer online, the message tries to send to the player and it breaks. Interesting that it happens though as I thought MT2 would be able to know the player logs out and the msg shouldn't send.

**Comment by brunyman** [comment]
indeed, must be something corrupted at players coordinates timing him out

**Comment by legobear154** [comment]
I can add a couple more checks and see if we can avoid the NPE.

**Comment by brunyman** [comment]
Great, thanks!
