### ISSUE TITLE
[0.1.0b] NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by brunyman** [MyEssentials/MyTown2#243]
We run FTB Direwolf20 withn cauldron 1.7.10. 

http://pastebin.com/1E6YMipc

**Comment by FiveEYZ** [comment]
Looks like a MFR Grinder having problems with a Creeper

will test this on my server

**Comment by FiveEYZ** [comment]
i do not get this crash :S

tested:
[x] unclaimed area
[x] claimed area
[x] grinder in a claimed area killing mobs in unclaimed area
[x] claimed the area where mobs were then changed flags
     "/t perm set mobs passives" and made a plot "/t plot perm set mobs all"

**Comment by legobear154** [comment]
This may be a similar problem as #242. Might be fixed in MyEssentials-Core master branch.
