### ISSUE TITLE
"Mining Turtles" turning in to normal Turtles

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#244]
Protection from turtles works, there is only 1 problem and that is when a lets say a "Mining turtle" gets to close to a town it will turn in to a normal "Turtle" with this message:

TileEntity dan200.computercraft.shared.turtle.blocks.TileTurtle@1079b8 was ATOMICALLY DISINTEGRATED!

protection against them works, but mt2 turns them to regular turtles.

**Comment by FiveEYZ** [comment]
Looking at the id's and the Mining Turtle have 1473:1 but turns to regular "Turtle" 1473
all other 28 special turtles like "Crafty Magnet turtle" have same id 1474 but when placed it turns into 
regular "Turtle" but with id 1474

**Comment by legobear154** [comment]
The problem seems to be that the item version of turtles hold some info as NBT data, which determines the turtle upgrades, fuel, etc and we don't copy that from the TE when its turned into an item.

So, we need to copy the right NBT data to the item, should be interesting!

**Comment by AfterWind** [comment]
I could implement something for the protection files that will let you tell what NBT data you need to copy from the TileEntity to the ItemStack. Although this will be in the future as I will first refactor the protection system.

**Comment by legobear154** [comment]
Thats what I was thinking we would have to do as well AfterWind.

**Comment by FiveEYZ** [comment]
I feel that making mt2 remember the "owner" of the turtle isn't so important at this moment, as long it drop as the same turtle that was placed then people will be happy with the current protection.

**Comment by AfterWind** [comment]
Basically done. All I am doing right now is copying the nbt from the TileEntity to the nbt of the ItemStack. Should work in most cases, but will have some stacking issues (this would be unavoidable even with the exclusion of some nbt tags).
