### ISSUE TITLE
Owner and Members can't modify plots

### ISSUE THREAD

**Issue by krwminer** [MyEssentials/MyTown2#247]
FlagType MODIFY is set to TOWN_ONLY which means it is not settable for Plots and permission is only checked on the Town level. But if the Town has RESTRICTIONS set to true, nobody but the Mayor can modify the Plot.

**Comment by AfterWind** [comment]
That is not/should not be true. Every player has rights in their own plots whether or not the RESTRICTIONS flag is true. Maybe there's a bug with the checkPermission method again?

**Comment by FloxRoxX** [comment]
I can confirm the problem, tested with the latest build from irc yesterday the Owner of the plot or the member of the plot cannot modify the land inside it with restriction flag true
