### ISSUE TITLE
Restricted flag not acting as it should.

### ISSUE THREAD

**Issue by yepidoodles** [MyEssentials/MyTown2#248]
Just updated my server's MyTown to the latest release version via Curse, I'm very pleased with it so far, however I am finding a few minor issues, I'll keep posting new issues as I find them.

First thing I noticed is that the new restricted perm (Which replaced restrictedTownPerms) doesn't appear to work, set to true or false, any resident within the town can access unassigned areas (which, for me, are mostly roads)

Also, I couldn't work out if there was any other flag for 'mobs' other than 'all' or 'none', as 'none' removes friendly mobs too; If there isn't a flag for it, adding one would be fantastic.

Thanks again for everything you've been doing, and I've noticed a few changes I could make to improve the lang file like I did before, so I'll do that at some point ^.^ (Thanks for adding that in, btw)

Much love, Alice

**Comment by AfterWind** [comment]
We've already tracked down the bug with the new restricted flag. I think it's already fixed but someone needs to test it.

Now we have a wiki page for flags: https://github.com/MyEssentials/MyTown2/wiki/Flags#mobs
I will be updating that every time I make modifications to that from now on.

**Comment by yepidoodles** [comment]
How would I go about testing it?

And thank you for the wiki ^.^

**Comment by AfterWind** [comment]
It's complicated at the moment as the Jenkins server is down and I am quite busy and can't allocate time for solving the issue. Just wait for a few days and hopefully other team member will release a new minor version.

**Comment by nylser** [comment]
Jenkins should be up. Atleast now

**Comment by AfterWind** [comment]
\o/

**Comment by yepidoodles** [comment]
Downloaded latest from Jenkins and tested, it's fixed :) 

Good job, thank you

**Comment by yepidoodles** [comment]
Okay new issue, with restrictions set to true, no one can place/ break blocks in their own plots

**Comment by krwminer** [comment]
Look down one. This is Issue #247 that I reported.
