### ISSUE TITLE
restrictions issue

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#249]
A player that is only part of 1 town and have the rank assistant, cant enter the town if "enter: false" and "restrictions:true" 

tested on build 185

**Comment by krwminer** [comment]
Does the latest build fix this?

**Comment by FiveEYZ** [comment]
will test it now

**Comment by krwminer** [comment]
Thanks. I just did a quick test, it seemed to work. If it looks good for you, you can close this.

**Comment by FiveEYZ** [comment]
yes it works but "restrictions" seems to affect all flags 

as an assistant i cant access anything in my town or modify blocks

i think this should only apply to residents
