### ISSUE TITLE
mytown.util.exceptions.GetterException: Failed to get a field in getter: fuse

### ISSUE THREAD

**Issue by ProfX66** [MyEssentials/MyTown2#250]
My server randomly crashed with: http://pastebin.com/raw.php?i=7Xa54YjE

I say randomly because we were not doing anything related to MyTown at all and all of a sudden the server dies with that crash report.

Looks like it has an issue with a creeper, every time the server starts (even before anyone connects) it crashes with that same error. 

I tried deleting the db file, but that did not work.

Renaming/Deleting the world does work.

I noticed that regular creepers are not a problem, but the following creepers throw the error as soon as they are spawned:
* Ars Magica mana creeper
* Galacticraft evolved creeper

Interestingly, the Thaumcraft tainted creepers do not throw this error.

Mod versions:
* MyTown2-1.7.10-188-dev
* MyEssentials-Core-1.7.10-1.5r30-universal

I am also using Cauldron, if that helps.

**Comment by AfterWind** [comment]
This issue is actually related to the code not the protection files. I will look into it.

**Comment by krwminer** [comment]
Until this is fixed, you can remove the following from the Minecraft.json so you can use your server:

      "condition": "fuse > 20",
      "fuse": [
        {
          "element": "field_70833_d",
          "type": "FIELD"
        }
      ],

**Comment by legobear154** [comment]
Just wanted to quickly add that looking through Ars Magica 2 source, they have a "timeSinceIgnited_Local" which appears to be used in place of timeSinceIgnited in their code. Also, they have lastActiveTime included directly in their class as well. I am not sure if either of those could cause a problem, but thought it would be worth noting. I haven't seen anything off with Galacticraft creepers implementation yet, but will continue looking!

**Comment by krwminer** [comment]
Fixed in latest Minecraft.json protect.
