### ISSUE TITLE
New plot with a name that already exists

### ISSUE THREAD

**Issue by yepidoodles** [MyEssentials/MyTown2#251]
When I go to make a plot, and try to give it the same name as another plot, I can not get rid of the selector tool so I can do the command again to call it another name.
Tried /town plot select reset
Tried dropping the tool 
Tried re-logging

Hope you can fix this issue,

Much love,
Alice

**Comment by AfterWind** [comment]
Dropping the tool and relogging will let you get another tool. I am not exactly sure how this should be implemented. Should it simply remove the tool if it fails to create the plot because the name already exists?

**Comment by yepidoodles** [comment]
Yes, removing the tool if it fails, and resetting the command in order to do it again with a new name.

**Comment by AfterWind** [comment]
Fixed.
