### ISSUE TITLE
Error with Mystcraft

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#252]
error when claiming in a Mystcraft dimension

http://pastebin.com/9EKKBySF

**Comment by FiveEYZ** [comment]
i see the issue now, its cause server only loads mystcraft dimensions "on demand" and there for wont be able to know the dimension exist.

**Comment by McyD** [comment]
There used to be no problems claiming chunks in Mystcraft dimensions with MyTown.  Really hoping this gets implemented soon otherwise I will have to rethink my use on MyTown.  What good is a protection mod if you can protect most dimensions?
