### ISSUE TITLE
[MyTown2-1.7.10-189-dev] NoClassDefFoundError: com/bluepowermod/part/tube/TubeStack

### ISSUE THREAD

**Issue by brunyman** [MyEssentials/MyTown2#253]
Using FTB Direwolf20 with KCauldron-1.7.10-1420.117

I got this crash: http://pastebin.com/2qY2jGZ3

**Comment by brunyman** [comment]
This after the latest modpack update v1.5.0, looks like it crashes too on 0.1.0b

**Comment by GT-SEGFAULT** [comment]
I'm getting this error too, but with FTB Infinity 1.7 - the BluePowerMod isn't even in this pack! Also, this crash happened to me right after someone tried to place a quarry in a non-town area.

**Comment by krwminer** [comment]
Thanks for the info. I made one attempt to reproduce and failed to see it. The more info you can give the better the chances of me finding and fixing it.

**Comment by AfterWind** [comment]
This is an issue with the protection files. Might be some ASM changes BluePower or other mod makes?

**Comment by krwminer** [comment]
Interesting enough this happens on modpacks that do not have BluePower in them. I have not been able to replicate it yet.

**Comment by krwminer** [comment]
This is a BuildCraftCompat bug. I submitted a pull request to fix it:
https://github.com/BuildCraft/BuildcraftCompat/pull/30

**Comment by krwminer** [comment]
The PR has been accepted. The fixed version of BuildCraftCompat should be 7.0.9 or above.

**Comment by krwminer** [comment]
I compiled and tested from the fixed github source at https://github.com/BuildCraft/BuildcraftCompat today and it works fine now. If your server is using a modpack that contains buildcraft-compat-7.0.8.jar and MyTown2, you can remove the broken buildcraft-compat-7.0.8.jar from the server mods folder and replace it with this jar to fix the problem: https://www.dropbox.com/s/58wured0geyksfk/buildcraft-compat-7.0.8_07_09_2015.jar?dl=1

**Comment by GT-SEGFAULT** [comment]
Does the client need to update as well?

**Comment by krwminer** [comment]
No. Just the server.
