### ISSUE TITLE
mytown.protection.notify.modifyBlocks

### ISSUE THREAD

**Issue by zacekjakub** [MyEssentials/MyTown2#255]
Hi, is possible to allow computercraft turtles to perform actions in my town please? I can't allow it globally, but I'd like to use turtles for farming. It was easy in first version of MyTown, but I am not sure here.

Thank you!

The turtle which tried to perform an action just disappeared. :)

**Comment by krwminer** [comment]
Set your town permissions to allow Fake Players:
/t perm set FAKERS true

**Comment by krwminer** [comment]
Reopen this issue if you are still having problems.

**Comment by zacekjakub** [comment]
An unknown error occured while attempting to perform this command.

**Comment by FiveEYZ** [comment]
Mining turtles still turns to "normal" turtle, even if fakers is set to true

maybe the protection file need to be updated for the update that was made? :S

**Comment by AfterWind** [comment]
I tested it @FiveEYZ, what version are you using?

**Comment by FiveEYZ** [comment]
MyTown2-1.7.10-203-dev
MyEssentials-Core-1.7.10-1.5r37-universal
