### ISSUE TITLE
Problem with  a spawn town

### ISSUE THREAD

**Issue by ollillo** [MyEssentials/MyTown2#257]
I made an admin town around spawn so any new players who join won't ruin the area. I set access and activate to true thinking it would let them use a universal coins vendor block but it doesn't let them use it to buy items. They also can't access regular vanilla chests. I have these set to true: access, activate, enter and pickup. Everything else is false except for mobs which is all. Whitelister tool gives mytown.cmd.err.perm.whitelist when I right click anything. How can I let them open and use those items?

**Comment by AfterWind** [comment]
Fixed.
