### ISSUE TITLE
Crash on startup with out clean DB

### ISSUE THREAD

**Issue by JzJad** [MyEssentials/MyTown2#260]
If i reboot the server after towns have been created it crashes, unless i clean the DB/Drop all the tables.

(Part of) latest fml log: http://pastebin.com/TMZE4kqT

**Comment by AfterWind** [comment]
This is an issue with dependencies not downloading. I will assign @legobear154  to this.

**Comment by JzJad** [comment]
Alright thanks have a rather large mod pack im using MyTown in and loving it untill this occured.

**Comment by legobear154** [comment]
@JzJad Try the latest build of MyEssentials-Core. Builds 34 and 35 had a problem with dependencies that should be fixed in build 36+

**Comment by JzJad** [comment]
Sadly im already using that version of MyEC re-downloaded latest versions of both again gave it a try and nope, http://pastebin.com/Tf0aM4wF

**Comment by legobear154** [comment]
Any chance you can create a fresh log from startup to crash and upload all of it? I can't seem to understand why its not wanting to work :/

Also, the logging where it has only %s is fixed in the newest MyTown build on Jenkins as well, which might help up figure out what is happening :)

**Comment by JzJad** [comment]
MyTown 202-dev seemed to have fixed the problem :) If it persists after a few more restarts ill let you know, and ill provide a full log.

**Comment by legobear154** [comment]
Interesting, glad its working now! :) And I am looking forward to not getting that log xD

**Comment by JzJad** [comment]
I lied, after a few restarts then and trying to delete a town, because it wouldnt let me unclaim i get this on a restart... sorry. https://mega.nz/#!AJVxyAbC!LHUULHIg5NAGrfpshu-xHuUINv7IFGBAKB-87ynNASE

**Comment by AfterWind** [comment]
If you can, try a clean database, see if that crashes. If you've already tried that, please tell us what exactly you did since this is a completely different issue than the other one you posted.

**Comment by JzJad** [comment]
With a clean DB it starts fine.

**Comment by AfterWind** [comment]
Ok, what basically happens is there are a few town banks that still exist in the DB of towns that were deleted. I don't know how that's actually possible.

**Comment by JzJad** [comment]
I'll give it another go, clean the DB and add them back in and see what happens.
