### ISSUE TITLE
Update from me

### ISSUE THREAD

**Issue by yepidoodles** [MyEssentials/MyTown2#261]
Hey guys

I've been a little slow and not with it lately, but I just wanted to ask a few things and check in with a few others

I understand that the restrictions flag has been fixed in the newer builds?
All my towns folk can build on other people's plots, but not access, which is odd, wondering if that's fixed or not.

Is it safe for me to update to the latest successful build on Jenkin's?

I've also been learning java, and been playing around with making a plugin to get used to it, so I hope to contribute to MyTown2 sometime in the future, rather than me just telling ya'll what's wrong xD

Also the height thing with the plots doesn't seem to work on my current build

I think that's all for now....

Much love,

Alice

**Comment by AfterWind** [comment]
I did some changes to the permission logic and that screwed up the restrictions flag. It should work now.
The current build is stable, feel free to use it, not many differences from the official release yet.
What issue do you have with making plots?
Would really help having a few more programmers to work on this as we do have ~7 more projects planned for the future.

**Comment by yepidoodles** [comment]
When creating a new plot, the selector says at default: Height dependant: False; but it still goes based on height and isn't bedrock to sky, which is what I assume it means.

**Comment by AfterWind** [comment]
Oh... if it's in "Height dependant: True" does it do it from bedrock to sky?

**Comment by yepidoodles** [comment]
I didn't check, I will do that now

**Comment by AfterWind** [comment]
So basically the Height dependant value is somehow reversed and there are a few bugs when showing the selection. I will look into it.
