### ISSUE TITLE
[Q?] Claim perm node?

### ISSUE THREAD

**Issue by JzJad** [MyEssentials/MyTown2#262]
Is their a Perm node I can deny in my spawn for /t claim. Rather then deny everything including /t spawn, thanks!

**Comment by AfterWind** [comment]
Nobody has access to /t claim unless they are Assistant or Mayor rank in a town (assuming default settings).

**Comment by JzJad** [comment]
I mean for the server spawn, in the area, I would like to deny /t claim and /t new, while their in server spawn, so they dont claim part of spawn. Not the town spawn.

**Comment by AfterWind** [comment]
Oh, you mean you don't have a town in the spawn and you want people to not be able to create/claim chunks in that area, right?
That is not yet implemented, but it's a good feature request.

**Comment by JzJad** [comment]
Yeah, Im working on haveing a command computer display the rules on an advanced screen then have a touch button that ranks them from guest to member, people keep making towns in spawn haha.

**Comment by Luppii** [comment]
You can create an admin town (using /ta) and then give outsiders access to interact with blocks. That way you will protect the spawn but still let new users interact with the machines.

**Comment by JzJad** [comment]
Well i have spawn protected just need it to stop players from claiming with in the spawn.
