### ISSUE TITLE
Flags not working as intended

### ISSUE THREAD

**Issue by wookiefever** [MyEssentials/MyTown2#263]
Hello there,

So I was messing around with flags on my server and I had an issue. Whenever I set the flags for the town they would override the flags for each plot in that town. I have tested this with both the enter and access flags. Also when I set the access flag to false players are still able to right click on chests and furnaces even if they are not associated with that plot.

Currently using:
MyTown2-1.7.10-201-dev
MyEssentials-Core-1.7.10-1.5r36-universal

**Comment by dariusc93** [comment]
@wookiefever can you provide the commands you used so this can be reproduced?

**Comment by wookiefever** [comment]
/t perm set enter false (or true depending on desired effect)
/t perm set access false (or true depending on desired effect)

**Comment by AfterWind** [comment]
`/t plot perm list` to check the perms in the plot. Probably it's just a logic issue in the checkpermission method. Please check that for me if it actually changed.

**Comment by wookiefever** [comment]
I looked into that and it is allowing me to change the flags for plots and not for the town. However changing the town flags overrides the plot flags. I have attached a screenshot link. Players are still able to access inventories in my plot even though they are not associated with the plot. http://imgur.com/XoOtcEM

**Comment by AfterWind** [comment]
Should be fixed in latest build.
