### ISSUE TITLE
MyTown crashing when trying to add ForgeEssentials

### ISSUE THREAD

**Issue by Padavar** [MyEssentials/MyTown2#264]
Was wondering if I could get a hand looking at this issue. Server keeps crashing when both MyTown and ForgeEssentials are added.  

http://pastebin.com/embed_js.php?i=ZtNrX0QC

**Comment by legobear154** [comment]
This is because ForgeEssentials rewrote their permission stuff, again. We will work on getting this resolved asap :)

**Comment by Padavar** [comment]
Appreciate the quick response. I'll try an older version of FE for now.

**Comment by AfterWind** [comment]
This is like the 3rd time we need to rewrite the implementation of FE perm/economy system o.O
Are they doing some kind of huge rewrite preparing for Sponge or something?

**Comment by JzJad** [comment]
I'm thinking thats what it is @AfterWind but the change they made last wasnt huge, im refraining to update FE untill you guys have MyTown play nice with it haha, also looking forward to sponge!

**Comment by legobear154** [comment]
@AfterWind They supposedly "rewrote" the permission API this time >.> One of the last big commits they did basically moved net.minecraftforge.permissions to net.minecraftforge.permission. I would fix this up but I have no clue how to grab the maven version of the one with changes. Gradle isn't updating it so this may have to stay this way for longer than I personally want >.>

@JzJad  I agree! Sponge will be nice! :D

**Comment by jogi01** [comment]
we are trying to setup a forgeessentials/mytown2 server but now we're thinking about to pulp the project down... after every new weak lurks a new crash thats annoying

**Comment by JzJad** [comment]
@jogi01 I suggest using their slightly older stable versions, they work fine.

**Comment by jogi01** [comment]
yes ok.. the older versions are stable but some features would be missing :) we will wait 1-2 month and see whats ready than. i know how hard it is to code and in case of minecraft it must be horrible to reconcile ;)

**Comment by legobear154** [comment]
Meant to reply earlier. Try grabbing MyEssentials-Core build 38 from Jenkins and see if that allows you to use the newest FE. Shouldn't have to update anything but MyEssentials-Core, and FE of course. :)

Reopen this if problem still happens! :)
