### ISSUE TITLE
[Bug] Botania blaster and spreader with bore lens

### ISSUE THREAD

**Issue by superscruffy** [MyEssentials/MyTown2#268]
Players are able to use the mana blaster with the bore lens to destroy anything. The mana spreaders with bore lens are also able to destroy things.

**Comment by superscruffy** [comment]
I'm using:
MyEssentials 1.7.10  1.8r
MyTown2-1.7.10-0.1.0b
Botania r1.7-203

**Comment by AfterWind** [comment]
https://github.com/MyEssentials/MyTown2-Protections/issues
Find the Botania mod in there and move the issue there.
