### ISSUE TITLE
[Suggestion] Dynmap support

### ISSUE THREAD

**Issue by Luppii** [MyEssentials/MyTown2#27]
Well, title says it all. I doubt I have to go into detail. In short:

Dynmap integration for showing nations/towns/plots.

**Comment by AfterWind** [comment]
Closing since it's only for client-side, will come back to this at a later point in time.

**Comment by evernife** [comment]
Any progress ?

**Comment by Eufranio** [comment]
Soon™

**Comment by evernife** [comment]
Two months for 2017...
