### ISSUE TITLE
Farclaim doesn't register with rftools

### ISSUE THREAD

**Issue by LameGirlyCurly** [MyEssentials/MyTown2#271]
Money is accepted gladly but farclaim doesn't appear anywhere using rftools dimension. Refund grrr :(

**Comment by AfterWind** [comment]
Any crash report / issues in logs?

**Comment by LameGirlyCurly** [comment]
Ah entirely forgot to look, sorry..

03.08 08:45:03 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
03.08 08:45:03 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03.08 08:45:03 [Server] INFO at mytown.commands.CommandsEveryone.townCommand(CommandsEveryone.java:36)
03.08 08:45:03 [Server] INFO at mytown.commands.Commands.callSubFunctions(Commands.java:52)
03.08 08:45:03 [Server] INFO at mytown.core.command.CommandManager.commandCall(CommandManager.java:161)
03.08 08:45:03 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606)
03.08 08:45:03 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03.08 08:45:03 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
03.08 08:45:03 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03.08 08:45:03 [Server] INFO at mytown.commands.CommandsAssistant.claimCommand(CommandsAssistant.java:91)
03.08 08:45:03 [Server] INFO at mytown.datasource.MyTownDatasourceSQL.saveBlock(MyTownDatasourceSQL.java:737)
03.08 08:45:03 [Server] INFO at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
03.08 08:45:03 [Server] INFO at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
03.08 08:45:03 [Server] INFO at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
03.08 08:45:03 [Server] INFO at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
03.08 08:45:03 [Server] INFO at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
03.08 08:45:03 [Server] INFO at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
03.08 08:45:03 [Server] INFO at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
03.08 08:45:03 [Server] INFO at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
03.08 08:45:03 [Server] INFO at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
03.08 08:45:03 [Server] INFO at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
03.08 08:45:03 [Server] INFO at com.mysql.jdbc.Util.getInstance(Util.java:382)
03.08 08:45:03 [Server] INFO at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
03.08 08:45:03 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
03.08 08:45:03 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
03.08 08:45:03 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
03.08 08:45:03 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
03.08 08:45:03 [Server] ERROR com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`rrpublic_mytown2`.`Blocks`, CONSTRAINT `Blocks_ibfk_2` FOREIGN KEY (`dim`) REFERENCES `Worlds` (`dim`) ON DELETE CASCADE)
03.08 08:45:03 [Server] ERROR Failed to save Block %s!

**Comment by AfterWind** [comment]
Ok, I see what the issue is. Restarting the server might actually fix it but I will look into fully fixing it. Thanks for the crash report.
