### ISSUE TITLE
Couple of suggestions

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#272]
- [x] 1. change or add: "/t bank pay <number>" to "/t bank deposit <number>".

- [x] 2. When a player use "/t spawn <townName>" the money required will be deposited to said town bank.

- [x] 3.  Make Assistants able to manage plots (delete/remove owner's) they are not a owner of, for example if the player that is the owner of the plot and stop play and the mayor isn't online to often.

- [x] also when adding a resident as a owner to a plot (mostly cause i want them to be able to change perm in their own plot) they will get added 2 times (nothing shows in the logs).
http://gyazo.com/fe6184649d656bf525e27ad1078038de

**Comment by AfterWind** [comment]
All 3 are good suggestions, will implement.
I don't think they are added twice, just shown twice for some reason, will look into it.

Right now we're in the middle of making huge changes in code so it may take longer than usual to implement all of these.

**Comment by AfterWind** [comment]
Everything has been added.
