### ISSUE TITLE
[bug] Can create 1x1x1 plots (0.1.1b)

### ISSUE THREAD

**Issue by Red3Tango** [MyEssentials/MyTown2#274]
Regardless of the settings for minPlotsArea and minPlotsHeight I am able to right click with the plot creation tool, then right-click the same block (now a redstone block) and it creates a 1x1x1 plot.

This was done in a player created town, non-admin (deop), and in gamemode 0. Reproduced by two different players in different towns.

**Comment by FiveEYZ** [comment]
i can confirm this is also happening on MyTown2-1.7.10-219-dev

my plot setting are default in config
