### ISSUE TITLE
ServerTools - No Town Permissions

### ISSUE THREAD

**Issue by groveham** [MyEssentials/MyTown2#275]
Hi,

I'm using ServerTools instead of ForgeEssentials but none of the commands for /t or /ta are usable since there permissions are not passed from MyTown2. 

Even though I have added the required 'cmd.t' and 'cmd.town' as stated by ServerTools I'm still unable to use commands. The author from the ServerTools mod has suggested that it'll be a MyTown2 issue. 
All other commands that other mods add work fine except the MyTown2 Mod. 

I run the following versions:
MyTown2-1.7.10-0.1.1b.jar
ServerTools-CORE-1.7.10-2.2.0.79.jar
ServerTools-PERMISSION-1.7.10-2.2.1.7.jar

**Comment by AfterWind** [comment]
Yeah, seems like it's our fault. We currently do not have support for ServerTools' Permissions system. I'll implement it in the next update. Thanks for the report, did not know ServerTools had a permission system.

**Comment by AiwendilCiunio** [comment]
Hello

I'd like to ask whether this has been fixed or not yet?

**Comment by AfterWind** [comment]
It was implemented in latest build, not yet in any of the official versions. Wait until we fix all the bugs with the build and we'll release an official version after, with this implemented of course.

**Comment by groveham** [comment]
What would you need to put in the MyPermission.conf for this to work? 

S:permissionSystem=$ServerTools

Soon as I load the server, log in, and try /t  -  I get the following error: 
http://pastebin.com/z2zPuNFu

Using: 
MyEssentials-Core-1.7.10-1.12r-universal.jar
MyPermissions-1.7.10-17-dev.jar
MyTown2-1.7.10-0.1.4b.jar

**Comment by groveham** [comment]
OK setting   "S:permissionSystem=$ServerTools" seems to work now. I've added myself as an admin, and created the default group.
