### ISSUE TITLE
Mayor not allowed to delete town

### ISSUE THREAD

**Issue by dw515** [MyEssentials/MyTown2#276]
In version 0.1.3b the mayor can't delete his town. (works in version 0.1.1b) 
"/town leave delete" returns "You don't have the rank required to use this command" even though the user is the mayor of the town. 

KCauldron-1.7.10-1492.150
MyEssentials-Core-1.7.10-1.11r
MyTown2-1.7.10-0.1.3b.jar
MyPermissions-1.7.10-13-dev + PEX

**Comment by FiveEYZ** [comment]
i believe this is fixed now, will test

**Comment by AfterWind** [comment]
Should be fixed in latest build, please test. If it doesn't work use command /ta ranks reset <town> and try again

**Comment by dw515** [comment]
Nope, still erroring, but in a different way. 

http://pastebin.com/vkTCscmd

MT 233, MP 17, MEC 55 + Pex & KCauldron

**Comment by AfterWind** [comment]
You need MP 18, don't know why it didn't build. It should be available now.
