### ISSUE TITLE
GroupManager bridge does not work

### ISSUE THREAD

**Issue by dezil** [MyEssentials/MyTown2#277]
MyEssentials-Core-1.7.10-50-dev
MyPermissions-1.7.10-13-dev
MyTown2-1.7.10-219-dev

KCauldron:1.7.10-1492.150
Groupmanager 2.1.19

/t works and gives a list of cmds

have talked to @AfterWind and looks like that group manager is not picking up the wildcard after the latest update as adding individual perms lets the cmd be used

**Comment by AfterWind** [comment]
I tested and it should now work with GroupManager with the nodes:
mytown.cmd
mytown.adm.cmd
mypermissions.cmd

No support for subcommands, but I don't think that is possible with the current system.
