### ISSUE TITLE
SQL Error when adding some user's to plot

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#290]
Getting a SQL error when adding some user as owner/member to a plot

http://pastebin.com/raw.php?i=QQKLYEBa

after i tried to add another user as owner and it worked just fine
and error when tried to add the first user, so its just for some residents

Using:
MyTown2-1.7.10-223-dev
MyEssentials-Core-1.7.10-52-dev
MyPermissions-1.7.10-13-dev
MySQL: 5.6.20

Aslo:
KCauldron-1.7.10-1448.133
Vault+PEX
FTB Infinity 1.10.1

**Comment by AfterWind** [comment]
Probably fixed in the latest build, please try it.

**Comment by AfterWind** [comment]
Is this fixed, or should I continue searching for the issue?

**Comment by AfterWind** [comment]
This should be fixed.
