### ISSUE TITLE
error after leaving a town

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#291]
im a mayor in 1 town and got invited to a second

so i got invited to a second town, then i selected it and left it and now im getting error when trying to select my first town, everything gets fixed after a reboot. and i have my first town selected again

http://pastebin.com/raw.php?i=vFxmZXtu

https://i.gyazo.com/fd9f729d7a39409a61ab1902337a4c0e.png
as u can see i don't have my "first town" selected after leaving the second (would be green otherwise)
after a reboot the town name is green when doing /t res

**Comment by AfterWind** [comment]
This is probably fixed in latest build, if not, please come back with an updated crash report

**Comment by AfterWind** [comment]
I have tested and this is fixed.
