### ISSUE TITLE
[0.1.4b] Startup crash - ConcurrentModificationException

### ISSUE THREAD

**Issue by brunyman** [MyEssentials/MyTown2#292]
Could not get this new version to work using FTB Direwolf20 modpack and Kauldron also using latest MyEssentials and MyPerms as well all up to date protection modules.

Crash:  http://pastebin.com/gH6VDCwA

**Comment by dariusc93** [comment]
This was because the tileentity was not removed from the list. Should be fixed pretty soon

**Comment by brunyman** [comment]
Great thanks guys for your great work
