### ISSUE TITLE
Localization loading failure

### ISSUE THREAD

**Issue by LubsonGG** [MyEssentials/MyTown2#293]
After updating to 1.4b whenever I execute a command, the response is the permission node required for the command. For example if I were to use /t info then the response would be mytown.notification.town.info instead of information about the town. This happens to all commands.

Using latest version of FE and MyPermissions 1.7.10-17-dev on Forge server with a lot of mods.

**Comment by AfterWind** [comment]
It is not the actual perm node, it is the localization key. Probably the localization does not load properly. Will look into it.
