### ISSUE TITLE
error when after updating to latest of all builds

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#294]
this is what i see when i try to login once: http://pastebin.com/raw.php?i=gArEQz2c

do i need to wipe the DB or something?

**Comment by AfterWind** [comment]
I think it's probably Opis at fault here. As I can see it in the crash report.

**Comment by FiveEYZ** [comment]
its not a crash report, i copied a part from fml-server-latest.log

only thing i changed was:
mt2 223 -> 230
MEC 52 -> 55
MP 13 -> 17

**Comment by AfterWind** [comment]
Ok, I'll look into it.

**Comment by dw515** [comment]
Also it seems like all texts are missing? 

Players only get those:
mytown.notification.town.created
mytown.notification.enter.wild
mytown.notification.enter.ownTown
etc.
MT 233, MP 17, MEC 55

**Comment by AfterWind** [comment]
Try latest MT 233 build with MP 18.
