### ISSUE TITLE
HaoSs mytown2 requests !

### ISSUE THREAD

**Issue by HaoSs07** [MyEssentials/MyTown2#3]
i will post multiple requests here once i remember them.
Note to self. write them on a damn notepad !!

1)Ability to add chunks to player ( that count to final town chunks able to claim by mayor )
2) change the damn formula for chunk calculation. I sure hate it. its hard to get the number you want. Make it : mayor has a fix chunk set. from 1 to 9999. new residences have fix chunk number from 1 to 999. total is mayor +res1+res2+res3+nation chunks
3) pvp flag for ta perm wield:#  
4) item craft/place/brake/etc bans

also i have some request on the other mytown github like autoset townspawn when you claim your first chunk

**Comment by AfterWind** [comment]
Most of the features added, except item/block bans which I will not implement since MANY other mods/plugins do that already.
