### ISSUE TITLE
Crashing and Unable to use commands

### ISSUE THREAD

**Issue by CallumSm1th** [MyEssentials/MyTown2#300]
Hey, I am having a few issues with Mytown2, my first would be, at the moment whenever I place a block in the world I am presented with this crash? 

http://pastebin.com/FtCLwEzL

Secondly, I am having some issues running the commands. but in my groupconfig I put "permissions":["mytown.cmd", "mytown.adm.cmd"] and although I had access to see the commands, like I could see all available commands, I still couldn't use any of them, am I missing something?

**Comment by FiveEYZ** [comment]
i see multimc in the crash log, are u trying to use mytown2 on a client?

**Comment by CallumSm1th** [comment]
I saw the issue there, I swapped over to FTB, and Im not experiencing the crashes anymore, however, I am still experiencing the command issues

**Comment by CallumSm1th** [comment]
I will try the * now sorry I missed that

**Comment by FiveEYZ** [comment]
i just assumed the permission system is similar to PEX

**Comment by AfterWind** [comment]
What permission system do you use? If you use any, you can set it inside config/MyPermissions/MyPermissions.cfg file.
If not, add to the default group, the permission "mytown.cmd".
The permissions field should look like this: "permissions": ["mytown.cmd"]
And for permissions to admin commands you use "mytown.adm.cmd", simply create a different group and add people that you want to access the commands to the group with the command:
`/myperm user group <player> <group>`

I will be making a wiki page for all this during this week, be on the lookout.

**Comment by CallumSm1th** [comment]
I'm not currently using any, I did look at forge essentials, however, I was unsure on the permission nodes to put within it, a wiki would be great, cant wait for that

thanks for the response

**Comment by CallumSm1th** [comment]
I know im being exceedingly annoying here, but could you look at this image and tell me what I'm doing wrong?

http://puu.sh/jOfo0/1b8f7b7ded.jpg

**Comment by AfterWind** [comment]
Hmm, check a few things: 
 * are you in the default group (inside the UserConfig.json file)?
 * any errors in the server log?
 * after modifying the file, did you restart the server?

**Comment by CallumSm1th** [comment]
[
  {
    "uuid": "7b8cd111-0e93-4edd-9da8-30f740467b5f",
    "groupName": "default"
  }
]

I'm in the user group, and no, the server log is clear and yeah I did restart the server, been having a few issues this morning haha

**Comment by AfterWind** [comment]
You might be using an older version of MyPerms, which build are you on right now?

**Comment by CallumSm1th** [comment]
I am using MyPermissions1.7.10-13

**Comment by AfterWind** [comment]
Ah, that's why. That version does not have a fully working system. Try updating to latest MyTown2 which supports build 17

**Comment by CallumSm1th** [comment]
So do I need MyPermission build 17, with what version of mytown?

**Comment by AfterWind** [comment]
Go to the forum page and look into the changelog, it tells you exactly what is compatible with what. Pick the latest version of MyTown2 (0.1.4b)

**Comment by CallumSm1th** [comment]
Ok updated everything, restarted the server, changed the config to "permissions": ["mytown.cmd"], so fingers crossed, lets hope it works

I apologise for somewhat wasting your time,

**Comment by CallumSm1th** [comment]
I'm afraid I face the same problem I did before, that when I update to all of those versions I am stuck with a server that crashes after the world is loaded, it doesnt provide a crash log and simply returns the final lines 

11:55:19] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[11:55:19] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

Perhaps its an issue with the forgecraft pack?

**Comment by AfterWind** [comment]
I need the crash report to know why the crash is ocurring.

**Comment by CallumSm1th** [comment]
That's the problem I'm facing though it doesn't create a crash report, it simple dumps the general server log

**Comment by AfterWind** [comment]
There must be something in the full server log that creates this crash.

**Comment by CallumSm1th** [comment]
I can't really effectively send the full server log as it is over the pastebin limit, is there another option?

**Comment by AfterWind** [comment]
Just send the last ~300 lines before the `[11:55:19] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.` line

**Comment by CallumSm1th** [comment]
http://pastebin.com/NM7J4CuE there you go

**Comment by AfterWind** [comment]
Ok, higher than that, as many lines as you can.

**Comment by CallumSm1th** [comment]
http://pastebin.com/hMd3Qi65 any better?

**Comment by AfterWind** [comment]
`Caught exception from MyPermissions
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 6 column 6
        at com.google.gson.Gson.fromJson(Gson.java:818) ~[Gson.class:?]`

**Comment by AfterWind** [comment]
This is the issue, your GroupConfig.json is not formatted correctly
Paste it here and I will validate it.

**Comment by CallumSm1th** [comment]
[
  {
    "name": "default",
    "type": "NORMAL",
    "permissions": ["mytown.cmd"],
    "meta": {}
  }
]

**Comment by AfterWind** [comment]
Try deleting the file altogether and add the permission to the default group through the command:
`/myperm group perm add default mytown.cmd`

**Comment by CallumSm1th** [comment]
Ok so I deleted the file and am relaunching the server

**Comment by CallumSm1th** [comment]
Server wont launch on reload, I am presented with - still  

[Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

**Comment by CallumSm1th** [comment]
http://pastebin.com/hnD66kMG 

theres the pastebin

**Comment by AfterWind** [comment]
Now UserConfig.json is the issue. Remove that as well, and restart.

**Comment by CallumSm1th** [comment]
shall I just delete the entire mypermissions config folder

**Comment by AfterWind** [comment]
No, you don't need to, just delete all the files aside from MyPermissions.cfg

**Comment by CallumSm1th** [comment]
Ok server has loaded, should I run the command rather than the config change?

**Comment by AfterWind** [comment]
Yes

**Comment by CallumSm1th** [comment]
/myperm group perm add default mytown.cmd

Returns, an unknown error occured whilst attempting to run this command

**Comment by CallumSm1th** [comment]
The group default does not exsist, when run through the command line

**Comment by AfterWind** [comment]
>.> ...
What's the error in the server log?

**Comment by CallumSm1th** [comment]
http://pastebin.com/S6ipEppf

http://puu.sh/jOkS4/e1bf7b2bb9.png

sorry I couldnt see it in the log, hope that helps

**Comment by AfterWind** [comment]
Login to the server and then try this command in the console: `/myperm user perm add <your_username> mytown.cmd`

**Comment by CallumSm1th** [comment]
no luck there 

http://puu.sh/jOljK/9e238047d5.png

**Comment by AfterWind** [comment]
without the `<>`

**Comment by CallumSm1th** [comment]
bigger error this time

http://puu.sh/jOlpU/b39d78ed28.png

**Comment by CallumSm1th** [comment]
wait
no that worked

**Comment by CallumSm1th** [comment]
I can see commands, but it shows the node, such as /town list says "mytown.notification.town.list"

**Comment by CallumSm1th** [comment]
http://puu.sh/jOm81/5b23887323.jpg 

if that helps =]

**Comment by AfterWind** [comment]
That is an issue that will be fixed next version.
