### ISSUE TITLE
Command to show extra block count of player/town

### ISSUE THREAD

**Issue by dw515** [MyEssentials/MyTown2#301]
At the moment you can only see the extra blocks count of a town by using "/town info \<town\>".
However you can not really tell where the extra blocks are coming from. Are they added by the town or a specific player?

My suggestions would be a few commands to:

- [x] show the number of extra blocks of the player (e.g. "/ta res blocks list \<player\>" or by displaying it under "/town res \<player\>")
- [x] show the number of extra blocks and farclaims of the town (e.g. "/ta blocks far list \<town\>" and  "/ta blocks extra list \<town\>")

Or even a command that lists all extra block counts for a town (by players + town extra blocks (+ far claims)) at once. 

 i also would like to add:
command:
- [x] /ta spawn townName
bypasses the teleport cost for mod/admin

**Comment by FiveEYZ** [comment]
i also would like to add:
command:
/ta spawn <townName>
bypasses the teleport cost for mod/admin

perm node:
mytown.adm.bypass (or something)
give the player with this node the ability to bypass town protection. So we don't have to OP all mod/admins just so they can assist player in need of help (if they been griefed and we need to investigate)

**Comment by AfterWind** [comment]
The bypass was already implemented on the latest version, try the nodes:
mytown.bypass.flag.<flagName>

As for the spawn command for admins it's a really good idea, will implement.

**Comment by FiveEYZ** [comment]
worked for me by adding     - mytown.bypass.flag.*
using vault/PEX

and thanks :D

**Comment by AfterWind** [comment]
All of this has been finished. Try the latest build with the commands:
`/t blocks info`
`/ta blocks info`
`/t res`
`/ta spawn`
