### ISSUE TITLE
extra block count of player

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#302]
- [x] MT2 dosent seem to read the amount of the extra blocks added to players in towns

as seen on the picture: 
My town have 47 used out of a total 21 chunks(26 chunks from extra blocks is missing)
https://gyazo.com/2292444c555dbc1199e97868d077bd00

adding the extra blocks to the player wont fix it :/

 - [x] also got this http://pastebin.com/raw.php?i=yk3hFdTB

- [x] Making a plot returns: You cannot be owner of more plots than 0
doing "/t plot limit (anynumber)" returns: Value '
no error in log about that

edit:
might have clicked on something or not :S

**Comment by AfterWind** [comment]
Build/version?

**Comment by FiveEYZ** [comment]
a sorry forgot, justupdated to the latest from jenkins

**Comment by FiveEYZ** [comment]
also got this http://pastebin.com/raw.php?i=yk3hFdTB

**Comment by FiveEYZ** [comment]
also it seems Residents cant access their town

Tried /ta ranks reset <townName>
The flag "restrictions" in the town in question is set to "false", but he was still able to access in his own plot.

Making a plot returns: You cannot be owner of more plots than 0
doing "/t plot limit <anynumber>" returns: Value '
no error in log about that

**Comment by FiveEYZ** [comment]
Cant invite a resident to town because he already exist in another town. 
config is set to: I:maxTowns=3

**Comment by AfterWind** [comment]
That's .... a lot of issues. Will look into them tomorrow ;)

**Comment by FiveEYZ** [comment]
sorry i don't wanna be to pushy but maybe 1 issue can be fixed? like the "resident cant build in the town" 
cause my players are waiting eagerly :s 

plots and extra blocks can wait

**Comment by AfterWind** [comment]
@FiveEYZ try issuing the command `/ta config reset defaultRanks` and the use the `/ta ranks reset (town)` command on the towns needed. See if that fixes the issue you are having with people not being able to access their towns.

**Comment by AfterWind** [comment]
Other than the 2nd issue which I cannot replicate everything should be fixed.

**Comment by FiveEYZ** [comment]
tested 2nd

these are the commands i used:
[15:58:34] [Server thread/INFO]: fiveeyz issued server command: /t borders show
[15:58:41] [Server thread/INFO]: fiveeyz issued server command: /t claim
[15:58:50] [Server thread/INFO]: fiveeyz issued server command: /t bank deposit 50
[15:58:53] [Server thread/INFO]: fiveeyz issued server command: /t claim
[15:58:53] [Server thread/ERROR]: Couldn't process command: 't claim'
 http://pastebin.com/raw.php?i=yash0qc1

now the chunk wont show withe borders but its still claimed
https://i.gyazo.com/55593f9f6caddef073f85620ea558989.png

**Comment by AfterWind** [comment]
This should be fixed now.
