### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Auzze** [MyEssentials/MyTown2#303]
I loaded the 3 main files in multiMC and try to create a new world and it just crashes

http://pastebin.com/TDVP5yck
Crash report.

Mods:
  MyEssentials-Core-1.7.10-1.12r-universal
  MyPermissions-1.7.10-23-dev
  MyTown2-1.7.10-0.1.4b

**Comment by FiveEYZ** [comment]
its not a client mod :S

**Comment by AfterWind** [comment]
Yup, MyTown2 is only compatible with the server-side.

**Comment by Auzze** [comment]
Sorry, what a noob.. I have been working on this new modpak for 3 days...
my brain is fried.

On Thu, Aug 27, 2015 at 10:15 AM, Sergiu Muresan <notifications@github.com>
wrote:

> Yup, MyTown2 is only compatible with the server-side.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MyEssentials/MyTown2/issues/303#issuecomment-135215061>
> .
>



-- 
Stuart (Auzze) Mitchell
Australia
