### ISSUE TITLE
a crash happend

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#304]
just gonna put this here...
crash caused by:
Ender I/O farming Station: http://pastebin.com/raw.php?i=ESrB1GmS

**Comment by FiveEYZ** [comment]
more http://pastebin.com/raw.php?i=ARzs3Fhm + additional http://pastebin.com/raw.php?i=K1pLemhQ

**Comment by FiveEYZ** [comment]
forgot to add:
MyEssentials-Core-1.7.10-56-dev
MyPermissions-1.7.10-25-dev
MyTown2-1.7.10-237-dev

another crash:
TE Autonomous Activator: http://pastebin.com/raw.php?i=C2wc3nEb
more from log here: http://pastebin.com/raw.php?i=Lg8ZRGeu

This crash make some players (myself included :/ ) unable to login if they had a autonomous activator/farming station  placed in the world prior to the latest Mytown2 build 228 i believe

**Comment by AfterWind** [comment]
Should be fixed now.
