### ISSUE TITLE
Error with visualizer and town claim

### ISSUE THREAD

**Issue by LameGirlyCurly** [MyEssentials/MyTown2#307]
Hello, I get the following error when trying to claim a chunk on 236-release, Core 1-12r and Perms 10-26. The claim processes correctly but spills that error in console.

http://pastebin.com/DG7SLqx4

**Comment by LameGirlyCurly** [comment]
update:

with build-239, Core build-57 and Permission build-26 the errors have changed slightly into

http://pastebin.com/ACXHHjTa

**Comment by AfterWind** [comment]
Hmm... try claiming something but execute the command `/t borders show` before. I would like to know if that error still occurs.
