### ISSUE TITLE
[239-dev] You cannot modify the land here

### ISSUE THREAD

**Issue by brunyman** [MyEssentials/MyTown2#308]
Hi, just tried to update to the latest build of Mytown, MyEssentials and MyPermissions and nobody could enter their own towns or break blocks in their towns or even wilderness, all of them get the message: You cannot modify the land here

If you are OP it works fine, am I missing something? Now i'm running MyTown2-1.7.10-0.1.3b as it's the last update that works for me. Running FTB Direwolf20 modpack with Kauldron.

**Comment by AfterWind** [comment]
Yes, you are missing something crucial. Let me explain:
The ranks and their permission are saved in the database and not updated alongside MyTown2 therefore you need to perform the update yourself, here's how you do it:
`/ta config reset ranks`
Then you use 
`/ta ranks reset (town)`
For all the towns that have been created before the update.

**Comment by brunyman** [comment]
Ok, thanks, if there are many towns created before the update, we will have a lot of work :D , What does the town ranks reset do? can it be done by editing the database directly?

**Comment by brunyman** [comment]
is there a way to reset all towns ranks?

**Comment by AfterWind** [comment]
I will implement a command for updating things in the mod. For now you can use tab complete to go through all the towns.
