### ISSUE TITLE
Error when new player tries to create a town

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#310]
As the topic is saying an error occurred when a new player tried to create a new town:  http://pastebin.com/raw.php?i=H61M5GUa

using:
MyTown2-1.7.10-239-dev
MyEssentials-Core-1.7.10-57-dev
MyPermissions-1.7.10-26-dev

**Comment by FiveEYZ** [comment]
error with /t leave delete
http://pastebin.com/raw.php?i=YEanUpEc

**Comment by AfterWind** [comment]
While the `/t leave delete` seems plausible in case the town was deleted when the world was not loaded, the `/t new` issue I cannot identify.
