### ISSUE TITLE
BlockOwners Database issue

### ISSUE THREAD

**Issue by iPencil** [MyEssentials/MyTown2#313]
Hey,

this morning our server went down during a regular restart and wouldn't come back up, there wasn't even a crash report only this in the log:

http://pastebin.com/fDhFwiX8

I've tried updating to the newest builds on the ci as of today, but same issue.

I've opened the sqllite database up and removed the only entry in "blockowners" and the server is working again now.

What caused this?

**Comment by AfterWind** [comment]
There is a tile entity in a world which did not load on startup. Possibly placing a chunkloader on there will fix this issue

**Comment by iPencil** [comment]
It's a quarry, I just looked at the coords. I guess it's with the new "hasOwner" that you recently added.

A chunkloader isn't going to solve it, 1. quarries should chunkload themselves and 2. I can't count on every player doing this :/

**Comment by AfterWind** [comment]
Ok, coming with a fix in a few minutes.

**Comment by AfterWind** [comment]
Done. Try latest builds now.
The perms system now requires you to have `mytown.bypass.<flagName>` in either the rank's permissions or the group permissions. You bypassing all the protections possibly means you have the node `mytown` which gives permissions to all its children node (`mytown.cmd`, `mytown.adm.cmd` and `mytown.bypass.<flagName>`)

**Comment by iPencil** [comment]
I'll test in about 30 minutes and get back to you, thanks for the awesome and fast response!

The permission I have in are currently just : mytown.cmd=true via forgeessentials.

It works pre 236 , not after that.

I'm also using a second account with the default group and no OP.

**Comment by AfterWind** [comment]
Oh, being OP completely bypasses ANY perm. Can be changed in the config file.

**Comment by iPencil** [comment]
No, the second account I use to test doesn't have OP. It's like a regular new user.

**Comment by AfterWind** [comment]
I have tested this before implementing and haven't encountered any issues. Can you give me the flag values and the action you are testing with?

**Comment by iPencil** [comment]
It was my default town which had not had any flags changed ever, was made before the update, and I was simply breaking blocks.

Did the flags change significantly enough that old towns need to be recreated?

**Comment by AfterWind** [comment]
No, the system updates the flags automatically.
So basically there is a default town (in which the player you are testing with is not a member of) but you can still break blocks in it. Is the flag `modify` set to false?

**Comment by iPencil** [comment]
Account 1: made a town before the update, no flags changed. Without update, account 2 can't break blocks. After build 236, no other changes made, account 2 can break blocks.

Account 2 is not member of the town, not OP, has only the permission i said above.

**Comment by AfterWind** [comment]
I tested it right now and this does not happen to me. Try:
`/ta perm town set <town> modify false`
And try breaking blocks now.

**Comment by iPencil** [comment]
Just used the newest build + set the perms again, can still break blocks :(

**Comment by AfterWind** [comment]
Could be an issue with MyPermissions. Look in the MyPermissions.cfg and see if the `permissionSystem` variable is set to `$ForgeEssentials`

**Comment by iPencil** [comment]
S:permissionSystem=$ForgeEssentials

Again, it's working on build 235 which already has the forgeessentials permissions included :)

**Comment by AfterWind** [comment]
Ok, I see what the issue is.
Basically ForgeEssentials defaults all perms that are not command related (like `mytown.cmd`) to true.
Simply set the permission `mytown.bypass.flag.*` to `false` and it should fix the issue. I will have to make it default to false in the future.

**Comment by iPencil** [comment]
Yes that works, thanks for figuring this out! :)

I'll have to see if the quarry thing comes back. Thanks again for fixing this so quickly!

**Comment by AfterWind** [comment]
No problem, that's what I do.
