### ISSUE TITLE
Bug: Selected area is too big

### ISSUE THREAD

**Issue by Callum-MM** [MyEssentials/MyTown2#314]
When trying to switch the plot selection tool to height dependant mode: false it can't claim anything at all. Whenever you try it always says "selection area too big" 
![image](https://cloud.githubusercontent.com/assets/14040343/9612951/73486062-50e0-11e5-9812-30932b21ab7f.png)
 even when you are claiming a 3x3x255 area and the config is set to allow very large plots. The tool itself doesn't look right either as it says both True and false. 
![image](https://cloud.githubusercontent.com/assets/14040343/9612934/660a91ea-50e0-11e5-8168-1a1ce056f0c1.png)

This issue is with Build #239 but i haven't tested it with the latest build since it was only just released. If it has already been fixed then im sorry for wasting your time :P

**Comment by AfterWind** [comment]
Set maximum height to 255 in config. See if that solves the issue.

**Comment by AfterWind** [comment]
Fixed the visual glitch, but the problem seems to be in your config since 254 < 255
>.>

**Comment by Callum-MM** [comment]
Same issue sadly 
![image](https://cloud.githubusercontent.com/assets/14040343/9618571/984975c6-50ff-11e5-8d27-5efbf5c8101b.png)

**Comment by AfterWind** [comment]
Ah... then try 256. That should do it o.O... or any number bigger than that.

**Comment by Callum-MM** [comment]
Yep! that's fixed it! Thanks a bunch. Might be an idea to make the config default to 256 as im sure it currently defaults to 255 so that people don't run into this in the future! Thanks again for all the help (and quick responses :P)

**Comment by AfterWind** [comment]
Yeah, it has more to do with how I check it not what I check. Will fix it.
