### ISSUE TITLE
Permission issue with ForgeEssentials in newest build

### ISSUE THREAD

**Issue by iPencil** [MyEssentials/MyTown2#315]
Hey AfterWind,

turns out the solution to my last issue with the newest version with permissions by adding

mytown.bypass.flag.*=false

isn't exactly working right. Whats happening now is that players are unable to access their own town. It's telling them that the block is owned by X player (their name) but they cannot break/access it at all. Even unclaiming and reclaiming doesn't help.

I really need to use the newest build because of the bugfix you did, I just can't get the permission to work :(

**Comment by iPencil** [comment]
https://github.com/MyEssentials/MyTown2/issues/313

**Comment by AfterWind** [comment]
`/ta update ranks`
Should do it

**Comment by iPencil** [comment]
Great, thank you. It did add a bunch of ranks to towns, I hope this works :) Thanks again for the super quick reply.
