### ISSUE TITLE
Crash with buildcraft builder

### ISSUE THREAD

**Issue by iPencil** [MyEssentials/MyTown2#316]
Hey,

I've had this issue before, but with the newest build, including the newest protection files, I'm still getting this and it's stopping the server from starting:

http://pastebin.com/6iRVSTKK

**Comment by AfterWind** [comment]
` MyTown2{1.7.10-0000r} [MyTown 2] (MyTown2-1.7.10-235-dev.jar) `
You are not using latest build/version.
Get the newest from the forums please. This issue was fixed already.

**Comment by iPencil** [comment]
Yes sorry, it didn't produce a crash report with the newer version and I didn't notice: https://github.com/MyEssentials/MyTown2/issues/317
