### ISSUE TITLE
BlockOwners Database issue still happening

### ISSUE THREAD

**Issue by iPencil** [MyEssentials/MyTown2#317]
Sorry about the last report, didn't notice that the crash with the newer build didn't produce another crash report.

I'm having the same issue with BlockOwners again:

http://pastebin.com/mHEEJ1M4

Just crashes but doesn't produce a crash report.

MyEssentials-Core-1.7.10-60-dev
MyPermissions-1.7.10-31-dev
MyTown2-1.7.10-245-dev

**Comment by iPencil** [comment]
https://github.com/MyEssentials/MyTown2/issues/313 :(

**Comment by AfterWind** [comment]
You may have deleted a world that you were using. That's what could've caused the crash.
The only thing I can advise you do is go into your database and delete the rows from the BlockOwners table that have invalid `dim` ID. You can look into your world folder to find which dimensions you have (if it exists there should be a folder with name `DIM<some_number>` and `some_number` would be the dimension).

**Comment by AfterWind** [comment]
Will look into fixing this forever on the next update ;)

**Comment by iPencil** [comment]
No I'm pretty sure that no world was deleted. This occurred after a regular restart. I'm going to open up the database file and look at it to confirm tho.

**Comment by iPencil** [comment]
Just checked. The Dimension is -28 which is the Galacticraft moon dimension. It's 100% still there as it's a big part of the modpack.

**Comment by AfterWind** [comment]
Just don't restart the server. I will come with a fix tomorrow.

**Comment by iPencil** [comment]
Alright, I'll turn off auto restarts until it's fixed, thank you :)

**Comment by AfterWind** [comment]
Ok, try latest build and see if it fixed the issue.

**Comment by iPencil** [comment]
I have just updated, placed a few quarries and builders on the moon that aren't chunkloaded and restarted. So far, no issues. It seems resolved, thanks again for doing such a fast fix!  We've been using this mod for a very long time, even the original. Nice to see that it's still maintained this actively!

I'll keep my eye on the error for a while, I'll report back if it happens again.
