### ISSUE TITLE
[0.2.0b] NullPointerException

### ISSUE THREAD

**Issue by brunyman** [MyEssentials/MyTown2#318]
Hello, updated to this new version about 1h ago and already got 7 crashes. I updated MyEssentials and MyPerms and the protection modules. 

Crash log:  http://pastebin.com/bQXvzXYh

I'm going to revert the modules update to see if problem is from there.

**Comment by AfterWind** [comment]
Ah, I think it might have been my fault for updating the protections but not updating the build. Try latest build and see if that works.

**Comment by brunyman** [comment]
I reverted the protection to the version i had before and the mod is finally 100% stable, before version 0.2.0b i was getting about 30 crashes a day from MyTown, in 3 days we got 0 crashes. Great job and thanks for this great mod!
