### ISSUE TITLE
Possible my town issue with claim and plot creation

### ISSUE THREAD

**Issue by mirimoo** [MyEssentials/MyTown2#319]
Modpack is modsauce 2.2.2.2
forgeessentials-1.7.10-1.4.3.921-server.jar and previously build 920
MyTown2-1.7.10-0.2.0b

What happen:

Installed MyTown2 to modsauce 2.2.2.1 with fe 920 installed.
Added deny of mytown bypass to fe protections. 
Made config changes and everything seemed to work ok. I could create towns and plots.
Mytown was reading settings from configuration file.

Updated the server to 2.2.2.2 and also updated fe to 921

Outcome:

Players were unable to create new claims or plots.
Mytown stopped reading settings from config file. I've tried several times, but it is persistent.
Reverted down to fe 920 and that didn't help the issue.

Not sure what is going on, console isn't outputting any issues so it looks like this is permissions issue.

**Comment by AfterWind** [comment]
Did you change the `permissionSystem` setting inside MyPermissions' config file to `$ForgeEssentials`?

**Comment by mirimoo** [comment]
Yes, i have done that. Also set deny mytown.bypass.flag.* to stop players from interacting with towns without permissions

**Comment by mirimoo** [comment]
Is there an ingame command I could use to force the setting, like /p global value mytown.config.defaultMaxPlots 5   or something.

**Comment by AfterWind** [comment]
Sadly no, the current config system doesn't allow that. You have to modify the config and reload with `/ta config reload`

**Comment by AfterWind** [comment]
Possibly the latest version of FE is not compatible with MT2. But I don't know why it doesn't work if you downgrade.

**Comment by mirimoo** [comment]
Ok, so only option would be to downgrade down to 2.2.2.1 and fe 920 build with clean install. ... I'll wait for some sort of solution and fiddle around with settings on my own to see if I can figure out why mytown isnt writing the config nor reading from it at all.

**Comment by krwminer** [comment]
Could you test this again with the latest dev builds of MT2/MEC/MyPermissions?
