### ISSUE TITLE
plot size not working

### ISSUE THREAD

**Issue by blasterdude9** [MyEssentials/MyTown2#323]
the plot tool has a max setting of 300 and height of 200 the last time i used it there was no max size

**Comment by blasterdude9** [comment]
i remember before i could plot our a whole spot if the building is in more then one chuck

**Comment by AfterWind** [comment]
Yup, this was implemented before but the check for the size of the plot created did not work. If you want bigger plot sizes just change the values in the config.

**Comment by blasterdude9** [comment]
ok

**Comment by blasterdude9** [comment]
the plot im trying to make is a chunck which the x is on 16 the max is 300 what block or 300 all together?

**Comment by AfterWind** [comment]
It tells you right there on the config: the `plotsArea` is x times z 
For example: If the `maxPlotsArea` is 100 then a plot that is 5x10xsomeHeight will be allowed while a plot that is 10x20xsomeHeight will not.
