### ISSUE TITLE
Enhancement: Flag Variables

### ISSUE THREAD

**Issue by Callum-MM** [MyEssentials/MyTown2#333]
I think it would be really great to have a command which shows what the options for each type of town/plot flag are. On our server, one of the most commonly under-used flags is mobs: passives. Nobody knows it exists at all unless i tell them! Even then, they try "passive" and that doesn't work of course and they give up and don't use it anyway! Maybe it could have the same formatting as the current town flags but instead of a description of what the flag does it just has each of the settings.

[mobs] : (all / none / passives)
[Fakers] : (true / false)
[Enter] : (true / false)

I'm not really sure what the command should be though. Maybe something like ./t perm options or ./t perm variables

**Comment by AfterWind** [comment]
I am currently working on changing how flags work. The `mobs` flag will no longer be a `String` type but instead it will be a `Boolean` type, so it can only accept true/false values. I will also add the flag `entities` if someone wants to disable all living entities (mobs included).

There is no need for a command, I think simply adding a tab completion when using the command to set the flag will be enough. With this change I will also add the `/t perm toggle` command to toggle between true and false.

**Comment by Callum-MM** [comment]
Sounds great. Thanks!
