### ISSUE TITLE
Some players are unable to properly create towns, town Mayor is set as SystemAdmins

### ISSUE THREAD

**Issue by rjdunlap** [MyEssentials/MyTown2#340]
We've had 2 players now on our server who when doing /town new are unable to create a town where they're the Mayor; the town is "created" but Mayor is set as SystemAdmin and when using /mytownadmin add [name] [town] Mayor it says there is no rank of Mayor in that town..

**Comment by AfterWind** [comment]
Any logs that you can find?

**Comment by AfterWind** [comment]
No response.
