### ISSUE TITLE
updating issues

### ISSUE THREAD

**Issue by Eidelmaim** [MyEssentials/MyTown2#342]
we updated our server from 

MyTown2-1.7.10-245-dev.jar /  MyPermissions-1.7.10-31-dev.jar / MyEssentials-Core-1.7.10-60-dev.jar 

to

MyTown2-1.7.10-253-dev.jar / MyPermissions-1.7.10-34-dev.jar / MyEssentials-Core-1.7.10-67-dev.jar

this was done on a fresh world map with no towns created, and only admins on it for initial set up. the problem is now no one, not even opped admins can do anything with land... we get this message... http://prntscr.com/8oha2p

**Comment by AfterWind** [comment]
Sometimes builds don't work well together. Go in the server log and find out if there's any errors shown in there.

**Comment by Eidelmaim** [comment]
there were no errors listed in the logs, it looked as if everything loaded correctly. the only error is the ingame notice that the area your trying to build/destroy blocks in is owned by Server Owners and nothing else.

**Comment by AfterWind** [comment]
Build 253 is not working because that was built in the middle of a really big refactoring. Just downgrade and wait for the next build.

**Comment by Eidelmaim** [comment]
sadly we can not downgrade, we had to disable mytown completely, every build is crashing our server when there are explosions in the world.... if it helps we are running infinity 1.11.2 with KCauldron-1.7.10-1448.133, 25 plugins installed, i can provide a list if you think a plugin might be conflicting

**Comment by AfterWind** [comment]
Ah, you can try disabling `extraEvents` in the config file. That will fix your issue. I will come up with a patch for this later.
