### ISSUE TITLE
Error with WildPermsConfig

### ISSUE THREAD

**Issue by JzJad** [MyEssentials/MyTown2#343]
After upgrading to the latest version the server crashes giving me this.
http://pastebin.com/rFnQaq0T

**Comment by JzJad** [comment]
I tried removing the config folder and having it create new configs and same thing.

**Comment by AfterWind** [comment]
What versions are you using? From the crash report it seems to me that you forgot to update MEC.

**Comment by JzJad** [comment]
MT: 253
MEC: 71
MP: 34

**Comment by AfterWind** [comment]
Ah, build 253 is not ready to be used yet. Sorry.
