### ISSUE TITLE
onPlayerAttackEntity causes client internal server error

### ISSUE THREAD

**Issue by Eidelmaim** [MyEssentials/MyTown2#344]
hey afterwind, the fix you gave us for stopping explosions from crashing the server worked a charm, we have discovered a new issue with players PvP. when a player attacks another player either by punchin, sword, or any weapon at all including modded weapons and ranged weapons the attacking player is crashed with a internal server error.

In this pastebin, the first errors you see are pulled from console and the second error log is pulled from client side latest.log.

http://pastebin.com/ucdiZhrs

this is on Infinity 1.11.2 using Kcauldron build 1448.133 and MyTown2 build 246-dev

**Comment by AfterWind** [comment]
Is the mod installed on the client side?

**Comment by Eidelmaim** [comment]
server side

**Comment by AfterWind** [comment]
Ah, ok. This will be fixed in the next version.

**Comment by AfterWind** [comment]
The whole system changed. Probably fixed.
