### ISSUE TITLE
Infinite loop crash from ProjectE protections

### ISSUE THREAD

**Issue by nanakisan** [MyEssentials/MyTown2#346]
This is a severe bug I just discovered.

The server will start going into a infinite loop when a Red Matter morning star is used to grab ores in a claimed area. The chat just keeps on being spammed with warnings about how the area is protected. Further more this issue completely cripples the server outright. I cannot issue any commands. Not even in the console itself.

To put it in a visual sense. If you right click with RM:MS on any ore. all ores in that immediate area will begin flickering constantly. It's like the claim just simply isn't preventing the right click action.

**Comment by nanakisan** [comment]
Update
This bug is not limited to just the morningstar. It is any of the mining tools

This issue does not cause anything to happen in console. so I have no other technical information to provide.

**Comment by AfterWind** [comment]
Unfortunately this bug is not caused by MyTown2 itself, it's caused by ProjectE not handling the cancelling of the break event properly. So it continually tries to break blocks while they are being replaced because the event is cancelled. Try contacting the ProjectE developer please.
