### ISSUE TITLE
BuildCraft Quarries

### ISSUE THREAD

**Issue by Callum-MM** [MyEssentials/MyTown2#348]
Using MyTown2 build 246-dev (can't update further atm, have tried)

Buildcraft quarries don't seem to work properly as fakeplayers. If you place one in a town, and set the town's flags to "Fakers = true" then it can build, it can destroy no problem, but if you put it in the wild where the wildperms are set to "Fakers = true" it can't build or destroy anything at all. not sure if im missing something but i tried all the usual, making almost every variation of [BuildCraft] i could think of OP, and adding mytown permissions to them in the permissions file but they still only work inside towns.

**Comment by krwminer** [comment]
This should be fixed in MT2 dev build 279, but I have not been able to verify that yet.

**Comment by krwminer** [comment]
OK. I tested this with the latest dev builds. It works.
