### ISSUE TITLE
MySQL or SQLite?

### ISSUE THREAD

**Issue by Morketh** [MyEssentials/MyTown2#350]
was digging around in the directory structure adfter getting all of this working and saw a couple DBCs one with MySQL and the other with SQLite. Is there Actual support for MySQL? or is this only for the SQLite? would love to see actual MySQL support if at all possible was hoping maybe i could write an admin panel using PHP and MySQL that could link into MyTown2

**Comment by FiveEYZ** [comment]
I'm using mt2 with only MySQL, i would say its fully supported.

**Comment by AfterWind** [comment]
Yes, we support both MySQL and SQLite

**Comment by Morketh** [comment]
Well that is good news indeed i know the issue/question has been closed however id like to ask a follow up question concerning the location of the configuration settings and the SQL structure. Is there some examples some where in a wiki or out on the web some place? or are they in the configuration settings and i just need to configure them?

**Comment by AfterWind** [comment]
Go to `config/MyTown/MyTown.cfg` and change the `dbType` to `MySQL`. Restart the server. Voila, you should have the needed fields in the config. (user, password etc.)

**Comment by Morketh** [comment]
Well that seems to be working restarted and looked at the config settings sure enough there there however that leads me to the MySQL structure. is there an SQL file i need to import? in order to install the database all the tables set up, a user? Specific Permission i need to GRANT to the MyTown2 DB User? im not about to give Minecraft the root account to MySQL as this could lead to MySQL Injection and a full take over on the server. id like to set it up in a way that is both secure and usable. is there an SQL file included here in the repository some where that ive over looked?

**Comment by cjm721** [comment]
That is all determined by the username / password you put in the config file. If you only want to give it access to certain databases in your MySQL server only grant the user you create for it access on that database.

**Comment by Morketh** [comment]
so can i assume that i create a blank DB a new User grant full perms to the new DB to the new User and restart minecraft? and then it just works? im not really used to the magic button approach to installing MySQL in the years that ive been programming its hardly ever that easy

**Comment by Morketh** [comment]
well that is amazing. In all the years ive been running MySQL applications ive only ran across a few that installed there own DBs on first startup good Work guys after plugging in the variables it was literally plug it in and watch it go thank you guys for the help.
the learning curve is steep but i think the user/admin simplicity is just that simple.
