### ISSUE TITLE
can no longer use all the protection files

### ISSUE THREAD

**Issue by dezil** [MyEssentials/MyTown2#352]
I see you have made a change in the code that requires the protection files "mod" to be installed on the server, is there any way to change this back to the past functionality?

or at least print an error of what config needs to be removed 

though ideally just not loading the json if it cant find the class would be better, though I have no idea if that can be done or not

**Comment by AfterWind** [comment]
Removing protections if the mod that was linked to could not be found was already implemented.
I am aware that most messages are missing, I will try to get them beck and working, it is somewhat difficult though.

**Comment by dezil** [comment]
wait so it am I supposed to be able to just dump all the protections in?

**Comment by AfterWind** [comment]
Yes

**Comment by dezil** [comment]
ok I get this error when I do that http://pastebin.com/4su5RgSf

**Comment by AfterWind** [comment]
Hmm, ok I will fix that.

**Comment by krwminer** [comment]
Fixed in latest dev builds of MT2/MEC/MyPersmissions.
