### ISSUE TITLE
MySQL issue

### ISSUE THREAD

**Issue by dezil** [MyEssentials/MyTown2#354]
ok trying to get MySQL working tried to use my old config (updating a server) didn't work so I regened the config and put MySQL as the DB type let it regen put in the fields "username, host, DBname, and password" and still getting this error http://pastebin.com/UNSfqqQS

have also tried with a fresh MySQL DB and no luck

**Comment by dezil** [comment]
@krwminer tried your updated MEC still not working new crash http://pastebin.com/U4TGx4RZ

**Comment by dezil** [comment]
ok ignore that we got it working, but not 100% sure on why or how

**Comment by krwminer** [comment]
I got that error also after I fixed the MySQL connection bug last night. That is why I said there might be another issue. I will try and check into that tonight along with protections if I can. Getting closer... :)

**Comment by krwminer** [comment]
Fixed in latest version of MT2/MEC/MyPermissions.
