### ISSUE TITLE
dimension switching bug

### ISSUE THREAD

**Issue by Callum-MM** [MyEssentials/MyTown2#356]
With the newest version of MyTown(# 264), MyEssentials(# 82) and MyPermissions(# 39) I'm getting some strange bug. I can teleport around the overworld no problem at all but any time i try to change worlds it just sends me to my town spawn. I have tried ./home, I have tried ./tpx, I have tried ./warp and I have tried building portals. All of them send me to my town's spawn! This is a bit of a strange bug and I'm afraid there is absolutely no help from console, client side console or any logs. To hopefully help you a bit I've done a little testing 
- If I delete my town it lets me change worlds again.
- It only affects players in towns. Players who aren't in towns can travel as normal but players in towns are sent to their town's spawn.
- It seems to affect ALL players in a town regardless of their rank
- On an unrelated related note, DefaultTownRanks.json generates blank and ./ta config reset defaultRanks completely wipes it (I assume because of the same initial generating issue)
- Filling the town Ranks file manually with a copy from previous versions does fix the default ranks but doesn't fix the dimension bug. (I didn't expect it to, they seem completely unrelated things)

While I'm at it, it looked like the update also stopped ALL hostile mobs spawning regardless of wilderness or town flags. Peaceful mobs worked along with their [entity] flag but hostile mobs just wouldn't spawn. They started spawning again when I went back to the old version.

**Comment by AfterWind** [comment]
Could be the `ENTER` Wild flag set to `false`

**Comment by Callum-MM** [comment]
![wildperms](https://cloud.githubusercontent.com/assets/14040343/10559862/8914c838-74f1-11e5-980d-242e629618de.png)

Wilderness doesn't have an entry flag

**Comment by dezil** [comment]
can confirm this bug

**Comment by krwminer** [comment]
All these issues fixed in latest MT2/MEC/MyPermissions.
