### ISSUE TITLE
QuiverBow Obsidian Wither rifle ignoring town protections

### ISSUE THREAD

**Issue by deadman96385** [MyEssentials/MyTown2#361]
Currently all QuiverBow weapons that do block damage are blocked in towns but the Obsidian Wither rifle does damage to blocks my guess it is because it is not declared in explosion like the others.

**Comment by AfterWind** [comment]
Move this issue to the MyTown2-Protections repository, please.

**Comment by deadman96385** [comment]
Sorry about that remade it there
