### ISSUE TITLE
[0.3.0b] Issues, failed to get it working.

### ISSUE THREAD

**Issue by brunyman** [MyEssentials/MyTown2#362]
Today I Updated from 0.2.0b to 0.3.0b, however from the first run the server crashed and then spotted issues that prevented me from getting it working, after 1h for trying I give up, i'm back to stable 0.2.0b

I used:
MyEssentials-Core-1.7.10-1.14r-universal
MyPermissions-1.7.10-41-dev
MyTown2-1.7.10-0.3.0b
And latest protection modules.

KCauldron running FTB Direwolf20 modpack.

Here are the 3 issues that I found:

1) The mod failed to generate the DefaultTownRanks.json and server crashed, no crash log generated only an error on logs. The DefaultTownRanks.json that was generated was empty. I managed to get over this issue by using the old file I had from previews version.
Log: http://pastebin.com/F48KGEtP

2) Server crashed when MyTown tried loading the protection modules. After some testing the modules that were crashing were: ComputerCraft.json (the TileEntity part with Turtle protection) and RFTools.json . Note that I only installed modules for mods that my pack has, so I don't know if there are more modules crashing. By removing these 2 modules I managed to get over the protection modules loading part.
Log: http://pastebin.com/b7RfYYud

3) This is something with ticking and protections, this one generated a crash report.
Crash log: http://pastebin.com/LUGCt0Xc

Thanks, I hope they get fixed soon :D

**Comment by AfterWind** [comment]
1) is confirmed
2) may be fixed by updating protection files
3) will get fixed

**Comment by krwminer** [comment]
1) Fixed in the latest dev builds

**Comment by krwminer** [comment]
All these should be fixed in the latest dev MT2/MEC/MyPermisions/MyTown2-Protections.
