### ISSUE TITLE
Question: Can we prevent people from disabling a perm?

### ISSUE THREAD

**Issue by 0zlw** [MyEssentials/MyTown2#365]
Hi, Dez and I just have a question about how we can setup MT. Is there a way to stop people toggling one particular perm, either by permissions or by config. We want to stop people being able to switch mobs off on one of our servers.

**Comment by AfterWind** [comment]
Yes. Look into the FlagsConfig, you can set which perm should be inside a town or not.

**Comment by 0zlw** [comment]
Thank we will test this later today.

**Comment by 0zlw** [comment]
We had a go trying to make this work with this config, but it didn't appear to prevent the perm from being changed.

http://pastebin.com/qLbTurrc

**Comment by AfterWind** [comment]
Oh, ok, I will look into it. Probably some bug I've introduced accidentally. I'll come back with a fix.

**Comment by krwminer** [comment]
Fixed in MT2 dev 270.
