### ISSUE TITLE
Users cant access town blocks once claimed?

### ISSUE THREAD

**Issue by JzJad** [MyEssentials/MyTown2#367]
Maybe im missing a perm node some where assuming they changed, but normal users without bypass, once they make a town, they them selves cannot access anything either?

**Comment by krwminer** [comment]
I am not able to reproduce this. Could you provide more info?

**Comment by JzJad** [comment]
Once a player creates a town, he can no long access anything claimed by HIS town, Running with ForgeEssentials
FE: 1011
MT2: 269
MyP: 41
MEC: 88

**Comment by JzJad** [comment]
And im seeing no new Perm nodes, or are they not showing?

**Comment by dezil** [comment]
can you test with FE 1.4.1 as that is the recommended version to use with mytown, I'm not using FE on my servers so cant test if the issue is being caused by that

**Comment by JzJad** [comment]
Well if i remember right FE had a overhaul of how it handles permissions or something major like that, and if i where to do that i dont think the new mytown would work, also had mytown working just fine with it before.

**Comment by AfterWind** [comment]
This could be an issue with your ranks setup.
I think you need to execute `/ta update ranks`

**Comment by JzJad** [comment]
Aw yes like always AfterWind, problem solved. Strange.
