### ISSUE TITLE
Chisel Protection File Crash

### ISSUE THREAD

**Issue by wraith1200** [MyEssentials/MyTown2#371]
When launching the server it will fail to start due to an error with MyTown2 parsing the protection file for chisel.

MyTown2: 273-dev
MyEssentials-Core: 88-dev
MyPermissions: 41-dev
ForgeEssentials: 1.4.3.958

http://pastebin.com/gEmiD2Mk

**Comment by krwminer** [comment]
Are you using the latest protections? https://github.com/MyEssentials/MyTown2-Protections
Also, please submit protection problems under MyTown2-Protections issues.

**Comment by wraith1200** [comment]
I apologize for submitting the ticket to the wrong location.I can open the ticket under the correct location. I just downloaded the latest protections this morning.

**Comment by krwminer** [comment]
OK. I will check it out tonight after work.

**Comment by 0zlw** [comment]
We had an issue with this a couple of nights ago on IRC. I believe it's something to do with Chisel 2 being forked back into 'Chisel' as the dev team split.

**Comment by krwminer** [comment]
Use the latest dev version of MT2 (275+) and the updated MyTown2-Protections.

**Comment by Callum-MM** [comment]
Sorry to butt in but i think i can help here. The issue is not chisel (which confuses me because it throws an error that makes it look like its chisel) but I think its actually the agricraft.json protection file. Even with the latest mytown, myperms, myessentials and the latest protection files this issue is still happening. The only thing that stops it happening for me is removing agricraft.json

**Comment by krwminer** [comment]
There are two version of Chisel. Both were forked from the original versions of Chisel. One is called Chisel 2 and the other still just Chisel. Both use the *same* modid of "chisel" for their mod.

I noticed that @wraith1200 was using the version of Chisel that the protection file was not made for. I downloaded it and tested it and got the same crash. I renamed Chisel.json to Chisel2.json and added a "name" field comparison to the json and MT2, so it now uses the Chisel2.json only for the Chisel 2 mod.

This fixed the issue. You need to delete any old Chisel.json file you have as there is not such thing anymore.
