### ISSUE TITLE
TC Golems

### ISSUE THREAD

**Issue by groveham** [MyEssentials/MyTown2#374]
Just updated to MyTown2-1.7.10-0.3.1b but now golems are not able to place Sapplings in towns, or any blocks for that matter. 
I've tried to allow all the flags but this had no effect.
I've removed the chunk from the town doing /t unclaim and now the golems are able to place the sapplings so atleast there is a workaround for now but means that this section of land is unprotected by the mod.

**Comment by 0zlw** [comment]
Hey, from reports I'm getting from our server, it appears the fakers flag regardless of whether it is true or false isn't working. We had an issue with Activators from Thermal Expansion where they couldn't break cobblestone blocks inside mytown2, but worked fine when not inside a claimed area.

**Comment by krwminer** [comment]
Fixed in MT2 dev 279 build
