### ISSUE TITLE
Pvp flag not functioning properly

### ISSUE THREAD

**Issue by dw515** [MyEssentials/MyTown2#377]
No matter if the pvp flag is set to true or false, pvp seems to be always on in the recent versions.

MEC89, MP43, MT280

**Comment by dw515** [comment]
Sorry to bother you with this once more. ;)
Since the changes for v0.3, residents/mayors can bypass the PVP flag in their town by default.

Which means they can attack each other and other players if they're in their own town (the others can't fight back though). And that's not really the point of "no pvp".
It's probably solvable by modifing the ranks (like "-mytown.bypass.flag.pvp"), but I doubt it's intentional in general.

**Comment by krwminer** [comment]
No players can attack one another when in an area with PVP set to false.
Fixed in #301.
