### ISSUE TITLE
Some actions aren't working as expected

### ISSUE THREAD

**Issue by dw515** [MyEssentials/MyTown2#378]
I think certain actions are a little bit broken since the latest updates.

Examples: (not sure if others are broken as well)
RIGHT_CLICK_AIR
RIGHT_CLICK_ENTITY

..don't get blocked with all sorts of items, e.g.:
Thaumcraft Wand + Focus: Shock 
IC2 Mining Laser

If you click the ground, they get blocked. If you click in the air or on entities, they don't get blocked.

It worked fine in 0.2.0b, but it doesn't in the recent dev versions. 
And since the actions are setup correctly (according to the wiki), I don't think it's a problem with the protection files but rather with MyTown itself.

Tested with MEC89, MP43, MT280

**Comment by krwminer** [comment]
I will try and look at this tonight along with the PVP problem. Thanks for testing these. There was a big refactoring internally between 0.2.0b and the current releases. I am trying to go through and fix things up. :)

**Comment by krwminer** [comment]
I think this fixes both problems, but I was not able to see the RIGHT_CLICK_ENTITY problem after I fixed the first case. Please re-open if it is still a problem.
