### ISSUE TITLE
Tax support

### ISSUE THREAD

**Issue by LemADEC** [MyEssentials/MyTown2#382]
Any chance we could have a tax system added, a bit like towny: every x hours, you need to pay $y per chunk owned ?

**Comment by AfterWind** [comment]
We have that already, although it's limited to `x amount per day per chunk and per town`.

**Comment by LemADEC** [comment]
how do I set it up ?

**Comment by AfterWind** [comment]
In the config/MyTown/MyTown.cfg file you have the fields `costTownUpkeep` and `costClaimUpkeep` or something similar.

**Comment by LemADEC** [comment]
Got it, it's "I:costTownUpkeep", thanks!
