### ISSUE TITLE
missing comments in configuration

### ISSUE THREAD

**Issue by LemADEC** [MyEssentials/MyTown2#384]
According to https://github.com/MyEssentials/MyTown2/blob/505572eeab40e15906bebe9001e08e6b2bbcba5a/src/main/java/mytown/config/Config.java comments are provided but they won't show up in the generated configuration file.

We could be missing a flag to enable them or configuration isn't save?

**Comment by 0zlw** [comment]
I know that for us, comments appear initially in the config file, then disappear later, often when we flag dbtype to mysql.

**Comment by krwminer** [comment]
This is fixed in the dev build #95 of MEC.
