### ISSUE TITLE
Can't make FarClaim

### ISSUE THREAD

**Issue by 0zlw** [MyEssentials/MyTown2#388]
Even with maxFarClaims=1, I get a "You cannot have anymore far claims" message without having any far claims in the first place.

**Comment by AfterWind** [comment]
What version are you using?

**Comment by 0zlw** [comment]
Latest dev.

**Comment by AfterWind** [comment]
Try making a new town and see if you can claim far with that.

**Comment by 0zlw** [comment]
The town was new and made specifically for testing

**Comment by dw515** [comment]
It seems that the far claims are only pulled from the config once (when the town gets created).
However the farclaims of old towns don't adapt to changes made in the MyTown.cfg. 

Is that intended? I'm pretty sure that they updated properly in older versions.
The block count per resident still updates when changes to the MyTown.cfg are made.  

Running the latest dev builds.

**Comment by krwminer** [comment]
It is intended. The MyTown.cfg is used on Town creation, (default),  then you can use the commands to adjust it after that on a per Town basis.

If you want all of your towns reset to the MyTown.cfg, load MyTown2.2-1.7.10-293-dev.jar and bring up the world. Then bring it back down again and use the latest.
