### ISSUE TITLE
Far claims not working

### ISSUE THREAD

**Issue by yepidoodles** [MyEssentials/MyTown2#392]
I recently (finally) updated to the latest version, but no matter what I do I can not seem to enable far claims, any help?

Changing 'I:maxFarClaims=' doesn't do anything

- Alice
DragonTechMC

**Comment by dezil** [comment]
I believe you have to edit the claims for existing towns but new ones made after the config change will pick it up

**Comment by krwminer** [comment]
There was a bug where the maxFarClaims was ignored from MyTown2.cfg, but that has been fixed in the latest dev build of MT2. You can use the "/ta blocks far set <town> <amount>" command to adjust any already existing town.

**Comment by 0zlw** [comment]
Given how this issue has cropped up a few times, would it make more sense for the far claim amount to always be taken from the config for each town, then adjusted by extraFarBlocks. It seems silly for me for a change in config setting to not change the set value for towns. As a server, if I want to change my far claims amount from say 1-5 it is imfeasible to change it for every town to make it happen.

**Comment by krwminer** [comment]
I am waiting till I can get a hold of AfterWind to check on this. I agree with your idea.

**Comment by dezil** [comment]
saying that it was easy for us to change @0zlw a simple cmd on phpmyadmin did the job, that will not be the case for all users though

**Comment by yepidoodles** [comment]
Thanks for the help

**Comment by krwminer** [comment]
Build #297 of MT2 has the change. It should use the MyTown2.cfg maxFarClaims value plus the extraFarClaims set on a per town basis by command for the total maxFarClaims for a given town.
