### ISSUE TITLE
Modify Flag now allows everyone to modify the land

### ISSUE THREAD

**Issue by deadman96385** [MyEssentials/MyTown2#393]
When we updated to the latest build to fix the UUID spamming it made it so there is no way as far as we can tell to make it so only town members can modify the land. Because if you have modify on then anyone can modify the land but if you have modify off then no one can modify the land. Maybe we are just looking over a setting somewhere but if you could enlighten us that would be amazing

**Comment by krwminer** [comment]
Setting "modify" to true is suppose to allow outsiders to modify your town land. Set it to false.
If you want Residents to be able to modify the the town land, then make sure the "restrictions" flag is set to false.
Close this out if that fixes it, if not please provide more info. Can the Mayor modify the land? What message does it give,  what DB are you using, etc.

**Comment by deadman96385** [comment]
The mayor can not modify the land, we are using MySQL, the message states "You cannot modify the land here Owners: S3S" S3S is the mayor of the town in this example. Ops can still modify in towns.

This is our DefaultTownRanks.json we have restriction removed from all of them because we do not want people changing the perms for example access because we are a pvp raiding server
http://pastebin.com/gUgmbF8v

**Comment by krwminer** [comment]
Please use the latest dev versions for all:
MyPermissions: 46
MyTown2: 296
MyEssentials-Core: 95

Also I would save a copy of your DefaultTownRanks and have it regen a new one. Then edit back in the changes from default you had. Basically the syntax changed. You need to specify "mytown.cmd*" to mean all mytown commands. "mytown.cmd" is just the perm for the base command /town.

**Comment by deadman96385** [comment]
We have updated to the latest dev versions regen'd the configs and there is no issue if we do not use the database from the previous version but if we tell mytown to use it then the mayor can not build in the town with the same error as above.

**Comment by krwminer** [comment]
Try this command with your old DB: "/ta update ranks"

**Comment by deadman96385** [comment]
That fixed it, out of curiosity what does that command do on the backend?

**Comment by krwminer** [comment]
It resets the rank containers in every town. Adds new rank names as needed and deletes unused rank names.

Method resetRanks() in: https://github.com/MyEssentials/MyTown2/blob/5c196ef5b88de0f199f0d98518a3ac140198362e/src/main/java/mytown/new_datasource/MyTownDatasource.java
