### ISSUE TITLE
Updating issues

### ISSUE THREAD

**Issue by Eidelmaim** [MyEssentials/MyTown2#394]
Hey afterwind,

got an updating issue here that's really boggling our minds, we are updating from 246 to 296 and we are getting 2 different server crash errors....

the first crash is http://pastebin.com/n9scM6Tj it is when we update the server by renaming all the old mytown folders/files to -old and running the server with the new mytown, myperms and my essentials, after starting the server for the first time we add our database file to the new directory for the data base and it generates this error.

the second method we tried was to after installing the updated mods we let it run and generate its own database file, when the server is up and running we added our database file and reloaded the database files in console... this is the error that generates.... http://pastebin.com/sZXyc6HX

we have update the protections to the latest, we even started the server with no protection files, same result either way. we can update and start the server up just fine IF we do not add our old database to the server, but we lose all our players towns :(

any ideas ?

thanks in advanced.

interestingly enough though, we can perform the update like mentioned above locally on a personal computer but once we do the update on our dedi these errors are generated. personal computer is windows, dedi is linux

**Comment by krwminer** [comment]
In the first crash case, you had it regen all the configs and database, brought down the server, replaced the newly created database with your old database and brought up the server again and let it update the database, right?

It seems in the first case like it might have a bad dimension ID tag in the sell sign TE. I will fix that crash case.

**Comment by Eidelmaim** [comment]
that is correct in the first case

**Comment by krwminer** [comment]
Let me know if you build #298 works.

**Comment by Eidelmaim** [comment]
thank you, this update worked, but with on issue, and it is something that we should be able to fix on our own, it is with the protection files, we have added custom protections that we will have to re add. the server starts and runs perfectly with the latest protections files, but with our modified ones it crashes.... but it is most likley a formatting issue and we can handle it from here. again thank you very much !

**Comment by Eidelmaim** [comment]
resolved people not being able to enter the towns by running the ./ta update ranks command
