### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Morketh** [MyEssentials/MyTown2#397]
Crash report saves here: http://ci-main.no-ip.org/minecraft/crashreports/crash-2015-11-17_17.59.19-server.txt
I was looking through my crash-reports on the sever doing my mid-week administrative duties and found this report. Non of the players on my server have said anything about this error but i wanted to let you guys know just in the event that it was a bug.

**Comment by krwminer** [comment]
I can not connect to the link you gave. You might want to use pastebin.

**Comment by Morketh** [comment]
Network is down for repairs tonight I had to pull an extra cat-5 cable
should be back up later tonight . Posting on pastebin would have to wait as
well as the logs are on the server that is under repair I apologize for the
inconvenience.

**Comment by Morketh** [comment]
Alright all network services have been restored and should be operational. Again my apologies for the delay

**Comment by krwminer** [comment]
Thanks for the info. This happened when you were bringing down the server for some reason and it is a very old version of MT2, so it is hard to figure out all the issues around this crash at this point. It looks like the DB request was returning a null where it was not suppose to. It is actually not really a problem as what is was trying do will happen on the next shutdown.

I suggest bringing your server up the latest dev versions of everything and the latest protection files.

I will close this now, but please open a new one if you encounter a crash again.

**Comment by Morketh** [comment]
Thank-you for the help on this.
