### ISSUE TITLE
Can't mount on own horse inside other cities or control tamed wolfs/cats

### ISSUE THREAD

**Issue by joserobjr** [MyEssentials/MyTown2#399]
If I tame a horse inside my city, than I mount on it and ride to an other city, than if I dismount I won't be able to mount on my own horse.

The same thing affects tamed wolfs and cats, we cant make them sit/stand up while we are inside an other city, (but this is better than the horse)

**Comment by krwminer** [comment]
Very good feedback, thanks, I will look into it.

**Comment by krwminer** [comment]
I can fix Cats and Dogs without too much problem. Horses are a bit more of an issue. They do not have an owner. Which means if I open them up then everyone can ride them.

**Comment by joserobjr** [comment]
The horse entity stores the owner on watchable object 21 as String and refers to the player UUID. It can be read by the public method `func_152119_ch()` and it also writes the OwnerUUID to the NBTTags:
![image](https://cloud.githubusercontent.com/assets/3679022/11304250/f00e6932-8f85-11e5-8099-c64d3a8eebb9.png)

Wolfs and cats extends EntityTameable and the Owner UUID is stored at watchable object 17 and can be read by the public method `func_152113_b()`:
![image](https://cloud.githubusercontent.com/assets/3679022/11304349/6767918e-8f86-11e5-85a4-91b66cf5e55c.png)

**Comment by krwminer** [comment]
Thanks. I missed that last night when I took a quick look.

**Comment by krwminer** [comment]
Fixed in dev build #305 and the latest Minecraft.json protection file.
