### ISSUE TITLE
Sell sign doesn't work for players with long name after the server reboots

### ISSUE THREAD

**Issue by joserobjr** [MyEssentials/MyTown2#401]
If a mayor is named 1234567890123456 (16 chars) and creates a sell sign, it will work while the chunk is loaded, but if we save and reboot the server (save-all; stop) the sign will no longer work because the player name will be trimmed.

I didn't test yet but I believe that it won't work if the player changes the name too which is no a big problem because the players can change the nick only once a month by mojang (although I do allow players to change their names locally instantly manipulating the login process with my BungeeCord plugin)

**Comment by joserobjr** [comment]
This problem is happening because the `TileEntitySign.readFromNBT(NBTTagCompound)` method does a `substring(0,15)` on big lines after reading the Text# key from the NBT tag compound.

Maybe we could create a custom TileEntity that extends TileEntitySign to add some custom NBT data to store information about the sell sign instead of the sign lines, this way changing the translations wouldn't break the sign and we could store the player UUID instead of the name...

**Comment by AfterWind** [comment]
We are aware of this problem. (Props for finding it out though)
The solution you are suggesting will not work simply because MyTown2 is a server-side only mod and I don't think the client will be happy about that ...

I already prepared MyEssentials-Core to have all the signs saved in the database so that we don't have such issues. I just haven't got around to making the changes in MyTown2 yet.

**Comment by joserobjr** [comment]
Actually it won't cause any issue to the clients because it will interpret it as a normal sign, database will only add extra complexibility and can become a problem when there are too many signs being used at once.

I made a simple example mod to show how a custom TileEntity can store the custom NBT Tag, I tested it and it caused no problem on a client running pure forge.

The example can be accessed in this link:
https://github.com/joserobjr/Example-Clickable-Sign/blob/master/src/main/java/com/example/examplemod/ExampleMod.java

I also released a compiled jar that only requires forge on the server:
https://github.com/joserobjr/Example-Clickable-Sign/releases

The example stores the arguments used after the /tool command in the ItemStack using NBT Data, then when the player right click a block it places a sign with a custom TileEntity transferring the args from the tool to the custom tile.

**Comment by joserobjr** [comment]
If you still don't like the custom `TileEntity` solution, we could instead use a class transformer to add a custom NBT data to the `TileEntitySign`, this way we won't need to register anything, the NBT tag will be stored alongside with the sign lines on the original sign's entity, will be ignored by the client and if we remove the MyTown mod the sign will still display the lines and will loos only the custom data.

Here's the example mod changed to attach the data to a normal TileEntitySign:
https://github.com/joserobjr/Example-Clickable-Sign/tree/coremod-with-nbt/src/main/java/com/example/examplemod

I also release a compiled version of this new example:
https://github.com/joserobjr/Example-Clickable-Sign/releases

This example uses ASM to modify the class when it's loading and will not conflict with other mods, it's very light-weight and doesn't need the complexity of SQL queries nor iteration over big maps or lists.

**Comment by krwminer** [comment]
I like your second option, but will wait for feedback from AfterWind. What ever we choose I want to make it so it will work without forcing existing signs to have to be redone.

Thanks!

**Comment by krwminer** [comment]
Your sign-optimization branch looks like the best solution for this so far. When it is ready, please submit a PR for this.

Thanks again for all the help! :)

**Comment by krwminer** [comment]
@joserobjr we really appreciate your help on MT2. If possible, we would like to talk to you. Could you get on the MT2 IRC at some point. AfterWind or I would like to send a PM to you.
