### ISSUE TITLE
adminTowns

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#403]
Something that have been annoying me the last couple of updates is that when i make a admin Town for example a spawn i need to add extra blocks to it, is that intended or a bug?

the command i use is /ta claim Spawn 15

Before i never needed to add extra blocks to a admin town to claim.

maybe the radius is bugged, cause claiming a chunk with only /ta claim Spawn works without adding extra blocks.

**Comment by AfterWind** [comment]
Ah, probably yes, just the part of the command that uses the radius.

**Comment by AfterWind** [comment]
Fixed
