### ISSUE TITLE
Can't cancel a tool process without reconnecting

### ISSUE THREAD

**Issue by joserobjr** [MyEssentials/MyTown2#406]
Tested on commit 7dde68cc60c42a998bce70fe83c6b653b6d31068

Steps to produce:
- `/t new example`- Create a town
- Place down a chest
- `/t perm whitelist` - Attempt to whitelist the chest, it will fail as described on #404
- `/t plot new plot1` - Attempt to create a new plot, an error message will be displayed saying that you already have a tool.
- Throw the whitelister tool away
- `/t plot new plot1` - Attempt to create a new plot again, the same error message will be displayed although you don't have the tool anymore
- Disconnect and reconnect
- `/t plot new plot1` - Create a new plot
- `/t plot new plot2` - Attempt to create a new plot, an error message will be displayed saying that you can't own more than one plot (as described on #405)
- Disconnect and reconnect -  This is the only way I found to actually stop a tool procedure.

**Comment by AfterWind** [comment]
Fixed
