### ISSUE TITLE
Server Crash, Unknown Cause

### ISSUE THREAD

**Issue by 0zlw** [MyEssentials/MyTown2#409]
Server crash on Regrowth. Unable to obtain anything from players when asking them what they were doing. Feel free to close.

http://pastebin.com/02zeygS0

**Comment by AfterWind** [comment]
Yeah, probably related to our mods.

**Comment by krwminer** [comment]
The only way I see this crash happening is if the EntityPlayerMP object's playerNetServerHandler got set to null. My guess would be someone got disconnected before the visuals had a chance to send the update packets. Was there a player disconnect message before this crash?

**Comment by AfterWind** [comment]
Probably we can simply make a check for that since we're doing the updates on any/each tick.

**Comment by krwminer** [comment]
Or should we put a try/catch around the sending of the network packets?
