### ISSUE TITLE
[Minor] Free sign after purchasing a lot

### ISSUE THREAD

**Issue by joserobjr** [MyEssentials/MyTown2#413]
Steps to reproduce:
- Create a town
- Create a plot
- /t plot sell 10 - Create a sell sign directly on the floor
- /t plot sell 10 - Create an other sell sign but this time it must be attached to the first sell sign
- Purchase the plot with an other player by right click on the sign that is directly on the floor, the attached sell sign will drop.

**Comment by AfterWind** [comment]
Fixed, since there only can be one Sell Sign in a plot at a time.
