### ISSUE TITLE
Breaking: Updating to latest versions crashes server

### ISSUE THREAD

**Issue by 0zlw** [MyEssentials/MyTown2#417]
http://pastebin.com/ZD4VqRtf

Updating from the following to the following on FTB VanillaPlus v1.0.0

Versions:
MEC: 95 -> 99
MyPermissions: 46 -> 47
MT2: 301 -> 312

**Comment by 0zlw** [comment]
The following update was successful:

Versions:
MEC: 95 -> 99
MyPermissions: 46 -> 47
MT2: 301 -> 311

**Comment by krwminer** [comment]
The path for the class transformer for signs was wrong. I think MEC #100 should fix it. Reopen if you still have problems.

**Comment by joserobjr** [comment]
My fault, I forgot to update a reference on this commit https://github.com/MyEssentials/MyEssentials-Core/commit/f448a4195d7220f264ee9c23aa7cfb1c1f521931 MEC build 100 should really fix it
