### ISSUE TITLE
Unable to use filebased localization

### ISSUE THREAD

**Issue by 0zlw** [MyEssentials/MyTown2#419]
Someone in the MyTown IRC reported that he had to resort to editing the jar to implement his localizations. I tried to get localizations working via file on vanillaP to no avail.

Config setting: S:localization=en_US
File location: vanillaP/config/MyTown/localization/en_US.lang

I tried editing the localization for the /t spawn command and tested in game without success.

**Comment by joserobjr** [comment]
I noticed this before, I don't know if it's intended but it'll work if you place it directly on config/MyTown

**Comment by merksk8** [comment]
I wanted to post same bug, but i saw this post. 
The error is that MyTown only read the localization files INSIDE THE JAR, if you want to edit the files, you have to open the jar with winrar and edit the en_US.lang or copy it and save it with other name and change it in the config file. I hope this helps :)

**Comment by 0zlw** [comment]
@merksk8 I think you were the inspiration for this bug report. Have you tried what joserobjr suggested and put the localisation file in the MyTown config folder, instead of the localisation folder.

**Comment by merksk8** [comment]
@0zlw oh first of all sorry then.
I tried when i have the problem but was older versions, I will try in the last one that i have installed, but if worked for joserobjr is that works.
Sorry again, i just wanted to help a bit!

**Comment by 0zlw** [comment]
Nothing to be sorry about @merksk8. I agree, it's something that should probably be fixed, otherwise it needs to be clarified in the config how to use localisations.
