### ISSUE TITLE
TPS problem with MT2 

### ISSUE THREAD

**Issue by MineMine** [MyEssentials/MyTown2#421]
first, sorry for my bad english :D 

I've been experiencing some Low TPS problem with MT2

This is my sampling data with warmroast 

![image](https://cloud.githubusercontent.com/assets/6129171/11457659/0eaee3bc-96f2-11e5-9449-4b2343e5eded.png)

**Comment by MineMine** [comment]
PS. I'm using Latest Kcauldron with Infitech 2 Mod pack

**Comment by legobear154** [comment]
After doing a bit of investigation, it appears KCauldron changes some fundamental parts of Minecraft that we use and their changes combined with how we do some things seem to have caused the low TPS. We are looking into ways to help avoid this problem, but we are not sure just yet.

**Comment by legobear154** [comment]
If you could try out the newest build (https://ci.mineguild.net/job/MyTown2/315/) it should improve the TPS quite a bit. If you don't see an improvement (or it's a really small improvement) please reopen this issue and let us know :)

**Comment by MineMine** [comment]
Oh god Thanks for fast response!

**Comment by MineMine** [comment]
It works like charm :D 
Thanks again!
