### ISSUE TITLE
Townlist too Long

### ISSUE THREAD

**Issue by 0zlw** [MyEssentials/MyTown2#422]
On servers with a large number of towns, the town list is too long to see all the towns.

Suggestions:
- Use pages (preferred)
- More than one town to a line

**Comment by AfterWind** [comment]
Pfft you kids nowadays with the huge amount of players on your servers.
Back in my day one town was ALL we needed.

**Comment by 0zlw** [comment]
Actually, in my day we didn't need no protections.

**Comment by AfterWind** [comment]
Fixed
