### ISSUE TITLE
Mob Entry flag

### ISSUE THREAD

**Issue by Flenix** [MyEssentials/MyTown2#423]
As suggested on GitHub, it'd be nice if the mob spawn flag simply prevented SPAWNING and mobs could still walk into town if it's not fortified enough. A second mob entry flag could then kill them off as they enter. This would be very useful for harder servers to make sure players defend their towns well.

**Comment by krwminer** [comment]
Should this be a MyTown.cfg setting that effects the whole server?

**Comment by Flenix** [comment]
Probably, yes. Personally I was going to just force the flag, but that's probably a better idea.

Date: Thu, 3 Dec 2015 10:15:54 -0800
