### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by Mystyfy** [MyEssentials/MyTown2#425]
http://pastebin.com/7Tnffz3H

keep receiving this crash report of Name and ID cannot both be blank...im fairly new to minecraft server setup but im figuring it out...this particular issue is one i still cant seem to figure out, ive attempted numerous versions, config setups, etc and cant seem to rid my server of this crash

my apologies if its not related to mytown2 but i dont see it being anything else...the wolf ticking event has me confused on what exactly is going on...ive been able to figure out every glitch, crash, etc with multiple mods and server setups so far but this one has me stumped...appreciate any help

**Comment by Mystyfy** [comment]
bah, mod list was left off at end...the following mytown versions are being used: MyEssentials Core 1.16r universal, MyPermissions 42-dev, Mytown 0.3.2b...mods are only server side atm

**Comment by joserobjr** [comment]
Thank for informing, the crash is coming from MyTowns2. I didn't see this happening on vanilla entities yet but I had this same problem when I was working on a branch that protects vehicles from MCHeli and Vehicular Movement mods, a similar issue was happening on vehicles that had an empty string on the owner field.

On your case it could be the Minecraft.json file on your protections directory, if it's not outdated then you probably have an wolf with an empty string on the owner field.

I'm going to send a pull request with this commit cherry-picked to the master branch: https://github.com/joserobjr/MyTown2/commit/846cdab7a9a41eadb18f61ceac2425e5d2ec4f3c

If it get accepted you can get the latest development build from https://ci.mineguild.net/job/MyTown2/ , just remember to create backups before using it, also note that you might have problems if you try to downgrade the dev build to 0.3.2b without backups.

**Comment by Mystyfy** [comment]
{
      "class": "net.minecraft.entity.passive.EntityWolf",
      "type": "entity",
      "actions": [ "PVP", "PROTECT" ],
      "flags": "PVE",
      "owner": [
        {
          "element": "func_152113_b",
          "type": "METHOD"
        }
      ]
    },

That is my current minecraft.json with the wolf...any quick fix change you think i could make to it to prevent the crash?? i can be patient with the build if needed, just curious if dropping the PVP action might be the issue - compairing it to other animals seems to make sense even though i havent looked at the java code behind it
