### ISSUE TITLE
Hungry Nodes can destroy protected blocks

### ISSUE THREAD

**Issue by joserobjr** [MyEssentials/MyTown2#429]
A player on my server found that a Thaumcraft's Hungry Node can destroy blocks on town blocks with `modify` and `fakers` set to `false`.
![2015-12-11_17 47 24](https://cloud.githubusercontent.com/assets/3679022/11755207/787713f0-a02f-11e5-81fc-f0fe2ed63fff.png)
(Hungry Node eating blocks on a town)

**Comment by 0zlw** [comment]
Following discussion in IRC, I had someone test trying to release a hungry node in a jar within a 30 block radius of a town, and it appeared that MyTown was protecting against this.

**Comment by krwminer** [comment]
Creating Town protection for a Hungry Node could lead to abuse as one could find a Hungry Node and claim the chunk, then use the block protection to more easily capture it.

**Comment by AfterWind** [comment]
Protect against placing a node in a jar near the town instead. Should fix the issue.

**Comment by krwminer** [comment]
It is already protected against as you need to use a wand in order to release a node from a jar and the range for a wand use is around 30 blocks right now.

**Comment by krwminer** [comment]
Your thoughts Jose? I found where I could patch this and possibly make a config file entry to enable the protection, but before I go through that effort I want to discuss this and make sure we are all happy with the solution.

**Comment by joserobjr** [comment]
Sorry for the delay on my response. I agree that a town protection could lead to abuse, I didn't know that it required wand to release the node, I saw that node eating blocks under that town and I thought it wasn't protected.

The way it is now is fine.

Players on my servers are actually complaining that they can't use wands in plots because the range hits town protection, I'm planning to protect wands injecting protection codes on Thaumcraft in future.

I'm going to close this because it isn't an actual issue on MT2 as the protection works, reopen it if you think that it should remain open :P

**Comment by krwminer** [comment]
I have started work on closing the big window for Thaumcraft. The IMPACT event will help, we need to go back change the range for the thrown entities to be only the are of affect when the entity hits.

I agree, that we still might need some more ASM hacks to bring the range in so people could use the wands in a plot.

**Comment by Eufranio** [comment]
@krwminer , do you have news in this? Placing nodes is not the only way to put them in/near a tonw. Nodes can also be teleported with other mods, like Blood Magic teleporter, can enter in the chunk with relocators, be placed with portal guns...
