### ISSUE TITLE
Blazes can burn my house

### ISSUE THREAD

**Issue by Esctogrillo** [MyEssentials/MyTown2#430]
Blazes (and others mobs from others mods) can burn protected houses with fireballs.

**Comment by krwminer** [comment]
Are you using the latest mods and protection files?

**Comment by Esctogrillo** [comment]
Yes.

**Comment by krwminer** [comment]
Do you allow MODIFY for outsiders in the Town?

What server are you running?

**Comment by Esctogrillo** [comment]
The Modify permission is false.
I'm running a KCauldron server, with forge 1492.

**Comment by krwminer** [comment]
The support should be in there for it. I will try and double check that version of KCauldron.

**Comment by krwminer** [comment]
From your description, it sounds like two things are not working. Firespread protection in a Town and Fireball Impact protection.

I assume the "fireSpreadInTowns" flag is false in your MyTown.cfg, right?

**Comment by krwminer** [comment]
KCauldron-1.7.10-1492.164.zip?

**Comment by Esctogrillo** [comment]
Is KCauldron-1.7.10-1492.152.zip
MyTown.cfg does not have "fireSpreadInTowns".

**Comment by krwminer** [comment]
It should be there if you are using: MyTown2-1.7.10-0.4.0b.jar

Hmm... I will check when I get home from work.

**Comment by Esctogrillo** [comment]
Ow, I'm using 0.3.2, sorry! :P 
I will update the mod and try again.

**Comment by krwminer** [comment]
Make sure you use all the versions I listed above. Let me know how it goes. :)

**Comment by Esctogrillo** [comment]
Can I download the latest mods from jenkins? (Mytown, Mypermissions and Myessentials).

**Comment by krwminer** [comment]
Yes. They should be fine.

**Comment by Esctogrillo** [comment]
Ok, I tested and my player houses are protected now :)
Thank you! :+1:
