### ISSUE TITLE
Arcane Bore can bypass protection

### ISSUE THREAD

**Issue by Esctogrillo** [MyEssentials/MyTown2#431]
The Arcane Bore (Thaumcraft) can break protected blocks.
To reproduce, just mount a Bore and break your friend house.

**Comment by 0zlw** [comment]
Issue confirmed and reproducible.

**Comment by krwminer** [comment]
Horrible Thaumcraft TE based mess. You might be able to prevent placement of the Arcane Base but the range has to be 64 blocks. :/

**Comment by Esctogrillo** [comment]
No problems, my server has a mine world.

**Comment by Esctogrillo** [comment]
I'm trying to put this on Thaumcraft.json:
    {
      "class": "thaumcraft.common.blocks.BlockWoodenDevice",
      "type": "block",
      "actions": "RIGHT_CLICK",
      "meta": -1,
      "flags": "ACCESS",
      "range": 64
    },
And is not working. It's wrong?

**Comment by krwminer** [comment]
Try using:
{
      "class": "thaumcraft.common.blocks.BlockWoodenDeviceItem",
      "type": "item",
      "actions": "RIGHT_CLICK_BLOCK",
      "isAdjacent": false,
      "meta": -1,
      "flags": "MODIFY",
      "range": 64
}

I am not setup to test at the moment, but give it a try and let me know. You have to prevent it before placement as an item in your hand.

**Comment by Esctogrillo** [comment]
Nope, don't works.

**Comment by krwminer** [comment]
I will try and figure it out.

**Comment by krwminer** [comment]
It seems to work for me. Please download the latest Thaumcraft.json protection file and try it out.
