### ISSUE TITLE
Failed to send chat message

### ISSUE THREAD

**Issue by Esctogrillo** [MyEssentials/MyTown2#432]
Sometimes, when a player enters and leaves town, the message not show and a message appears on the console: Failed to send chat message! Message: Welcome back.... (Do you know what).
And, sometimes too, this error is when a player create a town, with the message: 
[Server thread/INFO]: Murralia issued server command: /town new bones
[Server thread/ERROR]: Linked Resident Murralia (1260793e-c13a-3320-91af-ba8e2af2aa0a) with Town bones Rank Mayor

**Comment by AfterWind** [comment]
MyTown fails to send a message because the player just joined and the player Entity did not get fully created probably.

The second "error" is just a message that got sent as an error instead of debug. Nothing to worry about. We'll fix it.

**Comment by Esctogrillo** [comment]
The message of the daily payment of the town is not showing up and is flooding the console with this error message.

**Comment by Esctogrillo** [comment]
Sorry, I closed the issue -,-

**Comment by legobear154** [comment]
Should be fixed by MyEssentials-Core PR#18. Please reopen if necessary.
