### ISSUE TITLE
Tinker's Construct Lumberaxe when tree is half claimed causes Server crash

### ISSUE THREAD

**Issue by FaMatrix** [MyEssentials/MyTown2#434]
If you try to cut the tree down with Lumberaxe while tree is in between claimed and wilderness, it'll causes server to crash. But if whole of tree is inside or outside of mytown2 protection, it won't crash.

[Link to Crashreport] (http://pastebin.com/MHZu3MaY)

After you restart server, only few blocks disappeared, but the rest still holds upright, 
![Tree's surviving] (http://puu.sh/m8Zzw/00c92c120b.jpg)

**Comment by 0zlw** [comment]
I should introduce @FaMatrix to you people. He's one of our staff members. :P

**Comment by krwminer** [comment]
Sorry guys, this has nothing to do with MT2. The code for LumberAxe is massively recursive if it encounters any protection. Personally I think the code is wrong, it should just do nothing if it fails a block break. I might suggest a PR to them later if I have the time.
