### ISSUE TITLE
issue with SQL and fakePlayer when adding blocks to player

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#446]
Im getting a console error when adding extra block to a resident

the command "/t res blocks extra add fiveeyz 1" seems to work and actually gives a extra block according to /t info https://gyazo.com/85b65802d59f94163cc8d02c5bc4511b

but i see this error in console when i run it:
http://pastebin.com/raw/UQ0Rr2gB

believe it started when "fakeplayer" got added to towns.

using:
MyEssentials-Core-1.7.10-111-dev
MyPermissions-1.7.10-49-dev
MyTown2-1.7.10-333-dev

**Comment by krwminer** [comment]
I think @legobear154 might be better to answer this, but my guess is that for some reason the schema update did not take place that adds "fakePlayer" to Residents in the DB.

**Comment by FiveEYZ** [comment]
just tried the latest build

used command:
/ta res blocks extra remove fiveeyz 1
a claim gets removed from me but i get this in console
http://pastebin.com/raw/sJEtW7B8

**Comment by legobear154** [comment]
Ignore that, meant to mark issue #466 as fixed instead >.<
