### ISSUE TITLE
Thaumcraft protection

### ISSUE THREAD

**Issue by Esctogrillo** [MyEssentials/MyTown2#448]
With your last addiction on Thaumcraft protections I cannot put a Arcane Bore near a other player town, It's ok.
But the banners and Silver Wood have the same class and, obvious, the same restriction.
I am unable to put a banner or silver wood (plank) near 64 blocks a other players town.

**Comment by krwminer** [comment]
Fixed with latest MT2 and Thaumcraft.json.
