### ISSUE TITLE
Crash with Lumber Axe

### ISSUE THREAD

**Issue by Esctogrillo** [MyEssentials/MyTown2#449]
When a player try to break a protected tree with Lumber Axe (Tinker's Construct) the server crashes.
Crash report: http://pastebin.com/TR4LvErU

**Comment by krwminer** [comment]
This has nothing to do with MT2. The old TiC Lumber Axe code is massively recursive code and gets even more recursive when it hits protected blocks. It looks like the master branch of TiC has a much better rewrite of the LumberAxe code.

**Comment by Esctogrillo** [comment]
You can add a range protection to Lumber Axe and avoid this crash (I thing).

**Comment by krwminer** [comment]
It might help since you are trying to overcome a bug in the TiC code, but since he uses recursion there is not limit to the range. Have you submitted an issue against TiC?
