### ISSUE TITLE
[MyTown2] Issues with Tekkit Legends

### ISSUE THREAD

**Issue by FaresSpeed** [MyEssentials/MyTown2#451]
hi,
I'm having plenty of problems with mytown2 in tekkit legends
apparently, the protection file of some mods are either missing or doesn't work perfectly
I have ProjectE installed in the protection file and it doesn't protect Energy condenser and the mks machines as it's accessible
the quarry doesn't work in the wild or inside the town and I have no idea why it doesn't work
also for some tools in ProjectE, some can cause real damage and some spam mytown such as the red and dark pickaxes as it spam mytown2 and then crash it, and red morningstar "it bypass mytown2 like it's nothing"
also for IC2, it doesn't work with ICC "the developers modify the name only"
it's the same mod, but only diff names
that's all what I know so far, hope you can help

**Comment by FaresSpeed** [comment]
I solved the quarry problem, it's usually AuthMe for blocking fake players
I made sure to read the protection file full in details
you are missing some lines for this modpack only
please try to make them

**Comment by AfterWind** [comment]
Since this is an issue with the protections please move it to: https://github.com/MyEssentials/MyTown2-Protections/issues

Sorry for not replying to your issue for so long, been incredibly busy with uni work and just now got around to work on the project.
