### ISSUE TITLE
Bug - MyTown2 Database stops working and prevents server from starting

### ISSUE THREAD

**Issue by 0zlw** [MyEssentials/MyTown2#454]
On our AS2 server (possibly has occurred once on a different server) every so often, we get this error on start up: http://pastebin.com/23WTqLnw which prevents the server from starting. This means we have to roll the database back to a backup.

**Comment by AfterWind** [comment]
I think what happens is that a town got deleted at some point but the ranks were left in the database and now MyTown is loading Ranks from towns that no longer exist thus throwing an NPE. 

If you don't have too many towns you can go in the Ranks table of the database and remove all the ranks from towns that don't actually exist.

**Comment by dezil** [comment]
tried this got very messy very fast
