### ISSUE TITLE
MyTown2 Not working

### ISSUE THREAD

**Issue by Renguko** [MyEssentials/MyTown2#455]
I downloaded the "Tekkit Legends Server" from the technic site and ran the server, then I closed it after all the stuff was done and popped the latest versions of MyTown2, MyEssentials-Core, and MyPermissions. I then launched the server, and it crashed. The crash report is as follows.
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2/16/16 11:58 AM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mypermissions/config/Config
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: mypermissions/config/Config
	at mypermissions.MyPermissions.preInit(MyPermissions.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 5 more
Caused by: java.lang.ClassNotFoundException: mypermissions.config.Config
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 32 more
Caused by: java.lang.NoClassDefFoundError: myessentials/config/api/ConfigTemplate
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 34 more
Caused by: java.lang.ClassNotFoundException: myessentials.config.api.ConfigTemplate
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1006829840 bytes (960 MB) / 1401421824 bytes (1336 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -Xmx2G -Xms1G -XX:MaxPermSize=128m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (TekkitLegends.jar) 
	UCH	Forge{10.13.4.1492} [Minecraft Forge] (TekkitLegends.jar) 
	UCH	CodeChickenCore{1.0.6.41} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.4.102} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.102-universal.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	mcdiscord{2.0.0} [MC Discord] (minecraft.jar) 
	UCH	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCH	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCH	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303 (1).jar) 
	UCH	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
	UCH	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
	UCH	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
	UCH	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
	UCH	ComputerCraft{1.74} [ComputerCraft] (ComputerCraftPlusComputerCraftEdu1.74.jar) 
	UCH	IC2{2.2.999} [Industrial Craft Classic] (IC2.Classic.Version.1.1.3.5.jar) 
	UCH	Forestry{3.6.11.2} [Forestry for Minecraft] (forestry_1.7.10-3.6.11.2.jar) 
	UCH	LogisticsPipes{0.9.3.70} [Logistics Pipes] (logisticspipes-0.9.3.70.jar) 
	UCH	additionalpipes{4.7.0} [Additional Pipes] (additionalpipes-4.7.0.jar) 
	UCH	asielib{0.4.4} [asielib] (AsieLib-1.7.10-0.4.4.jar) 
	UCH	bdlib{1.9.3.107} [BD Lib] (bdlib-1.9.3.107-mc1.7.10.jar) 
	UCH	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCH	qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.114-universal.jar) 
	UCH	bluepower{0.2.962} [Blue Power] (BluePower-1.7.10-0.2.962-universal.jar) 
	UCH	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
	UCH	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
	UCH	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
	UCH	BuildCraft|Compat{7.1.3} [BuildCraft Compat] (buildcraft-compat-7.1.3.jar) 
	UCH	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCH	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCH	ComputerCraftEdu{1.74} [ComputerCraftEdu] (ComputerCraftPlusComputerCraftEdu1.74.jar) 
	UCH	Railcraft{9.7.0.0} [Railcraft] (Railcraft_1.7.10-9.7.0.0.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	computronics{1.5.7} [Computronics] (Computronics-1.7.10-1.5.7.jar) 
	UCH	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCH	eng_toolbox{1.2.3.0} [Engineer's Toolbox] (EngineersToolbox-1.2.3.0-BETA.jar) 
	UCH	ForgeMultipart{1.2.0.344} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	UCH	McMultipart{1.2.0.344} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	UCH	gendustry{1.6.1.126} [GenDustry] (gendustry-1.6.1.126-mc1.7.10.jar) 
	UCH	IC2-Classic-Spmod{0.0.0.0} [IC2 Classic Detection Helper] (IC2.Classic.Version.1.1.3.5.jar) 
	UCH	IC2NuclearControl{2.3.3a-Exist} [Nuclear Control 2] (IC2NuclearControl-2.3.3a-Exist.jar) 
	UCH	ImmibisCore{59.1.2} [Immibis Core] (immibis-core-59.1.2.jar) 
	UCH	ImmibisPeripherals{59.0.2} [Immibis's Peripherals] (immibis-peripherals-59.0.2.jar) 
	UCH	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) 
	UCH	IronChest{6.0.60.741} [Iron Chest] (Ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCH	itlt{0.0.8} [It's the little things] (itlt-1.7.10-0.0.8.jar) 
	UCH	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCH	MapWriter{2.1.8} [MapWriter] (MapWriter-1.7.10-2.1.9.jar) 
	UCH	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10.jar) 
	UCH	modtweaker2{0.9.4} [Mod Tweaker 2] (ModTweaker2-0.9.4.jar) 
	UCH	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
	UCH	powersuits{0.11.0.293} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.293.jar) 
	UCH	MyEssentials-Core{1.7.10-v1.17r} [MyEssentials-Core] (MyEssentials-Core-1.7.10-v1.17r-universal.jar) 
	UCE	MyPermissions{1.7.10-0000r} [MyPermissions] (MyPermissions-1.7.10-51-dev.jar) 
	UCE	MyTown2{1.7.10-v0.4.0b} [MyTown 2] (MyTown2-1.7.10-v0.4.0b.jar) 
	UCH	NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	neiintegration{1.0.12} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.12.jar) 
	UCH	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCH	OCS{1.7.5} [OpenCCSensors] (openccsensors-1.7.5.jar) 
	UCH	planetguyLib{1.9} [planetguyLib] (PlanetguyLib-1.9.1.jar) 
	UCH	PowerConverters3{1.7.10-2.11} [Power Converters 3] (PowerConverters-1.7.10-2.11.jar) 
	UCH	ProjectE{1.7.10-PE1.9.3} [ProjectE] (ProjectE-1.7.10-PE1.9.3h.jar) 
	UCH	quiverchevsky{b100} [QuiverBow] (QuiverBow_1.7.10_b100.zip) 
	UCH	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCH	JAKJ_RedstoneInMotion{2.8.8} [Remain In Motion] (RemainInMotion-2.8.8.jar) 
	UCH	SolarFlux{1.7.10-0.8b} [Solar Flux] (SolarFlux-1.7.10-0.8b.jar) 
	UCH	Tubestuff{59.0.4} [Tubestuff] (tubestuff-59.0.4.jar) 
	UCH	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCH	zettaindustries{1.1} [Zetta Industries] (zettaindustries-1.1-105.jar) 
	UCH	aobd{2.8.4} [Another One Bites The Dust] (AOBD-2.8.4.jar) 
	UCH	ForgeMicroblock{1.2.0.344} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	CoFHCore: -[1.7.10]3.0.3-303
	NetherOres: -[1.7.10]2.3.0-12
	RedstoneArsenal: -[1.7.10]1.1.1-89
	List of loaded APIs: 
		* apAPI (2) from additionalpipes-4.7.0.jar
		* asielibAPI (1.1) from AsieLib-1.7.10-0.4.4.jar
		* asielibAPI|chat (1.0) from AsieLib-1.7.10-0.4.4.jar
		* asielibAPI|tile (1.0) from AsieLib-1.7.10-0.4.4.jar
		* asielibAPI|tool (1.1) from AsieLib-1.7.10-0.4.4.jar
		* bluepowerAPI (1.0) from BluePower-1.7.10-0.2.962-universal.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|blueprints (1.2) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|core (1.4) from Railcraft_1.7.10-9.7.0.0.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|facades (1.1) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|items (1.1) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|library (1.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.14.jar
		* BuildCraftAPI|recipes (2.1) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|tiles (1.1) from Railcraft_1.7.10-9.7.0.0.jar
		* BuildCraftAPI|tools (1.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.1.14.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
		* CoFHAPI (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
		* CoFHAPI|block (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHAPI|core (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from forestry_1.7.10-3.6.11.2.jar
		* CoFHAPI|fluid (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHAPI|inventory (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHAPI|item (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHAPI|modhelpers (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
		* CoFHAPI|tileentity (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHAPI|transport (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHAPI|world (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|audio (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|gui (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|gui|container (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|inventory (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|render|particle (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|util (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|util|helpers (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|util|position (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303 (1).jar
		* ComputerCraft|API (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
		* ComputerCraft|API|FileSystem (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
		* ComputerCraft|API|Lua (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
		* ComputerCraft|API|Media (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
		* ComputerCraft|API|Peripheral (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
		* ComputerCraft|API|Permissions (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
		* ComputerCraft|API|Redstone (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
		* ComputerCraft|API|Turtle (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
		* computronicsAPI (1.3) from Computronics-1.7.10-1.5.7.jar
		* computronicsAPI|chat (1.3) from Computronics-1.7.10-1.5.7.jar
		* computronicsAPI|multiperipheral (1.1) from Computronics-1.7.10-1.5.7.jar
		* computronicsAPI|tape (1.0) from Computronics-1.7.10-1.5.7.jar
		* ForestryAPI|apiculture (3.5.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|arboriculture (2.3.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|circuits (2.0.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|core (3.2.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|farming (1.1.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|genetics (3.3.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|lepidopterology (1.1) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|recipes (3.1.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-3.6.11.2.jar
		* ForestryAPI|world (1.1.0) from forestry_1.7.10-3.6.11.2.jar
		* gendustryAPI (2.2.0) from gendustry-1.6.1.126-mc1.7.10.jar
		* IC2API (1.0) from IC2.Classic.Version.1.1.3.5.jar
		* MyTown|API (1.0) from MyTown2-1.7.10-v0.4.0b.jar
		* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.3.3a-Exist.jar
		* ProjectEAPI (7) from ProjectE-1.7.10-PE1.9.3h.jar
		* RailcraftAPI|bore (1.0.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|carts (1.3.1) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|core (1.3.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|electricity (1.6.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|events (1.0.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|fuel (1.0.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.7.0.0.jar
		* RailcraftAPI|signals (1.3.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.7.0.0.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.7.0.0.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by AfterWind** [comment]
https://ci.mineguild.net/job/MyPermissions/
Download no. 49 from there not 51.
