### ISSUE TITLE
Clockwork Phase Mod - No Protection

### ISSUE THREAD

**Issue by HalestormXV** [MyEssentials/MyTown2#458]
Hey there, this isn't really a bug I guess one could call it an enhancement. It seems the Clockwork Phases mod is not protected. I have no idea how you generate these protection files, but one for Clockwork Phase would be awesome. Or even a link on how to create a Protection file might be beneficial and I can attempt to create one.

**Comment by AfterWind** [comment]
[https://github.com/MyEssentials/MyTown2/wiki/Making-Protections](Here's) a link to the wiki page for making protections.

Also, protection issues should always go [https://github.com/MyEssentials/MyTown2-Protections/issues](here)
