### ISSUE TITLE
Portal Gun / Gravity Gun Bypass

### ISSUE THREAD

**Issue by cjm721** [MyEssentials/MyTown2#459]
The pickup code for both of these is not able to be stopped.

The Portal Gun uses a custom key.
The Gravity Gun even with right click disabled still works (It says you don't have permission and does it anyways)

**Comment by cjm721** [comment]
Also mentioned in MyTown2 Protections.
[# 79](https://github.com/MyEssentials/MyTown2-Protections/issues/79)

**Comment by AfterWind** [comment]
Closed. Protection related issue.

**Comment by cjm721** [comment]
Protection related issue that cannot be fixed via protection files.
