### ISSUE TITLE
Caught exeption from MyTown2

### ISSUE THREAD

**Issue by CreedTheFreak** [MyEssentials/MyTown2#464]
Hello I seem to have run into an error that I am unable to find a fix for, and it also doesn't leave any crash-report. I have been searching through my forge logs and believe I have found where it's "crashing" or throwing errors from. Here is just the error part of the log I found while searching, http://pastebin.com/PQvpc7qE if you need more of the log let me know. Also I have been searching through my server directories and have found that /databases/MyTown2 does not have a data.db file in it, like the configuration file has as the path name. So Iowa's wondering is the crash because I need a SQL database for it to work? I should also let you know that I am running quite a hefty amount of mods. Thank you for taking the time to read this
~Creed

**Comment by AfterWind** [comment]
Download [this](http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.32/mysql-connector-java-5.1.32.jar), [this](http://central.maven.org/maven2/com/esotericsoftware/reflectasm/reflectasm/1.09/reflectasm-1.09.jar) and [this](https://bitbucket.org/xerial/sqlite-jdbc/downloads/sqlite-jdbc-3.8.5-pre1.jar) and put them in the mods folder. I think MyTown failed to download these automatically so it crashes everytime you start the server up.

**Comment by CreedTheFreak** [comment]
Thank you, it's much appreciated! I will do this when I get home.

**Comment by groveham** [comment]
I was getting a slightly different error, see here: http://pastebin.com/0nP3LiWs

Tried the solution you suggested @AfterWind and it worked. I was creating a new world, on fresh install of a server running a dev version of v3,2 for the Infitech2 modpack, also using: 

MyTown2-1.7.10-0.4.0b.jar
MyEssentials-Core-1.7.10-v1.17r-universal.jar
MyPermissions-1.7.10-49-dev.jar	

Hope that helps :)
