### ISSUE TITLE
Assistants able to demote Mayor

### ISSUE THREAD

**Issue by cjm721** [MyEssentials/MyTown2#466]
Assistants are able to demote the Mayor of their town. The town will then revert to SERVER_ADMIN as the owner.

**Comment by AfterWind** [comment]
What version are you using? I am pretty sure this is not possible on the current version.

**Comment by cjm721** [comment]
Updated issue as found the real cause (Assistants able to demote mayor, and then subsequently kick)

**Comment by legobear154** [comment]
Whoops, marked the wrong issue in the last commit >.< This should be fixed now.
