### ISSUE TITLE
Crash with some protections

### ISSUE THREAD

**Issue by Esctogrillo** [MyEssentials/MyTown2#473]
Using minecraft, Chisel2, Extra Utilities, TConstruct, Thermal Expansion and/or Thaumcraft my server crashes: http://pastebin.com/07JwbM30

This started to happen after I formated my server (and reinstall all the stuff).

**Comment by AfterWind** [comment]
Pretty sure you're missing ReflectASM. Make sure you have all the jar files listed in issue #464 in the mods folder.

**Comment by AfterWind** [comment]
Closed. Duplicate of #464.
