### ISSUE TITLE
Allow Player name usage for add blocks

### ISSUE THREAD

**Issue by JzJad** [MyEssentials/MyTown2#479]
Possible to get /ta blocks extra add {PlayerName} X-Amount
I would like to set up command blocks to take money and give a set amount of blocks to a player's town.

**Comment by AfterWind** [comment]
[Here is the wiki page for that commands](https://github.com/MyEssentials/MyTown2/wiki/Commands#admin-resident-management)

**Comment by JzJad** [comment]
Oh well you rock thanks I missed it!
