### ISSUE TITLE
Crash with messages (pay upkeep and explosion)

### ISSUE THREAD

**Issue by Esctogrillo** [MyEssentials/MyTown2#481]
Crash on Pay upkeep (every day): http://pastebin.com/xsvQPc18

Crash on explosions message: http://pastebin.com/W2GCC19p

.lang file: http://pastebin.com/Td8Wm0L1

**Comment by legobear154** [comment]
Should be fixed by MyEssentials-Core PR#18. Please reopen if necessary.
