### ISSUE TITLE
Using Groupmanager for permissions

### ISSUE THREAD

**Issue by GabrielGamer66** [MyEssentials/MyTown2#484]
How I do for use Groupmanager for permissions?

(Sorry for my english, I'm brazilian)

**Comment by Eufranio** [comment]
https://github.com/MyEssentials/MyTown2/wiki/Commands
I'm brazillian too xD

**Comment by GabrielGamer66** [comment]
kkkkkkkkk
Eufranio, parece que o Group Manager não reconhece essas permissões. Deu certo com as permissões sem o rank, por exemplo, se era "mytown.cmd.outsider.new", tirando o "outsider." funciona.
Sabe dizer o por que disso?

**Comment by Eufranio** [comment]
http://prntscr.com/bap6ow
Tem skype? Alguns plugins de permissão não aceitam algumas permissões, você tem que configurar isso de acordo com o seu.

**Comment by GabrielGamer66** [comment]
Meu skype é gabrielgamer66br

**Comment by Eufranio** [comment]
Close issue if the problem is fixed.
