### ISSUE TITLE
Configurable max joinable towns

### ISSUE THREAD

**Issue by LorenzoDCC** [MyEssentials/MyTown2#485]
It's a pain the ass, really - I play with a number of friends, and we'd like to share access to our towns but it's impossible since we top the maxtown joinable. Making a huge town is also not a thing because we live far from eachother and even if we didn't there wouldn't be enough claims
An option to tweak this would be nice. If there is, I don't have a clue to where it is or I must be blind without knowing.

**Comment by Esctogrillo** [comment]
Maybe this?
![screenshot_1](https://cloud.githubusercontent.com/assets/14919996/15696744/e9de941e-2789-11e6-8aa7-997dbe94b22b.png)
(MyTown.cfg)

**Comment by AfterWind** [comment]
`/ta add` command bypasses this if need be.

**Comment by LorenzoDCC** [comment]
thank you I'm blind
now I must shout at a certain server admin both me and Escto know~

**Comment by Eufranio** [comment]
NO

**Comment by StoneLegion** [comment]
This is actually incorrect no? Does this not set max creatable towns and joinable?
