### ISSUE TITLE
Max plots config doesn't work

### ISSUE THREAD

**Issue by Eufranio** [MyEssentials/MyTown2#492]
When i try create more than one plot in my town, it say that i can't own more than 1 plot, EVEN if i increase the value in the config.

No logs, no errors, it just tell me "you can't be owner of more than one plot" and doesn't create the plot.

**Comment by AfterWind** [comment]
Value in the config is a default for newly created towns. You should be able to set the maximum amount of plots per player with the command: /t plot limit set <limit>

**Comment by Eufranio** [comment]
Okay, thank you :smile: 
The commands wiki page needs more documentation through

**Comment by AfterWind** [comment]
https://github.com/MyEssentials/MyTown2/wiki/Commands#plot-management
-.-
We're missing documentation for the configs, I'm pretty sure the one for the commands is mostly finished.
