### ISSUE TITLE
When creating a City, Residents can break streets but not plots

### ISSUE THREAD

**Issue by Eufranio** [MyEssentials/MyTown2#495]
I want make a city, i did the plots, everything okay. But residents are able to break the streets (the streets aren't plots, they're inside a town). Would be cool a permission-based modify/access/use nodes, so i would be able to negate these actions for normal residents.

**Comment by AfterWind** [comment]
Try turning on the restrictions flag, I think that is what you want.

**Comment by Eufranio** [comment]
YAYYYYYYYY! Thank you so much!

**Comment by Eufranio** [comment]
After a server restart, the residents will have permission outside the plots, and changing the flag again won't work, the only solution is to re-create the town (and it will bug again later when the server restart again...)
