### ISSUE TITLE
[Suggestion] Configurable commands

### ISSUE THREAD

**Issue by Eufranio** [MyEssentials/MyTown2#496]
Title.

**Comment by AfterWind** [comment]
Elaborate.

**Comment by Eufranio** [comment]
Would be cool a config to replace the normal commands, it will let us be able to translate the commands, like for pt-br:

/town = /cidade
/town new = /cidade criar 
/town claim = /proteger

**Comment by AfterWind** [comment]
Ah, I see. Although the current system doesn't really let us do that easily.

**Comment by Eufranio** [comment]
:/

**Comment by damonmensch** [comment]
May I recommend ForgeEssentials/ForgeEssentials.

It already has alias capabilities, which is exactly what you're looking for.

**Comment by Eufranio** [comment]
I can't use it for a wile, and i know make command alias, i'm just suggesting that it become a native part of MyTown2.

**Comment by AfterWind** [comment]
There is an alias system in place for the commands, I was refering to this: 
/town claim = /proteger
This kind of alias where you merge 2 commands into 1 is not possible. Other than that, it could be done fairly easily.

**Comment by Eufranio** [comment]
Hmmm, true :/

**Comment by Eufranio** [comment]
Fixed using BetterAlias plugin.
