### ISSUE TITLE
[Suggestion] GUI for town/plot permissions

### ISSUE THREAD

**Issue by JasonMcRay** [MyEssentials/MyTown2#5]
If people will have MyTown also on client side, the permissions for plots or towns could be set in some sort of GUI. This will allow people to not derp with /t perm town bla bla bla. And it will also look good.

So instead of "/t perm plot set mobsoff true" all what ppl will need to do is do "/t gui" (or something like that) sellect Mob Spawning (button) and sellect Enable/Disable (button)

**Comment by AfterWind** [comment]
Will get moved to client-side when we have that project started.
