### ISSUE TITLE
Issues with Forge Essentials

### ISSUE THREAD

**Issue by KaneHart** [MyEssentials/MyTown2#524]
I'm having issues with MyTown2 1.7.10 and FE 1.7.10. I'm hoping this is rather a crafting option or feature I must adjust rather then it being a bug.

In mytown2 permissions mod I made sure was set to the $FE config option.

So a MT2 Command:
/t map

By default I get the following error in game not enough permissions and on console if I turn on FE perm debug /p debug I get:
 mytown.cmd = false

So I go ahead and I add  mytown.cmd = true in my perm file or do it by a command with out mytown.cmd.*...

Now if I do /t map with the mytown.cmd node to true I get:
[23:32:12] [Server thread/INFO]: mytown.cmd = true
[23:32:12] [Server thread/INFO]:   zone _SERVER_ group _GUESTS_ for user Kane_Hart
[23:32:12] [Server thread/INFO]: mytown.cmd.outsider.map = true
[23:32:12] [Server thread/INFO]:   permission not set

It also works in game. Great. Now I'm going to set mytown.cmd.outsider.map to false since I don't want it.

So now it's false for the Map yet it's allowing it based on mytown.cmd...... 
[23:33:53] [Server thread/INFO]: mytown.cmd = true
[23:33:53] [Server thread/INFO]:   zone _SERVER_ group _GUESTS_ for user Kane_Hart
[23:33:53] [Server thread/INFO]: mytown.cmd.outsider.map = false
[23:33:53] [Server thread/INFO]:   zone _SERVER_ group _GUESTS_ for user Kane_Hart

So lets try this then.... Lets go back to removing mytown.cmd = true and give the outsider.map true just for test sake and see if I can just see it.....

[23:35:39] [Server thread/INFO]: Successfully reloaded permissions
[23:35:42] [Server thread/INFO]: mytown.cmd = false
[23:35:42] [Server thread/INFO]:   zone _SERVER_ group _GUESTS_ for user Kane_Hart

So pretty much what is happening is mytown.cmd that acts as actually mytown.cmd.* seems to no matter what be required.... If it's enabled with true then everything you attempt to false will break it... I also attempted to create another group that used guest as a sub group and it made 0 difference still. 

So not sure if this a bug with MyTown2 or a bug with FE or just a bad interaction combo or hopefully what I'm wanting to hear is user error....

**Comment by AfterWind** [comment]
So when you set
```
mytown.cmd = true
mytown.cmd.outsider.map = false
```

You still have permissions for `/t map`? Is that the issue?

**Comment by KaneHart** [comment]
@AfterWind Exactly! It's almost like mytown.cmd is a override but without it nothing also works. Kind like feeling like OP Mode (no I'm not an OP when testing nor was even after booting I had deleted the OP file right away).

**Comment by AfterWind** [comment]
From what I recall, this is has been an issue in the past as well. Can't pinpoint anything wrong with MyPermissions so it might be either MyPermissions or ForgeEssentials. 
Try with `mytown.cmd.*` instead?
Otherwise I might do a quick fix if it's very important and if I can solve it and it's not FEs fault.

**Comment by KaneHart** [comment]
Sadly the same issue:
[12:38:23] [Server thread/INFO]: mytown.cmd = true
[12:38:23] [Server thread/INFO]:   zone _SERVER_ group _GUESTS_ for user Kane_Hart
[12:38:23] [Server thread/INFO]: mytown.cmd.outsider.map = false
[12:38:23] [Server thread/INFO]:   zone _SERVER_ group _GUESTS_ for user Kane_Hart


What I can do later tonight make a 100% brand new instance with nothing but FE/MT2 and the 2 jars for it and do more testing. I can upload the entire instance as well if you like to be able to test from it.

I really love to get this to work not many 1.7.10 options I plan on investing a lot into a new server in Jan to start up a brand new GTNH server. It's amazing that pack being updated like every day with new content. In some ways it's why 1.7.10 still is alive in my books.

**Comment by AfterWind** [comment]
Try this version of MyPermissions. It might fix the issue but break other things so test a few more use cases. You might have to add the permission `mytown.cmd.*` instead of `mytown.cmd` to FE.
https://drive.google.com/open?id=1ObiuYLlgS13mHkJDpaixHEGXCX-1PiZ2

**Comment by KaneHart** [comment]
Brilliant it works! <3 Thank you so much. Now we have a decent protection system for 1.7.10 we can use :)
