### ISSUE TITLE
[Suggestion] Flohs requests

### ISSUE THREAD

**Issue by floh22** [MyEssentials/MyTown2#7]
Ok, so i installed mytown on a bteam server and the following mods seem to not be protected, i dont know if you can do anything about it but here is a list:

- Flans mod explosives
- Open blocks block breaker
- Thermal Expansion Terrain Smasher
- Random Things block breaker
- Random Things auto placer
- Random Things Block Mover
- Random Things Entity Mover
- Tinkers' Mechworks Drawbridges

**Comment by AfterWind** [comment]
Moved to the protections repo.
