### ISSUE TITLE
MyTown does not verify owner of the town

### ISSUE THREAD

**Issue by shady2k** [MyEssentials/MyTown2#84]
Mayor of town can unclaim any town and chage town flags of any town.

**Comment by shady2k** [comment]
In MyTown2-1.7.10-0.26a.jar I'm still able to use /ta commands without OP.

**Comment by shady2k** [comment]
No, vanilla server with Forge.

**Comment by dezil** [comment]
can confirm that non op players on a forge server can still use /ta

**Comment by AfterWind** [comment]
Fixed.
