### ISSUE TITLE
Creating new town without diamonds

### ISSUE THREAD

**Issue by Hazado** [MyEssentials/MyTown2#94]
I was able to create a town without any diamonds, then unclaim the spot of that my town was in.
This created 3 diamonds for me.

I am OP'd on the server.
MyEssentials-Core-1.7.10-1.4-universal.jar
MyTown2-1.7.10-0.26a.jar

**Comment by AfterWind** [comment]
Never had this happened for a while now. I think I fixed it at some point :P
