### ISSUE TITLE
server crash (plots)

### ISSUE THREAD

**Issue by dezil** [MyEssentials/MyTown2#95]
if plot is created and then the chunk said plot is in is removed the plot is removed but if you had show plots on at the time the redstone block makers dont disaper even after toggiling vanish and show interacting with these blocks crashies the server

http://pastebin.com/0CS7smb5

**Comment by dezil** [comment]
ok so this was caused by the wild perms being set to false

**Comment by AfterWind** [comment]
Wait, what do you mean it was caused by the wild perms being set to false?

**Comment by dezil** [comment]
That crash happens when I had the wild perms for block break set to false

**Comment by dezil** [comment]
ok so this crash happens if a player trys to break blocks in another players town (crashies the server...)

same crash just new log http://pastebin.com/j4h2TbF9

**Comment by dezil** [comment]
so missed the update for myessentials core
